### ISSUE TITLE
Manual crop does not work correctly after rotating

### ISSUE THREAD

**Issue by plisiam** [guoyingtao/Mantis#104]
**Steps to reproduce**
1. Open the crop controller
2. Rotate
3. Tap and drag the LEFT-TOP corner and release
3. -> the image is cropped, but the crop area is moved elsewhere.

https://user-images.githubusercontent.com/82956823/115670781-175fe500-a34a-11eb-8dd0-b2d2dc14d25a.mov

**Comment by guoyingtao** [comment]
@plisiam I fixed this issue in the commit below
```Ruby
pod 'Mantis', :git => 'https://github.com/guoyingtao/Mantis.git', :commit => 'e1bb974da1b712aaeb46fb4f7e274289831823fd'
```

Would you mind helping to test it again? Thank you!

**Comment by plisiam** [comment]
@guoyingtao The fix looks good. Thank you
