### ISSUE TITLE
Localization does not work

### ISSUE THREAD

**Issue by VladOrackle** [guoyingtao/Mantis#110]
I am trying to get default toolbar icons localized but it does not really work. Even the example project does not seem to care about device locale or app language set in the settings. I can see that the framework contains localized strings for several languages with possible additions of new localizations.

Moreover if using SPM `LocalizedHelper.getString` can't get proper Bundle because it's always nil.

**Comment by guoyingtao** [comment]
@VladOrackle  The example project only support English and Chinese, Simplified now (although I and add more languages support in the future). I tested it by changing the iPhone to Chinese and it worked.

<img width="650" alt="image" src="https://user-images.githubusercontent.com/26723384/116441643-9d36d100-a81f-11eb-8df1-6318a25dca20.png">

<img width="403" alt="image" src="https://user-images.githubusercontent.com/26723384/116441704-acb61a00-a81f-11eb-9595-05adac3d0a38.png">

Also, LocalizedHelper.getString is an internal structure not for public usage yet.

Currently, Mantis supports 14 different languages. If the language you want is not in the list, you are welcome to submit a PR for it.

<img width="433" alt="image" src="https://user-images.githubusercontent.com/26723384/116442079-16362880-a820-11eb-8934-8dc14a3394a0.png">

**Comment by guoyingtao** [comment]
@VladOrackle I am not sure if my answer solved the issue or not. I just close this ticket for now. You can reopen it if you have further questions.
