### ISSUE TITLE
Question: Using the resizer inside a SwiftUI Sheet

### ISSUE THREAD

**Issue by Memiin** [guoyingtao/Mantis#115]
I'm have a trouble when the resizer is inside a SwiftUI sheet, when I try to resize, the sheet dragdown event starts to happen, is there any way to stop the sheet to drag down?

**Comment by guoyingtao** [comment]
@Memiin maybe you can use .fullScreenCover

**Comment by Memiin** [comment]
@guoyingtao I was using it wrong, in the simulator there is no multiple touch so that's why the sheet was trying to close, thank you
