### ISSUE TITLE
How to make dynamic  rect height for cropping? 

### ISSUE THREAD

**Issue by lincelon** [guoyingtao/Mantis#116]
Hey, thanks for that amazing library. 
Is there way to cropping image with static rect width and dynamic height?

**Comment by guoyingtao** [comment]
@lincelon Can you provide more details. When you say static rect width, does it mean you want to keep the width unchanged and adjust height only?

**Comment by lincelon** [comment]
@guoyingtao Yep, absolutely right. I want to keep the width unchanged and adjust height only and set the fixed with by pixel. 
But, I will be grateful, if you demonstrate that in two ways: by ratio and by pixel.

**Comment by guoyingtao** [comment]
@lincelon 
I think I can add a new enum like below
```Swift
public enum NonePresetRatioType {
    case freeBothDirection
    case fixWidth(ratio: Double)
    case fixHeight(ratio: Double)
}

Config {
    public var nonePresetRatioType: NonePresetRatioType = . freeBothDirection
}
```

For your case, you can set `nonePresetRatioType` to `fixWidth(ratio: your ratio)`, you can always convert pixel to ratio by divide it by the image's width

**Comment by lincelon** [comment]
Yeah, It will be super useful, thanks

**Comment by guoyingtao** [comment]
@lincelon Kind of busy now. I may do it next week.

**Comment by guoyingtao** [comment]
@lincelon Can you check if the commit below solved your issue?

```ruby
pod 'Mantis', :git => 'https://github.com/guoyingtao/Mantis.git', :commit => '3fd3c61c83382ee1eacf13a3a1adaaaca97a86d2'`
```

You can try the `Normal` example in the screenshot below.
```Swift
        var config = Mantis.Config()
        config.freeRatioType = .fixWidth(ratio: 0.4)
```
<img width="288" alt="image" src="https://user-images.githubusercontent.com/26723384/120583522-647caf80-c3fc-11eb-8ea0-9cf6a3c20084.png">

**Comment by guoyingtao** [comment]
@lincelon Do you still need this feature?

**Comment by lincelon** [comment]
Sorry for ignoring, I don't need this anymore, thanks for your work
