### ISSUE TITLE
Possible to get cropInfo from Transformation when cropViewControllerDidCrop is called

### ISSUE THREAD

**Issue by RankyLau** [guoyingtao/Mantis#119]
First of all, thank you for this amazing framework, I have a great experience using it.
However, I am running into a problem. I want to apply the same transformation as image A to image B, which both has the same dimension.
Looking into the code, it seems that there is a method called getCroppedImage() that I can use to apply the same transformation to image B. However, the delegate method cropViewControllerDidCrop only return Transformation, not CropInfo, is there a way that I can compute the CropInfo myself?
For additional info, I can still access the original image if it helps to makes the computation simpler.

EDIT:Here is the current code that I am using. It seems that it doesn't work with zooming.
CropInfo(translation: CGPoint(x: transformation.maskFrame.minX - transformation.intialMaskFrame.minX,y: transformation.maskFrame.minY - transformation.maskFrame.minY), rotation: transformation.rotation, scale: transformation.scale, cropSize: transformation.maskFrame.size, imageViewSize: transformation.intialMaskFrame.size)

**Comment by guoyingtao** [comment]
@RankyLau The Transformation actually is for applying he same transformation as image A to image B which I mentioned it in README.

There is a demo for it too.

<img width="882" alt="image" src="https://user-images.githubusercontent.com/26723384/124866164-d05cb580-df70-11eb-9278-2145f3939845.png">

<img width="377" alt="image" src="https://user-images.githubusercontent.com/26723384/124866616-904a0280-df71-11eb-8c51-da9beedf1089.png">

**Comment by RankyLau** [comment]
Thanks for your help. I have decided to just use CropViewController.processImage() since the processing for ImageB need to be done at the same time as ImageA at the background when the user zoom in or done cropping because we need to check some condition against ImageB at the same time.
