### ISSUE TITLE
Disable rotation dial

### ISSUE THREAD

**Issue by rodrigoct** [guoyingtao/Mantis#15]
Is it possible to disable rotation dial?

**Comment by guoyingtao** [comment]
@rodrigoct It is possible. I can add a switch to Config in the next release.

**Comment by guoyingtao** [comment]
@rodrigoct I released Mantis 0.43. 
If you want to hide rotation dial, set Mantis.Config.showRotationDial = false

**Comment by rodrigoct** [comment]
Cool, thank you @guoyingtao

**Comment by guoyingtao** [comment]
@m3gtrmw 
Currently you can set CropViewConfig.dialConfig = nil to hide rotation dial
I will restore showRotationDial in the next release.

**Comment by guoyingtao** [comment]
@m3gtrmw 
I released Mantis 2.0.1. Now you can use Config.cropViewConfig. showRotationDial to hide rotation dial.
