### ISSUE TITLE
Add support for changing shapes from crop view toolbar

### ISSUE THREAD

**Issue by roddymunro** [guoyingtao/Mantis#151]
It would be great to have a way to change the shape from the crop view toolbar, just like we can change the ratios. For example, tapping on the 'shape' button in the toolbar would bring up a list of shapes, and tapping one would change the crop shape. This list of shapes could be set in the config, just in case the programmer doesn't want to show the heart or star in the list.

I had a go at this, but didn't get very far due to time constraints and limited knowledge of the codebase. Adding this enhancement request in case somebody else wants to have a go at this.

**Comment by guoyingtao** [comment]
Good suggestion! I can add this feature in the next release.

**Comment by roddymunro** [comment]
Awesome!! Something else I was toying with was adding a slider for the corner radius when `.roundedRect` is selected, and hiding this slider when a different shape is selected. Not sure if that's something worth adding too.

**Comment by guoyingtao** [comment]
I will think about it. Maybe I just expose some APIs to allow user to add extra controls. 🤔

**Comment by guoyingtao** [comment]
@roddymunro 
I know this issue has been here for a long time. Now when I check it again, I think there might not be many people having this requirement. Also you can always provide crop shape options when creating CropViewController, like the one demo in the Example project
<img width="344" alt="image" src="https://github.com/guoyingtao/Mantis/assets/26723384/9fe15912-56c9-43f5-9de9-3a8fb1ae999f">
For adding a slider for the corner radius, you can always do it in your own UIs.

So I decide to close this issue for now. You can reopen it anytime if you want to discuss more.
