### ISSUE TITLE
Output offset is wrong when using `alwaysUsingOnePresetFixedRatio` and rotate the image

### ISSUE THREAD

**Issue by Mehdi-Sohrabi0** [guoyingtao/Mantis#154]
Hi,
First, Thank you for your great work.

I'm using `config.presetFixedRatioType = .alwaysUsingOnePresetFixedRatio(ratio: 16.0 / 9.0)` in my config and after rotating the image the offset report wrong value. As it is visible in the attached gif the plugin report `offset(0, 0)` which clearly is wrong. It also sometimes report offset with swapped `x` and `y`.

![Screen-Recording-2022-01-11-at-2 05 59-PM](https://user-images.githubusercontent.com/94899625/148948969-711f421e-d4f3-4148-a92f-365edb9fd17d.gif)

**Comment by guoyingtao** [comment]
@Mehdi-Sohrabi0 Thank you for the report. Mantis uses a scrollView to hold the image. The offset is the scrollView.contentOffset. When rotating the image, the scrollView is rotated too. That offset value is just used for restoring images and may not have an obvious meaning as you thought.

**Comment by Mehdi-Sohrabi0** [comment]
Hi @guoyingtao,
Thank you for your answer.

I'm aware of the situation that you are mentioning, but I'm more interested in the **image rect** after transformation.
I'm using these calculation to get the result:

````swift
let imageWidth = originalImageWidth * transform.scale
let imageHeight = originalImageHeight * transform.scale

let offsetPercentageX = transform.offset.x / (transform.maskFrame.width * transform.scale)
let offsetPercentageY = transform.offset.y / (transform.maskFrame.height * transform.scale)
let imageOffsetX = offsetPercentageX * imageWidth * -1 // from (0,0)
let imageOffsetY = offsetPercentageY * imageHeight * -1 // from (0,0)
````
 
So, when I apply rotation the `transform.offset.x` goes wrong and all of the other calculation goes wrong too.

Any help or suggestion would be appreciated;

**Comment by guoyingtao** [comment]
@Mehdi-Sohrabi0 After rotating the image, the calculation becomes complicated. The transformation values in Mantis are for restoring the scrollview status in a specific order. The final crop action will retrieve the crop information based on the restored scrollview and other UI controls.
The current calculation in Mantis relies on the multiple statuses of UI controls and I didn't get a calculation only by the transformation values.

**Comment by Mehdi-Sohrabi0** [comment]
@guoyingtao  Thanks for the explanation.

Do you have any suggestion or idea that how can I get the **image rect**?

**Comment by guoyingtao** [comment]
Hi @Mehdi-Sohrabi0 Does Mantis 1.9.0 solve this issue?

**Comment by Mehdi-Sohrabi0** [comment]
Hi, @guoyingtao Sadly No. The problem still exists;

**Comment by guoyingtao** [comment]
@Mehdi-Sohrabi0 
This issue has been here for a long time. I think I didn't understand your question very well.
If it still makes sense, can you give a more clear definition of `image rect` after transformation you mentioned above.

**Comment by guoyingtao** [comment]
@Mehdi-Sohrabi0 
Since this issue has been here for a long time so I just close it for now.
You can reopen it if you can provide more clear definition of `image rect` after transformation you mentioned above.
