### ISSUE TITLE
Rotate based on center of image?

### ISSUE THREAD

**Issue by Mehdi-Sohrabi0** [guoyingtao/Mantis#156]
Hi,

Is it possible to change rotation **anchorPoint** so rotation occurs based on `imageContainer` center not `scrollView` center?

**Comment by guoyingtao** [comment]
Currently, there are a lot of calculations related to scrollview. I am not sure if it is easy to get the correct calculation result if changing the rotation `anchorPoint` based on `imageContainer` center.

Can you give me more context about the reason you want to change it?

**Comment by guoyingtao** [comment]
Also, I think rotating based on `scrollView` center seems more natural. It looks like the Photo app on iPhone also does the same thing.

**Comment by Mehdi-Sohrabi0** [comment]
Exactly, iOS do the same thing and it is more natural :). But I have a special case that needs the rotation to be based on the image. The below video is from Samsung default gallery app, and as you can see the rotation is centered by image.
I know the calculation is too complicated, I'm trying to figure it out by myself and will let you know the result.
In the meanwhile, I'll appreciate any suggestion.  

https://user-images.githubusercontent.com/94899625/149540472-ab5d2762-8258-4695-bad4-523853c339b1.mp4

**Comment by guoyingtao** [comment]
I close this issue for now but you can reopen it if you have come out some solutions.
