### ISSUE TITLE
Image does not adapt automatically

### ISSUE THREAD

**Issue by weifans** [guoyingtao/Mantis#16]
Thank you very much for contributing this library.
I found that the picture couldn't adapt in 9:16 mode.
As shown in the figure, is there any configuration required?

![image](https://image.feicdn.cn/Mantis.png)

**Comment by guoyingtao** [comment]
@weifans Thank for the report! Can you tell me the information of your device and iOS version? Does it happen every time when you set the fixed ratio?

I tested it on iPhone 11 Pro Max and iPad Pro emulator, they seem fine.

![Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2020-01-05 at 13 29 25](https://user-images.githubusercontent.com/26723384/71784327-6dc3db80-2fc0-11ea-9f97-c6423ae890d1.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-05 at 13 29 23](https://user-images.githubusercontent.com/26723384/71784328-6dc3db80-2fc0-11ea-96be-5646835a58bc.png)

**Comment by weifans** [comment]
你的名字很像中文名字，你会说中文吗？

I use iPhone 7 and simulator iPhone 11.
Simulator iPhone Pro Max -13.3 had the same problem.
The most important operation is to pinch your hands to shrink the photo, and you will not be able to adapt to it.

**Comment by guoyingtao** [comment]
@weifans 我说中文。这确实是一个bug，我会抽空修复它。多谢反馈！

**Comment by weifans** [comment]
@guoyingtao 好的，辛苦啦

**Comment by guoyingtao** [comment]
@weifans I just release 0.44 and fixed the bug you found. You can close this issue if it solved the problem. Thanks!

**Comment by weifans** [comment]
@guoyingtao Ok thank you very much.

**Comment by guoyingtao** [comment]
@weifans Can you close this issue if it solved the problem. Thanks!
