### ISSUE TITLE
cannot install through cocoapods

### ISSUE THREAD

**Issue by MensikJan** [guoyingtao/Mantis#163]
instalation fail and created empty folders, can you repair it?

**Comment by guoyingtao** [comment]
Hi @MensikJan 

Thanks for the feedback

Can you please provide the following information?
* CocoaPods version
* Mantis version
* Xcode version
* macOS version

Thank you!

**Comment by MensikJan** [comment]
Hi,
MacOS 12.1
cocoapods-1.11.3
Mantis 1.9.0
Xcode 13.3

**Comment by guoyingtao** [comment]
Hi @MensikJan 
I can't reproduce this issue. Can you try Swift Package Manager?

**Comment by guoyingtao** [comment]
Since I haven't got response for this issue for a long time. I close it for now.
