### ISSUE TITLE
How can i get the offsetX, offsetY, cropWidth, cropHeight relative to the original image?

### ISSUE THREAD

**Issue by datbu178** [guoyingtao/Mantis#165]
Hi.
I don't use the image rotation function. I just used the simple crop function with the crop area being a rectangle. However what I want here is not crop Image, I just want the coordinates of offestX, offestY, cropWidth, cropHeight relative to the original image size. How can I get this information. Thank you!

**Comment by guoyingtao** [comment]
@datbu178 Currently Mantis does not support this Although we do provide a Transformation in a delegate function which is more complicated than what you want.

**Comment by datbu178** [comment]
After reading your code, I figured out how to get these information.
    


        let width = cropInfo.cropSize.width / (cropInfo.imageViewSize.width * cropInfo.scale)
        let height = cropInfo.cropSize.height / (cropInfo.imageViewSize.height * cropInfo.scale)
        let centerOffsetX = cropInfo.translation.x / (cropInfo.imageViewSize.width * cropInfo.scale)
        let centerOffsetY = cropInfo.translation.y / (cropInfo.imageViewSize.height * cropInfo.scale)
        
        let x = 0.5 - centerOffsetX - width/2
        let y = 0.5 - centerOffsetY - height/2
        
        return CGRect(x: x, y: y, width: width, height: height)

I hope it is correct because I have tried many different images and it gived correct results.
