### ISSUE TITLE
Usage of `CropToolbarConfig.cropToolbarHeightForVertialOrientation`.

### ISSUE THREAD

**Issue by chauhan130** [guoyingtao/Mantis#167]
Thank you for the wonderful library!

I was trying to increase the height of the toolbar. I discovered that there is actually a configuration - `Config.CropToolbarConfig.cropToolbarHeightForVertialOrientation` and `Config.CropToolbarConfig.cropToolbarWidthForHorizontalOrientation`.

But that had no effect on the controller. Turns out [the implementation](https://github.com/guoyingtao/Mantis/blob/master/Sources/Mantis/CropViewController/CropToolbar.swift#L216) is left empty.

I can, of course, define my custom Toolbar by implementing the `CropToolbarProtocol`, just wanted to know if I have to create a custom toolbar by myself for this, or if that config option would be supported in the future?

**Comment by guoyingtao** [comment]
@chauhan130 
Thanks for the feedback.

`Config.CropToolbarConfig.cropToolbarHeightForVertialOrientation` and `Config.CropToolbarConfig.cropToolbarWidthForHorizontalOrientation` is orginally designed for Custom Toolbar.
You can check the `func customizedCropToolbarButtonTouched` in the Example project.

CropToolBar can support this config option if needed in the future.

**Comment by guoyingtao** [comment]
It is supported since Mantis 2.0.0.
