### ISSUE TITLE
Add customization options

### ISSUE THREAD

**Issue by jofuelo** [guoyingtao/Mantis#168]
For a better integration of this awesome library in projects, it would be really nice to have more visual customization options. For example, colors are not customizable at all, and they don't even react to dark/light mode of the ios device. Being able to manipulate the text's and background colors would be really desirable.

For further improvement, being able to change the text size and appearance or the icons of the basic functionalities (rotate and choose the aspect ratio) would also be desirable.

**Comment by guoyingtao** [comment]
Hi @jofuelo Thanks for the feedback.

I will consider supporting customization options you mentioned in the future releases.

**Comment by guoyingtao** [comment]
Hi @jofuelo 
I will add more options like supporting customized toolbar icons / foreground-color / background-color / text size

You mentioned `they don't even react to dark/light mode of the ios device`
I noticed the native Photo app also does not react dark/light mode. I think the user experience is better for keeping the background dark.
What do you think about it?

**Comment by vanniktech** [comment]
> I think the user experience is better for keeping the background dark.

Agreed.

**Comment by guoyingtao** [comment]
Since Mantis 2.0.0 added more customization options (No support for reacting to dark mode / light mode yet), I close this issue for now.
