### ISSUE TITLE
Image Crop Area does not move smoothly

### ISSUE THREAD

**Issue by TechieSouls** [guoyingtao/Mantis#17]
Hi @guoyingtao Guoyingtao,
I am using latest Mantis 0.43 version.
I have found that since ios 13, the image cropper area does not move smoothly.
I have created a video for you. Please have a look.

https://gfycat.com/fatalkindlyadmiralbutterfly

**Comment by guoyingtao** [comment]
@TechieSouls Thanks for the feedback. I put a temp solution in the README.

You need set (cropViewController or its navigation controller).modalPresentationStyle = .fullscreen for iOS 13 when the cropViewController is presented

I haven't fingered out a better solution yet...

**Comment by TechieSouls** [comment]
O Wow @guoyingtao . setting modalPresentationStyle worked. Thankyou So much.

**Comment by guoyingtao** [comment]
@TechieSouls No problem.
