### ISSUE TITLE
Better 'SEO'

### ISSUE THREAD

**Issue by vanniktech** [guoyingtao/Mantis#174]
I've searched for a suitable Image Cropping library and I may have found it. This library isn't really findable at all through Google though when using  `ios image cropping library` or anything alike. I've found so many libraries here on GitHub, some of them stale for 3 - 5 years, all of them still listed before yours.

The only reason I found this library was your blog post. I don't know what we can do in order to raise visibility though.

**Comment by guoyingtao** [comment]
Thanks for the SEO suggestions! 
I am not familiar with SEO for Github projects. But I would love to do some research and improve SEO for this project in the future.

**Comment by vanniktech** [comment]
According to https://www.developermarkepear.com/blog/github-search-engine-optimization, it seems like:

- Name
- About
- Topics
- Stars, Watchers, and Forks (via traffic, Readme.md, and just having a project that is useful to people :) )

---

Name can't be changed really.

I guess maybe the about:

> A photo cropping tool which mimics Photo.app written by Swift.

Can be changed to something like: An iOS Image cropping library, which mimics the Photo App written in Swift.

And for the topics, I'd remove `Mantis`, `mimicphotoapp` and add `ios`

**Comment by guoyingtao** [comment]
Updated them as you suggested.
Thanks again!
