### ISSUE TITLE
Pod install super slow

### ISSUE THREAD

**Issue by vanniktech** [guoyingtao/Mantis#188]
I'm mostly working from Mobile data and installing 2.0.1 took really long (10-15 minutes)

```
-> Installing Mantis 2.0.1 (was 1.9.0)
 > Git download
 > Git download
     $ /opt/homebrew/bin/git clone https://github.com/guoyingtao/Mantis.git /var/folders/mg/nrx5qjvs09v1wfmrfrlpnd800000gn/T/d20220722-90759-68zpak --template= --single-branch --depth 1 --branch
     v2.0.1
     Cloning into '/var/folders/mg/nrx5qjvs09v1wfmrfrlpnd800000gn/T/d20220722-90759-68zpak'...
```

I guess this is mainly because of the images directory which has 26.7MB. 

Either crunch / compress the images or maybe remove some (dunno if all are actually used).

**Comment by guoyingtao** [comment]
I will exclude unnecessary files from CocoaPods release later.

**Comment by guoyingtao** [comment]
@vanniktech 
I checked Mantis.podspec. It only includes files in the `Sources` folder

```Ruby
s.source_files  = "Sources/**/*.{h,swift}"
```


So the Mantis pod is only 222k after `pod install`

I am guessing if it is because of some temporary internet issue.

**Comment by vanniktech** [comment]
Hmmm, then let's close this and if I encounter it again I'll see what's inside.

**Comment by vanniktech** [comment]
To this day I still have those issue. Now I can't even get the latest version:

```
Installing Mantis 2.22.0 (was 2.21.0)

[!] Error installing Mantis
[!] /opt/homebrew/bin/git clone https://github.com/guoyingtao/Mantis.git /var/folders/mg/nrx5qjvs09v1wfmrfrlpnd800000gn/T/d20240819-27884-r78ec8 --template= --single-branch --depth 1 --branch v2.22.0

Cloning into '/var/folders/mg/nrx5qjvs09v1wfmrfrlpnd800000gn/T/d20240819-27884-r78ec8'...
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 10 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```

**Comment by guoyingtao** [comment]
I have no idea why it happened. It looks like a network issue or maybe you can clean the pod cache and try again?

**Comment by vanniktech** [comment]
It ended up working but then I still had to wait more than 5 minutes for the pod to install. It should not be that slow.

**Comment by guoyingtao** [comment]
I close this issue for now since it looks like having nothing to do with the Mantis code
