### ISSUE TITLE
minimumZoomScale not auto applied automatically?

### ISSUE THREAD

**Issue by vanniktech** [guoyingtao/Mantis#189]
I tried this out:

```swift
config.cropViewConfig.minimumZoomScale = CGFloat(5)
```

and when selecting a picture, the cropping box still feels like it's at `CGFloat(1)`:

<img width="300" alt="Screen Shot 2022-07-22 at 12 33 16" src="https://user-images.githubusercontent.com/5759366/180421336-8bbfb60c-35a5-44d7-a831-10c676ee1582.png">

Should not it auto zoom into the picture along the center?

**Comment by guoyingtao** [comment]
I checked the code and found the current logic actually does not support custom minimumZoomScale well. If may take me more time than what I expected to tackle this issue.
I did some tries but every try broke the normal logic.
I will check the logic again when I get more time.

**Comment by guoyingtao** [comment]
@vanniktech 
Please check #190 to see if it solves the issue
