### ISSUE TITLE
The language is updated only after the application is restarted

### ISSUE THREAD

**Issue by VOTONO** [guoyingtao/Mantis#192]
Thank you for your work. But please, help me!

When I change the language in the application, the buttons remain in the previous language

- Yes, I save language in user default
- Yes, I call synnchronize

**Comment by guoyingtao** [comment]
@VOTONO When you say `When I change the language in the application`, do you mean you changed the language inside your app or in the `System Settings`?
If you did it in your app, can you show me some code? Thank you!

**Comment by VOTONO** [comment]
Inside my app. 

langCultureCode is "en" , "fr", "ru" etc.

`UserDefaults.standard.set(langCultureCode, forKey: "UserLanguage")`
`UserDefaults.standard.set([langCultureCode], forKey: "AppleLanguages")`
`UserDefaults.standard.synchronize()`   

It works well for GSMGeocoder, without restart

**Comment by guoyingtao** [comment]
@VOTONO 
Can you provide more details about how you use langCultureCode with Mantis?

**Comment by VOTONO** [comment]
This method automatically changes the language in other libraries. GMSGeocoder from Google, for example. I expected the same from Mantis.
Please tell me a way how to change the language without restarting the application.

**Comment by guoyingtao** [comment]
@VOTONO 
Finally I got a chance to address this issue by adding some new APIs.
Now you can use Manits.chooseLanguage() to set a new language without restarting app and use Mantis.resetLanguage() to reset to default behavior.

For example, if you want to change the language to German, you can use ` Manits.chooseLanguage(Mantis.Language(code: "de"))`

I haven't release a new version for it yet but you can test it in master branch.

**Comment by guoyingtao** [comment]
I think the latest Mantis supports this feature. Since no response from last August, I close this ticket for now.
