### ISSUE TITLE
How to set border width and color mask layer? 

### ISSUE THREAD

**Issue by hoangnam714** [guoyingtao/Mantis#193]
![Screen Shot 2022-08-03 at 14 16 11](https://user-images.githubusercontent.com/51524705/182547422-d25265fe-65a6-4b79-8004-930ca70f06aa.png)

I am creating 1 class of image crop by modifying this library of yours, but i have tried everything with uibenzalpath but nothing works, can someone help me

**Comment by guoyingtao** [comment]
@hoangnam714  Thanks for the feedback. It will be supported in the next release.

**Comment by hoangnam714** [comment]
@guoyingtao  thank you very much, I wish you a good day.

**Comment by hoangnam714** [comment]
Hi @guoyingtao, looks like you misunderstood me, I mean the mask of crop image can set border, because my crop UI is different from yours, the image is previewed in a black frame, but when exporting the image still is 1 square like the previous library
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-08-07 at 10 38 32](https://user-images.githubusercontent.com/51524705/183274146-a50f6ff6-a509-4500-9c5b-38337d1cd97d.png)
I have not interacted much with mask layer, can you suggest me, it is not necessary to create a new feacher
Wish you a good day!

**Comment by guoyingtao** [comment]
<img width="971" alt="image" src="https://user-images.githubusercontent.com/26723384/183306422-7af97092-c1ed-4c69-9095-518b2822a991.png">
@hoangnam714  Check `getImageWithTransparentBackground` in `UIImageExtensions.swift` to see if it helps.

**Comment by hoangnam714** [comment]
@guoyingtao  oh no, that's bad, I can't exactly find that circle transparent overlay func, can you help me a little more, thank you.

**Comment by guoyingtao** [comment]
@hoangnam714 Why do you need to find  circle transparent overlay func since you want to set the rectangle border?

**Comment by hoangnam714** [comment]
@guoyingtao because my crop frame does not have to zoom in out the whole frame, it simply has the function of cropping the image, and the red circle is the crop frame, instead of your existing square frame

**Comment by hoangnam714** [comment]
@guoyingtao mantis is very cool and i tried to figure it out, but about the transparent overlay with circular outline i still don't know how to do with it

**Comment by guoyingtao** [comment]
So you want to set the border of the circle shape mask? Because the arrow in the attached image points at the rectangle border, so I am not sure which border you want.

**Comment by hoangnam714** [comment]
i want the border inside the circle to show like on the demo image above

**Comment by hoangnam714** [comment]
@guoyingtao sorry, editing photos on mac it's a disaster, what i want is a red border inside, close to the border of the transparent overlay

**Comment by hoangnam714** [comment]
@guoyingtao I don't want to keep the square frame, I removed the square frame

**Comment by guoyingtao** [comment]
OK. I think I understand your requirement now.
Do you think this [link](https://medium.com/thefloatingpoint/how-to-make-any-uiview-into-a-circle-a3aad48eac4a) is helpful?

**Comment by hoangnam714** [comment]
@guoyingtao sorry i use google translate, i mean have circle, border radius above the mask layer, ... and that circle border is the outermost frame layer, instead of your square frame, i'm trying to do this  there
![Uploading CE329E9C-D400-4F48-92E8-993DCEDE69DA.jpeg…]()

**Comment by guoyingtao** [comment]
<img width="850" alt="image" src="https://user-images.githubusercontent.com/26723384/183706679-959ed2b5-c31f-4f4c-a1cd-5a4cef96df87.png">
It seems the image you are uploading is not done yet.
Can you upload it again? Maybe it is easier for me to understand better.

**Comment by hoangnam714** [comment]
![227D12BF-C023-4460-BD4F-B158E117968D](https://user-images.githubusercontent.com/51524705/183706968-b6567c8b-39f8-407b-b873-578ea7d77c31.jpeg)
this is the ui i want, the round frame is fixed

**Comment by hoangnam714** [comment]
Hi @guoyingtao  i found a temporary solution and it's ok, thanks for your enthusiastic support. Wish you a good day!
