### ISSUE TITLE
Flipping image horizontally and then rotating causes weird animation

### ISSUE THREAD

**Issue by vanniktech** [guoyingtao/Mantis#201]
1. Flip image horizontally
2. Rotate image

Expected behavior: The image would rotate just around itself nicely as it is done without flipping image horizontally
Actual behavior: Rotating also plays the flipping animation which looks a bit weird

https://user-images.githubusercontent.com/5759366/187065183-3fbacff1-3fa8-4674-8a25-75e0187532eb.mp4

**Comment by guoyingtao** [comment]
@vanniktech 
The mp4 only shows a still picture.
Can you either post a gif or provide a downloadable video link? Thank you!

When you say `split image`, do you mean `flip image`?
Do you mean something like `flip image then rotate it`?
![Simulator Screen Recording - iPhone 13 Pro Max - 2022-08-28 at 08 03 38](https://user-images.githubusercontent.com/26723384/187073288-495f2e6c-1ae1-4701-9af2-fa909441378f.gif)

**Comment by guoyingtao** [comment]
When you say `split image`, do you mean `flip image`?

**Comment by guoyingtao** [comment]
This is the animation for `flip image horizontally then rotate` from my test.
![Simulator Screen Recording - iPhone 13 Pro Max - 2022-08-28 at 08 03 38](https://user-images.githubusercontent.com/26723384/187073430-066198cd-fdde-4389-b584-b4cf3bb8370b.gif)

**Comment by vanniktech** [comment]
Oh yes, I meant flip. Weird, I can not reproduce in the demo. In my real application I just call the `didSelect` methods:

```
extension CropViewController : ImageEditorDelegate {
    public func flipImageHorizontally() {
        didSelectHorizontallyFlip()
    }

    public func rotateImageCounterClockwise() {
        didSelectCounterClockwiseRotate()
    }
}
```

There's nothing else happening.

**Comment by guoyingtao** [comment]
Can you use a different image to test to see if it is the same? Thank you!

**Comment by guoyingtao** [comment]
In the mp4 video, I could not see the flip animation. Can you provide a new one including the flipping animation part too?
Thank you!

**Comment by vanniktech** [comment]
Yeah here's one. Can't be that much longer since GitHub has a 10mb file upload limit:

https://user-images.githubusercontent.com/5759366/187075672-26dd17b4-49c3-4573-a016-29a563bd25ac.mp4

**Comment by guoyingtao** [comment]
I reproduced this bug. It happens when using alwaysUsingOnePresetFixedRatio
I will fix it soon

**Comment by vanniktech** [comment]
`alwaysUsingOnePresetFixedRatio` indeed, this is what I'm using!

**Comment by guoyingtao** [comment]
@vanniktech 
Please check if this PR #202 fix the issue.
