### ISSUE TITLE
Build Error in Xcode 14 beta "Signing for Mantis-Resources requires a development team"

### ISSUE THREAD

**Issue by dileepasisila** [guoyingtao/Mantis#205]
We are using Mantis 1.6.2 version for our ios application.

Currently, we are testing our app with Xcode 14 beta and ios 16 betas.

We got a new build error from Mantis Resources in Pods level in Xcode 14 beta while building the application. 
It said the development team is mandatory for Mantis Resources. 
I have attached a screenshot for more details. 

<img width="1419" alt="Screenshot 2022-08-31 at 09 44 49" src="https://user-images.githubusercontent.com/36296098/187574558-01e0c341-1b87-40db-bb60-db2345a402e9.png">

We didn't get any build error from Xcode 13 and it is only happening in Xcode 14 beta.
if we provide the team, it is resolved and but we face some issues in during deployment.

1. We use Bitrise (it is already supported for Xcode 14 beta) as a CI and We already added steps for installing CocoaPods. even though we set the development team, it will be overridden while installing CocoaPods.
2. For testing, I removed CocoaPods install steps from Bitrise, but still it is failing with 
**" No "iOS Development" signing certificate matching team ID "XXXXXXXX" with a private key was found. (in target 'Mantis-Resource' from project 'Pods')"**. I think, if we upload our certificate to Bitrise, it is used only to set up the signing process of the application level. it will not be used in the library-level setup.

Does anyone have an idea about this? it will be really helpful to us to resolve it.
I really appreciate ur feedback and comments.

**Comment by guoyingtao** [comment]
Thanks for the feedback.
I found this [link](https://stackoverflow.com/a/72600584/288724) from StackOverflow.
Can you check if it can solve the issue?

**Comment by dileepasisila** [comment]
@guoyingtao yes, that link worked for me perfectly and I have modified the pod file below modification.

`post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
          if target.name == "Mantis-Resource"
              config.build_settings["DEVELOPMENT_TEAM"] = "JJJVV93J3A"
          end
         end
    end
  end
end`

Thanks a lot for your help 🙇 
I think we can close this ticket now.
