### ISSUE TITLE
Cropped/Rotated image sometimes ends up low res

### ISSUE THREAD

**Issue by BlueCobold** [guoyingtao/Mantis#208]
Hi.

I'm using the latest Mantis and sometimes, when I crop a 581x600 image (I can reproduce on this one) by 45°, the resulting image looks like it used a low-res version to rotate and crop the image and it also ends up in only 134x139 pixels.

I have attached screenshots of the Mantis-preview and the resulting image.

You can clearly see that the pixelation is rotated 45° as well, as if Mantis used a low-res image to produce the cropped result. Can I prevent that with some kind of setting or something?

Preview:
![Simulator Screen Shot - iPhone 12 Pro - iOS 15 4 - 2022-09-08 at 08 51 45](https://user-images.githubusercontent.com/4488101/189056152-fc3f19e5-899d-4fea-b616-e87a371eac93.png)

Result:
![Simulator Screen Shot - iPhone 12 Pro - iOS 15 4 - 2022-09-08 at 08 51 54](https://user-images.githubusercontent.com/4488101/189056171-36d41472-aafa-4160-8ee4-d0aef0edadde.png)

Raw result image:
![F73505C8-3884-4B0F-961C-8CBF9446C3B5](https://user-images.githubusercontent.com/4488101/189057210-c0642d2e-d931-4fff-86b3-cce75f3fb619.jpg)

**Comment by guoyingtao** [comment]
@BlueCobold 
Thanks for reporting this issue.
Can you also post the original image here? Thank you!

**Comment by BlueCobold** [comment]
Of course.
It looks like I cannot always replicate the problem. I could replicate it a few times, though, with different rotations and cropped rectangles and between different app-launches.

![thumb_1595767609182_2090130851_](https://user-images.githubusercontent.com/4488101/189347896-ab094457-18c6-45cc-978e-4f431c8921c5.jpg)

**Comment by guoyingtao** [comment]
@BlueCobold 
I closed this issue for now since it has been here for a long time and I could not replicate it.
You can reopen it anytime if you find this issue again in the latest verion.
