### ISSUE TITLE
Area crop image

### ISSUE THREAD

**Issue by rodrigoct** [guoyingtao/Mantis#21]
Can I set a smaller square area to crop the image?

**Comment by guoyingtao** [comment]
Yes. You can set do it by setting config.presetFixedRatioType to . alwaysUsingOnePresetFixedRatio

```
var config = Mantis.Config()
config.presetFixedRatioType = .alwaysUsingOnePresetFixedRatio(ratio: 1.0)
```

Then pass this config to Mantis.cropViewController

**Comment by rodrigoct** [comment]
Yes, however I'd like a square with smaller sides. For instance, a square with 20% the width of the image

**Comment by rodrigoct** [comment]
Hello,
I set config.presetFixedRatioType = .alwaysUsingOnePresetFixedRatio(ratio: 1.0)
So the area to crop has this size below
![Captura de Tela 2020-02-13 às 13 01 55](https://user-images.githubusercontent.com/4238802/74453325-058ad400-4e61-11ea-9af7-08d7d89251cd.png)
And I'd like set this crop area to [300,300] like this one:
![Captura de Tela 2020-02-13 às 13 14 39](https://user-images.githubusercontent.com/4238802/74454529-cb223680-4e62-11ea-85ac-c6e463f91543.png)
 Thank you

**Comment by guoyingtao** [comment]
Do you mean you want to keep the size of crop area all the time? Also, do you want to move this crop area to get different cropped image?

**Comment by rodrigoct** [comment]
Yes. Yes

**Comment by guoyingtao** [comment]
It is pretty different with the current way how Mantis crop view works. I may not have enough time to add this feature. Maybe you can create a new project for it.

**Comment by rodrigoct** [comment]
I see. Thank you for the response.
