### ISSUE TITLE
recrop 

### ISSUE THREAD

**Issue by zhang646702205** [guoyingtao/Mantis#210]
now can i recrop the same with last cropinfo, and can reset to the original image

**Comment by guoyingtao** [comment]
Yes
You can search presentWithPresetTransformation in the example project. You can get transform info from the previous crop delegate function cropViewControllerDidCrop(:cropped:transformation:cropInfo:)
And just push the reset button from Crop Toolbar to reset to the original image.

**Comment by zhang646702205** [comment]
ok

**Comment by zhang646702205** [comment]
the crop view padding can not set custom?

**Comment by guoyingtao** [comment]
It is not supported currently. But if necessary I can make it customizable in a future release.

**Comment by zhang646702205** [comment]
thanks. i need it

**Comment by guoyingtao** [comment]
Just released Mantis 2.3.0 which supports customizable crop view padding.

**Comment by zhang646702205** [comment]
when i set ratio to 1:1, then reset the ratio, then set ratio to 1:1, it do not work. I see inside cropViewController
<img width="742" alt="image" src="https://user-images.githubusercontent.com/12026257/203898695-89c663d7-1251-4aaa-8718-48331f2a41b9.png">. the viewModel aspectRatie not reset when i call reset ratio. Does this is a bug?

**Comment by guoyingtao** [comment]
![Simulator Screen Recording - iPhone 13 Pro Max - 2022-11-25 at 21 44 26](https://user-images.githubusercontent.com/26723384/204069640-bce4143f-393d-427a-b9dc-696d172156f4.gif)


Hi @zhang646702205 
I tested and didn't find the issue.

Can you attach your test here? Thank you!

**Comment by zhang646702205** [comment]
https://user-images.githubusercontent.com/12026257/204181246-1b5bc897-55a9-4194-9db1-71b3de5232ea.mp4

when click free i call cropToolbarDelegate?.didSelectSetRatio(), when click other i called cropToolbarDelegate?.didSelectRatio(ratio: ratio), can show the problem。Other question：as the video shows, when i change the aspect ratio，the image always scaled。Doesn't some i used wrong?

**Comment by guoyingtao** [comment]
![sample](https://user-images.githubusercontent.com/26723384/204196913-8b369045-968b-476d-a007-daf961b966b2.jpg)

Please check the example as shown in the screenshot.

**Comment by zhang646702205** [comment]
if custom is free size cropview, then i set to 1:1, how can reset the corpview to free size?

**Comment by zhang646702205** [comment]
if i add the cropviewcontroller as a sub viewcontroller ,does in metter?

**Comment by zhang646702205** [comment]
> 

i see the demo has the same problem。when i choose a landscape image, then click 9:16 it auto scale the image。click to 16：9 is ok, when i then click the 9:16 ,it‘s scale the image again.

**Comment by zhang646702205** [comment]
when i set the ratio to 1:1, how can i reset the cropview to freedom size？

**Comment by zhang646702205** [comment]
https://user-images.githubusercontent.com/12026257/204430553-bda510b2-e7fd-42b2-9444-a13ad18ae966.mp4

As the video show, does it's a bug?

**Comment by guoyingtao** [comment]
> if custom is free size cropview, then i set to 1:1, how can reset the corpview to free size?

Currently Mantis only supports showing fixed ratio list with the free crop button, or only showing fixed ratio buttons. I may support this later if needed.

> if i add the cropviewcontroller as a sub viewcontroller ,does in metter?

I don't think it matter

> i see the demo has the same problem。when i choose a landscape image, then click 9:16 it auto scale the image。click to 16：9 is ok, when i then click the 9:16 ,it‘s scale the image again.

It is a known issue. I may improve it later.

**Comment by zhang646702205** [comment]
Thanks for reply.
