### ISSUE TITLE
Change config.cropToolbarConfig.mode is not working

### ISSUE THREAD

**Issue by boy-coderzz** [guoyingtao/Mantis#213]
I want to hide Cancel and Done button by change config.cropToolbarConfig.mode to .simple but it not working.

**Comment by guoyingtao** [comment]
Currently it needs to set CropViewController.mode to customizable. I will improve this logic in a future release.

**Comment by guoyingtao** [comment]
It is fixed in Mantis 2.3.0
You can directly set config.cropToolbarConfig.mode to embedded.
