### ISSUE TITLE
Swipe to dismiss interferes with crop box changes

### ISSUE THREAD

**Issue by vanniktech** [guoyingtao/Mantis#217]
Forgive me if my terminology is incorrect. This is how I show the cropping view controller:

```swift
let cropViewController = Mantis.cropViewController(
    image: image,
    config: config
)
cropViewController.isModalInPresentation = true // Disable swipe to dismiss functionality.

let navigationController = UINavigationController()
navigationController.setViewControllers([cropViewController], animated: true)
present(navigationController, animated: true)
```

Now, when trying to change the cropping window size the swiping interferes with another swipe listener:

https://user-images.githubusercontent.com/5759366/197788535-5fda2b64-4b5a-48bd-8f88-af442e6109ee.mp4

You can see that resizing the window must be done in multiple steps and the entire view controller also moves slightly around. Now when adding:

```diff
+navigationController.modalPresentationStyle = .fullScreen
```

I can resize like I'd expect:

https://user-images.githubusercontent.com/5759366/197788828-b212c953-d496-4e3a-8afc-7443b91e18a0.mp4

Is it possible to get the behavior from the last video while having the view being presented as it's done in the first video?

**Comment by vanniktech** [comment]
It seems like option 3 is the way to go.

> If your canvas drawing is done with manual touch handling (e.g. touchesBegan:), override -gestureRecognizerShouldBegin on your touch handling view, and return NO if the passed in gesture recognizer is a UIPanGestureRecognizer.

Isn't this something Mantis would need to do though as I don't have access to the internals?

**Comment by guoyingtao** [comment]
@vanniktech 
You are right. I will take a look when I get a chance.

**Comment by guoyingtao** [comment]
@vanniktech 
I raised PR #220 for it which fixed this issue. You can try the normal demo to see if it actually works (Which presents CorpViewController without using full screen).

**Comment by guoyingtao** [comment]
@vanniktech 
I released Mantis 2.1.2 which includes the fix for this issue. Please have a test.

**Comment by vanniktech** [comment]
Will do later today / tomorrow!

**Comment by vanniktech** [comment]
Thanks! Verified with 2.2.1
