### ISSUE TITLE
counterclockwiseRotate do not triggers CropViewControllerDelegate methods 

### ISSUE THREAD

**Issue by mikestalker** [guoyingtao/Mantis#219]
No any method from `CropViewControllerDelegate` called when used any build in transformation: `.counterclockwiseRotate, .clockwiseRotate, .alterCropper90Degree, .verticallyFlip, .horizontallyFlip`. Only  `.reset` and `.ratio` actions triggers `cropViewControllerDidEndResize` and `cropViewControllerDidBeginResize`.

Is there any chanse to get information regarding actions from standart CropToolbar without creating own CropToolbar class?

**Comment by mikestalker** [comment]
Hello @guoyingtao 
I'm using your library in application for editing photo, and after some transformations are done - there appears "Apply" button in my app. And only after user press "apply" I perform `cropViewController?.crop()`.
So I need some event in delegate that informs me that some transformations were done, before I make "Apply" button available. Currently I use `cropViewControllerDidEndResize` but it do not works for most events from `CropToolbar`.

**Comment by mikestalker** [comment]
@guoyingtao sorry for bothering you, but can you please give me hint about your thoughts regarding this? Thank you in advance

**Comment by guoyingtao** [comment]
Hi @mikestalker 
I can add more delegate functions to expose more editing events. Hope I can get a chance to do it this weekend.

**Comment by guoyingtao** [comment]
Hi @mikestalker 
I added a new function cropViewControllerDidImageTransformed in CropViewControllerDelegate in this PR #222 
Can you take a look to see if it is what you want?

**Comment by mikestalker** [comment]
Hello @guoyingtao , looks like that's what I need. Thank you for such quick fix. Waiting for 2.1.3.

**Comment by guoyingtao** [comment]
Just released Mantis 2.2.0 which should solve this issue. Can you take a look? @mikestalker

**Comment by mikestalker** [comment]
Wow. Thank you so much @guoyingtao 
Just checked - works like a charm.
As idea for future, maybe it can be useful if there is one more delegate method cropViewControllerDidImageReset - called when image reset to initial state. Not critical for me at all, just genereted idea.
Thank you one more time.
