### ISSUE TITLE
Warning for Font

### ISSUE THREAD

**Issue by StackHelp** [guoyingtao/Mantis#22]
I got a warning for font ".SFUI-Regular" suppose to be only in `iOS13 or above`

```
CoreText note: Client requested name ".SFUI-Regular", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[UIFont systemFontOfSize:].
CoreText note: Set a breakpoint on CTFontLogSystemFontNameRequest to debug.
```
After Debug, I found that it is at the line number `87` of `RotationDialPlate.swift` file.

And to solve this, I guess you have to change the font like shared [here](https://stackoverflow.com/a/58937753) or can use enum like [this answer](https://stackoverflow.com/a/58085935)

**Comment by guoyingtao** [comment]
Thanks for the report!
I found the issue is at the line 88 of RotationDialPlate.swift file.
After I changed it to 
`let cgFont = CTFontCreateUIFontForLanguage(.label, numberFont.pointSize/2, nil)`
the warnings were gone.

I will fix it in the next release.

**Comment by guoyingtao** [comment]
The warning is removed in the new release Mantis 1.0.0
