### ISSUE TITLE
Version 2.2.0 introduces a rotation UI issue when resetting changes

### ISSUE THREAD

**Issue by twomedia** [guoyingtao/Mantis#224]
I've attached a video example of the issue on V2.2.0. In the video, you can see that after I reset my rotation changes, the controls will appear under the image as I rotate. There are also a few other minor visual issues as well, including the crop tint no longer working.

I reverted to V2.1.2 & confirmed the issue doesn't occur, so it was definitely introduced in the 2.2.0 changes.

Testing on the iPhone 14 Pro Simulator running iOS 16

https://user-images.githubusercontent.com/1635048/199406209-9c98459a-fbe6-4105-a702-5bc7da8d0fa5.mov

**Comment by guoyingtao** [comment]
@twomedia 
Thanks for reporting the bug.
I released Mantis 2.2.1 which should fix the issue.
Can you take a look again? Thanks!

**Comment by twomedia** [comment]
@guoyingtao Thanks for jumping on this so quick! I can confirm that V2.2.1 addressed this bug. 

Thanks again!
