### ISSUE TITLE
App crashed when i click the done button after cropping the picture directly captured by Camera  

### ISSUE THREAD

**Issue by iftikharokz** [guoyingtao/Mantis#235]
Its working perfectly when the image is picked from gallery but when i picked the image through camera app crashed while cropping the image . getting this error **App terminated due to memory issue**

**Comment by guoyingtao** [comment]
@iftikharokz 

Thanks for the feedback.

Can you post more detailed information here? Like the call stack when crash happened or some screenshot of your Xcode.
Thank you!

**Comment by iftikharokz** [comment]
**Xcode Message when app crashed**
<img width="284" alt="Screen Shot 2022-12-02 at 8 08 49 PM" src="https://user-images.githubusercontent.com/73760345/205324339-7376e385-e673-4dcd-85dc-654b3f869fee.png">

Details

The app “NFTsGenerator” on iPhone quit unexpectedly.
Domain: IDEDebugSessionErrorDomain
Code: 10
Failure Reason: Message from debugger: Terminated due to memory issue
User Info: {
    DVTErrorCreationDateKey = "2022-12-02 15:08:32 +0000";
    IDERunOperationFailingWorker = DBGLLDBLauncher;
}
--

Analytics Event: com.apple.dt.IDERunOperationWorkerFinished : {
    "device_model" = "iPhone8,1";
    "device_osBuild" = "15.3.1 (19D52)";
    "device_platform" = "com.apple.platform.iphoneos";
    "launchSession_schemeCommand" = Run;
    "launchSession_state" = 2;
    "launchSession_targetArch" = arm64;
    "operation_duration_ms" = 46135;
    "operation_errorCode" = 10;
    "operation_errorDomain" = IDEDebugSessionErrorDomain;
    "operation_errorWorker" = DBGLLDBLauncher;
    "operation_name" = IDEiPhoneRunOperationWorkerGroup;
    "param_consoleMode" = 0;
    "param_debugger_attachToExtensions" = 0;
    "param_debugger_attachToXPC" = 1;
    "param_debugger_type" = 5;
    "param_destination_isProxy" = 0;
    "param_destination_platform" = "com.apple.platform.iphoneos";
    "param_diag_MainThreadChecker_stopOnIssue" = 0;
    "param_diag_MallocStackLogging_enableDuringAttach" = 0;
    "param_diag_MallocStackLogging_enableForXPC" = 1;
    "param_diag_allowLocationSimulation" = 1;
    "param_diag_gpu_frameCapture_enable" = 0;
    "param_diag_gpu_shaderValidation_enable" = 0;
    "param_diag_gpu_validation_enable" = 0;
    "param_diag_memoryGraphOnResourceException" = 0;
    "param_diag_queueDebugging_enable" = 1;
    "param_diag_runtimeProfile_generate" = 0;
    "param_diag_sanitizer_asan_enable" = 0;
    "param_diag_sanitizer_tsan_enable" = 0;
    "param_diag_sanitizer_tsan_stopOnIssue" = 0;
    "param_diag_sanitizer_ubsan_stopOnIssue" = 0;
    "param_diag_showNonLocalizedStrings" = 0;
    "param_diag_viewDebugging_enabled" = 1;
    "param_diag_viewDebugging_insertDylibOnLaunch" = 1;
    "param_install_style" = 0;
    "param_launcher_UID" = 2;
    "param_launcher_allowDeviceSensorReplayData" = 0;
    "param_launcher_kind" = 0;
    "param_launcher_style" = 0;
    "param_launcher_substyle" = 0;
    "param_runnable_appExtensionHostRunMode" = 0;
    "param_runnable_productType" = "com.apple.product-type.application";
    "param_runnable_swiftVersion" = "5.5.2";
    "param_runnable_type" = 2;
    "param_testing_launchedForTesting" = 0;
    "param_testing_suppressSimulatorApp" = 0;
    "param_testing_usingCLI" = 0;
    "sdk_canonicalName" = "iphoneos15.2";
    "sdk_osVersion" = "15.2";
    "sdk_variant" = iphoneos;
}
--


System Information

macOS Version 11.7 (Build 20G817)
Xcode 13.2.1 (19586) (Build 13C100)
Timestamp: 2022-12-02T20:08:32+05:00


<img width="888" alt="Screen Shot 2022-12-02 at 8 10 11 PM" src="https://user-images.githubusercontent.com/73760345/205324743-652550e4-f8f4-4ad1-8e10-0e3ac0570596.png">

but i have now solved the problem by compressing the images with high size(mb) . This library is not working on big size images .

**Comment by guoyingtao** [comment]
#95 also address the large image issue, I close it for now.
