### ISSUE TITLE
CropViewControllerDidCrop does not called

### ISSUE THREAD

**Issue by hajducak** [guoyingtao/Mantis#236]
I perfectly implemented your lib, with VIPER architecture by calling VC in fullscreen mode:
``` 
func start(crop image: UIImage) {
    var configuration: Mantis.Config = .init()
    configuration.cropViewConfig.cropShapeType = .circle(maskOnly: true)
    let cropViewController = Mantis.cropViewController(image: image, config: configuration)
    cropViewController.delegate = self
    cropViewController.modalPresentationStyle = .overFullScreen
    router.presentOver(cropViewController, animated: true)
}
```
After sending image into VC and crop UI was open, every time I hit done on toolbar nothing happens, delegate is set. Unfortunately I don't know what is wrong. I Implemented all delegates methods, after opening cropViewControllerDidImageTransformed is it called so I guess delegate is proper set, so I assume the mistakes is inside of lib. Look at ti, I will be glad for any advices. Thanks
``` 
extension CropPhotoCoordinator: CropViewControllerDelegate {
    func cropViewControllerDidCrop(
        _ cropViewController: Mantis.CropViewController,
        cropped: UIImage,
        transformation: Mantis.Transformation,
        cropInfo: Mantis.CropInfo
    ) {
        print("Crop succesfull")
        router.dismiss(animated: true)
        UserProfilePhotoManager.shared.save(profilePhoto: cropped)
    }

    func cropViewControllerDidFailToCrop(_ cropViewController: Mantis.CropViewController, original: UIImage) {
        print("Crop failed")
        UserProfilePhotoManager.shared.save(profilePhoto: original)
    }

    func cropViewControllerDidCancel(_ cropViewController: Mantis.CropViewController, original: UIImage) {
        print("Crop canceled")
        UserProfilePhotoManager.shared.save(profilePhoto: original)
    }

    func cropViewControllerDidBeginResize(_ cropViewController: Mantis.CropViewController) {
        print("DidBeginResize \(cropViewController)")
    }

    func cropViewControllerDidEndResize(_ cropViewController: Mantis.CropViewController, original: UIImage, cropInfo: Mantis.CropInfo) {
        print("DidEndResize \(cropViewController) by \(cropInfo)")
    }

    func cropViewControllerDidImageTransformed(_ cropViewController: Mantis.CropViewController) {
        print("DidImageTransformed \(cropViewController)")
    }
}
```

**Comment by guoyingtao** [comment]
@hajducak 

Did it happened to any image you wanted to crop?
Was only cropViewControllerDidImageTransformed called and other delegate functions was not called?

**Comment by hajducak** [comment]
yes it is happend evry time I use it with any photo. 
Yes only one method working (cropViewControllerDidImageTransformed) other methods not working and I have no idea why.
Can you look at it ?

**Comment by hajducak** [comment]
Okey I tried do it through SwiftUI ImageCropper based on your test showcase and this variant is working. I implemented ImageCropper with coordinator and there methods are calling, it would be worth it to discover why is not working without swiftUI. Thanks

**Comment by guoyingtao** [comment]
I am not sure why it does not work based on the information you provide. It would be more convenient if you can provide a demo code.

**Comment by guoyingtao** [comment]
Since this ticket hasn't been answered for more than one month, I closed it for now. You can reopen it anytime if you have more detail to provide.
