### ISSUE TITLE
change background from crop view controller

### ISSUE THREAD

**Issue by Azilla030** [guoyingtao/Mantis#237]
Hey everyone, 

how I change the background from the crop view controller self.
I attach an image what I mean.

Kind Regards 

Alex
![IMG_0320](https://user-images.githubusercontent.com/73437117/205895360-271dad97-6f5b-4d59-a606-e591b9c446a7.PNG)

**Comment by BagmetDenis** [comment]
I'm trying out this trick, but it's not perfect - editor.view.backgroundColor = UIColor.red

**Comment by guoyingtao** [comment]
@Azilla030 
Mantis does not support changing CropViewController background color yet, but I am considering to add it in the future.

**Comment by Azilla030** [comment]
Thanks for the information!

**Comment by guoyingtao** [comment]
In Mantis 2.10.0, you can set CropViewConfig.backgroundColor now.
