### ISSUE TITLE
Is it possible to apply transformations to the starting image?

### ISSUE THREAD

**Issue by lucagiorgettispotsoftware** [guoyingtao/Mantis#24]
I save the information obtained from CropInfo. Is there a way to reapply these transformations to start with an already transformed image and not the original one?

**Comment by guoyingtao** [comment]
@lucagiorgettispotsoftware That is a good suggestion! I can do it in the next release.

**Comment by lucagiorgettispotsoftware** [comment]
Thanks a lot, it will be highly appreciated! Approximately, when is a new release scheduled?

**Comment by guoyingtao** [comment]
Maybe in a week.

**Comment by guoyingtao** [comment]
@lucagiorgettispotsoftware I released Mantis 1.0.0 

If you want to apply transformations when showing an image, set Mantis.Config.presetTransformationType
```
public enum PresetTransformationType {
    case none
    case presetInfo(info: Transformation)
}

public typealias Transformation = (
    offset: CGPoint,
    rotation: CGFloat,
    scale: CGFloat,
    manualZoomed: Bool
)
```
Please use the transformation infomation obtained previously from delegate method cropViewControllerDidCrop(_ cropViewController: CropViewController, cropped: UIImage, transformation: Transformation).

**Comment by lucagiorgettispotsoftware** [comment]
Thanks a lot, I'll try it in the next few days!

**Comment by guoyingtao** [comment]
@lucagiorgettispotsoftware Does the solution work for you?

**Comment by lucagiorgettispotsoftware** [comment]
it works like a charm! Thank you very much! 
PS: I apologize for the late reply
