### ISSUE TITLE
If the image resolution is too low, it can't be cropped?

### ISSUE THREAD

**Issue by hyodor** [guoyingtao/Mantis#241]
Hello! I love utilizing your library. It's super convenient and easy to use. 
The thing is, the images that I've collected from the iPhone gallery works fine but the instant image doesn't work from the cropViewController. So I was wondering what's the difference between them. Then I found out that the resolution is significantly different. The image from the gallery had much better resolution(obviously). So I've increased the resolution of the Live Photo then it started working and cropping. So, my question is does image resolution affects the cropping function? Thanks.

**Comment by guoyingtao** [comment]
@hyodor 
Thanks for the feedback.
Did it only happen when taking Live Photos? Or it also happened for Still Photos?

Thanks!

**Comment by hyodor** [comment]
Sorry for the confusion. It's not the "Live Photo" from iPhone(the picture that can show movement when tapped) Rather than picking from the gallery, I just took picture on the viewController and following is how I did.

      guard let cvBuffer = CMSampleBufferGetImageBuffer(sampleBuffer) else { return }
        
        let ciImage = CIImage(cvImageBuffer: cvBuffer)
        let uiImage = UIImage(ciImage: ciImage)

            DispatchQueue.main.asyncAfter(deadline: .now() + 0.5){
                let temp_img = uiImage.jpegData(compressionQuality: 1)
                let temporary: UIImage = UIImage(data: temp_img!)!
                self.openCropVC(image: temporary)
        }

After adding compressionQuality to 1, its' resolution got better and it started to be cropped.

**Comment by guoyingtao** [comment]
It would be helpful if you can help set some breakpoints in the pod file CGImageExtensions.swift, especially for getBitmapInfo() to see what it returns.

**Comment by hyodor** [comment]
![스크린샷 2022-12-26 오전 9 23 39](https://user-images.githubusercontent.com/67180796/209485778-4687f04b-2022-4217-b1fc-67773f43f759.png)

Hi! you mean this one?

**Comment by guoyingtao** [comment]
Can you check which branch was called for getBitmapInfo() when cropping was not working?
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/26723384/209494778-7ccac822-320f-43f6-8f06-c16e2b0a8d90.png">

Also if the context is nil in the code below. Thanks!

<img width="844" alt="image" src="https://user-images.githubusercontent.com/26723384/209494930-43164cc7-0531-45ec-8757-741130f6db73.png">

**Comment by hyodor** [comment]
I've tried with the image that wasn't cropped. It seems like it doesn't call getBitmapInfo() at all. I tried a lot of ways...I guess it stops here

![스크린샷 2022-12-26 오후 4 08 29](https://user-images.githubusercontent.com/67180796/209516207-1577a4d3-083e-413e-a7c5-92a9e2e6d038.png)

It think there is no fixed image here so, it can't proceed from here.

**Comment by guoyingtao** [comment]
@hyodor Thanks for the information! 👍
cgImageWithFixedOrientation() in UIImageExtensions.swift has 3 path to return nil. Can you help to check which path it goes into?

Thank you very much! 🤝

**Comment by hyodor** [comment]
`guard let cgImage = self.cgImage, let colorSpace = cgImage.colorSpace else {
            return nil
        }`

Hello, I've set 3 breakpoints to each one of them and it stops here above. FYI, the image was 1080, 1920.

**Comment by guoyingtao** [comment]
@hyodor 
Thank you!
Can you help to make sure if cgImage is nil or colorSpace is nil?

Also, would you mind sharing your test photos here if you can export them out?

**Comment by hyodor** [comment]
![스크린샷 2022-12-27 오후 5 36 32](https://user-images.githubusercontent.com/67180796/209640119-a7f84bc1-7594-4c47-9276-11fc3e59606e.png)

I've checked and it looks like cgImage is nil. For the test photos, I've tried but it oddly works fine when I retrieve the saved image and test with it.  I guess that's because I used let data = image.jpegData(compressionQuality: 0.9)! while saving the image. I don't know how to save the screenshot other than that way. It's a bummer that I can't help :<

**Comment by guoyingtao** [comment]
@hyodor 
Thanks for the debug.

Looks like you directly created an UIImage from a CIImage which does not set up CGImage for the UIImage.

I hope that the code blow from this StackOverflow [link](https://stackoverflow.com/a/51153500) could help

```Swift
func convert(cmage:CIImage) -> UIImage
{       
    let context:CIContext = CIContext.init(options: nil)
    let cgImage:CGImage = context.createCGImage(cmage, from: cmage.extent)!        
    let image:UIImage = UIImage.init(cgImage: cgImage)        
    return image
}
```

**Comment by hyodor** [comment]
Oh wow after following your advice and converted the image by ciImage -> cgImage -> uiImage / it works now. So, it was not about the resolution but the image itself. Thanks! my question is now resolved.
