### ISSUE TITLE
Strange Crop Box behavior

### ISSUE THREAD

**Issue by vanniktech** [guoyingtao/Mantis#242]
Possibly related to https://github.com/guoyingtao/Mantis/pull/194 - although this time on a real iPhone XR with iOS 16.2 using Mantis 2.2.1

There are a few glitches:

- Starting second 8: Upsizing the image is kind of tricky. You can kind of work around it but it's hard.
- Starting second 15: When just resizing the image along the left vertical line, the crop box leaves the image boundaries completely and you're stuck in a state in which you should never be in

https://user-images.githubusercontent.com/5759366/210814863-af116395-502d-4330-9167-855742d11515.mp4

My set up looks like this:

```
config.cropViewConfig.maximumZoomScale = some value
config.cropViewConfig.cropShapeType = .rect
config.showAttachedCropToolbar = false
config.cropViewConfig.showRotationDial = false
config.cropViewConfig.cropMaskVisualEffectType = .light
config.cropToolbarConfig.toolbarButtonOptions = []
config.ratioOptions = []

Mantis.cropViewController(
    image: image,
    config: config
)
...
```

Note that I myself can't reproduce this in the Simulator and at the moment I don't have a device that I can use. That video is from my colleague.

**Comment by guoyingtao** [comment]
@vanniktech 
Thanks for the feedback! 
I also noticed the similar issue. It is a little bit tricky to fix it. I was kind of busy recently but I will begin to fix this issue once I get more time this week.

**Comment by guoyingtao** [comment]
@vanniktech 
I improved this issue in #243 
Can you help to check if it works for you? Thanks!

**Comment by guoyingtao** [comment]
I released Mantis 2.4.0 for this issue. Hope it also solve the issue of the crop box leaves the image boundaries completely. (I did not reproduce it)

**Comment by vanniktech** [comment]
Currently working on a big feature, but will test 2.4.0 soon (building a new release of our thing)

**Comment by guoyingtao** [comment]
@vanniktech 
Just want to make sure if the latest Mantis version solved the issue or not?

**Comment by vanniktech** [comment]
My colleague hasn't tested this yet. He will do it by end of the week.

**Comment by vanniktech** [comment]
This is fixed. Thanks!

**Comment by vanniktech** [comment]
On second thought, my colleague can still get the same behavior when using Mantis 2.5.1 (that should contain the fix, right?)

See the below videos:

https://user-images.githubusercontent.com/5759366/219444870-c43ac8c9-9be6-4bfb-9580-54ce8ef032e6.mp4


https://user-images.githubusercontent.com/5759366/219444885-3f28292f-6bb2-48cb-bf76-5d9a9de9c977.mp4

**Comment by guoyingtao** [comment]
@vanniktech 
Thanks for the feedback. I tried the similar operations on my iPhone but still could not reproduce the bug.
Can you help to try the things below?
1. update Mantis tot the latest version
2. Post the test pictures here then I can use the same pictures to have tests.

Also, can you also give some information of the iOS version and iPhone type your colleague is using?

Thanks!

**Comment by vanniktech** [comment]
Information:

<img width="724" alt="Screen Shot 2023-02-18 at 21 41 57" src="https://user-images.githubusercontent.com/5759366/219898392-dfc86519-f972-4a37-9c78-2675e6e5ac12.png">

These are the images:

![WhatsApp Image 2023-02-18 at 6 39 33 PM (1)](https://user-images.githubusercontent.com/5759366/219898588-dc4bbd30-47bb-41ec-abe6-4787080d7987.jpeg)
![WhatsApp Image 2023-02-18 at 6 39 33 PM](https://user-images.githubusercontent.com/5759366/219898589-1c7c85be-89cb-48ce-acf6-9be91127f70d.jpeg)

**Comment by guoyingtao** [comment]
@vanniktech 
Thanks for sharing the test pictures. Can you also provide some information about the test phone like iOS version? Thank you!

**Comment by vanniktech** [comment]
That's in the first screenshot, no? iPhone XR with iOS 16.2

**Comment by guoyingtao** [comment]
@vanniktech 
I still could not reproduce it on my iPhone and I don't have an iPhone XR.
Would it be possible for your colleague also test it on other devices too to see if it relates to devices or not? Thank you!

**Comment by vanniktech** [comment]
That's the thing. It is kind of happening only on this particular device. We've tried others as well and only he's able to reproduce this with his phone.

**Comment by vanniktech** [comment]
Another possibly related case:

![IMG_6289](https://user-images.githubusercontent.com/5759366/222462137-1ba4caa8-5c95-40bc-afdd-37dc71abac85.png)

Probably also here the crop box extended and Mantis got confused and yielded an image which is not in accordance with the required 1:1 aspect ratio.

**Comment by guoyingtao** [comment]
@vanniktech 
I noticed this issue too and changed some code. Can you try the latest Mantis version to see if you can reproduce it? Thanks!
If so, can you post the test steps and image here?

**Comment by vanniktech** [comment]
Alright, will update Mantis from 2.7.0 to 2.8.0 & report back.
