### ISSUE TITLE
MacCatalyst with mouse cannot move the cropped area works only with trackpad

### ISSUE THREAD

**Issue by imrabti** [guoyingtao/Mantis#244]
I use this library in an iPadOS app that is also supported on macOS using catalyst, I'm facing an issue that I can only move the box when I use a trackpad with a mouse there is no possibility to move it, I can only change it size.

**Comment by guoyingtao** [comment]
Mantis uses UIScrollView which needs to use two fingers to scroll for catalyst when using a trackpad.

**Comment by guoyingtao** [comment]
> Mantis uses UIScrollView which needs to use two fingers to scroll for catalyst when using a trackpad.

Hi @imrabti 
Does this solve the issue?

I also found this [link](https://stackoverflow.com/a/67761150/288724) which mentioned a private API will do the trick. Looks like Apple will support dragging in the future but for now it seems we can only scroll instead of dragging for catalyst.

**Comment by imrabti** [comment]
Hi @guoyingtao thank you for the precise answer, it solves my issue I hope apple will support this soon. Many thanks for providing us this awesome library.
