### ISSUE TITLE
Get offset, width and height in image coordinate system

### ISSUE THREAD

**Issue by Karllas** [guoyingtao/Mantis#245]
Hello. Thank you very much for the great library. I've been trying to use Mantis as UI for cropping and then converting CropInfo to orientation and CGRect in original image coordinate system so I could use it in CoreImage filters but no luck. Is there some formula how to get the CGRect in the original image coordinate system?

**Comment by guoyingtao** [comment]
Hi @Karllas 
I don't quite understand the question and may need more information.
Can you give an example of what kind of information for what kind of CoreImage filters? Thank you!

**Comment by Karllas** [comment]
First, we would like to use convert rotation angle to CGOrientation and apply it via CIImage func oriented(). Second, we would like to use CICrop filter which accepts a CGRect so we could crop the image. For this we need to get rect for cropping in original image coordinate space

**Comment by guoyingtao** [comment]
If you rotate any angle say 33º, how do you convert it to CGOrientation?

**Comment by Karllas** [comment]
We are only going to support 0, 90, 180, 270 degrees

**Comment by guoyingtao** [comment]
@Karllas 

I added CropRegion in CropInfo in this [branch](https://github.com/guoyingtao/Mantis/tree/output-crop-region)

CropInfo includes four end points with normalized coordinator in image coordinate system and rotation information. Can you check if it provides the information you need?

```Swift
public typealias CropRegion = (
    topLeft: CGPoint,
    topRight: CGPoint,
    bottomLeft: CGPoint,
    bottomRight: CGPoint,
    rotation: CGFloat
)
```

The example value looks like 
`cropRegion: (topLeft: (0.0, 0.0), topRight: (1.0, 0.0), bottomLeft: (0.0, 1.0), bottomRight: (1.0, 1.0), rotation: 0.0)`

**Comment by Karllas** [comment]
Thank you very much! If the image is not rotated all works perfectly. But if you rotate the image counter clockwise then the coordinates are flipped. Is this the expected behaviour?

**Comment by guoyingtao** [comment]
topLeft is defined relative to the view of CropViewController not relative to the image.
In your case, after rotating the image, the topLeft in CropRegion may not be topLeft relative to the image.
For example, if you counter clockwise rotate the image 90 degrees, the topLeft point in CropRegion becomes topRight point considering the rotated image coordinate system.

**Comment by Karllas** [comment]
All works perfectly. Thank you very much!

**Comment by guoyingtao** [comment]
@Karllas 
I removed rotation from CropRegion because you can get it directly from CropInfo.
I will merge the [branch](https://github.com/guoyingtao/Mantis/tree/output-crop-region) later and make a new release.
