### ISSUE TITLE
add free cropView ratio to selectable modes 

### ISSUE THREAD

**Issue by nikitaBohatyrovExitek** [guoyingtao/Mantis#249]
Hello. Thank you very much for the great library. I've been trying to find the way to use free mode of crop view resizing inside Mantis, this option already exists in mantis on load of ViewController, but that would be great to add feature of selection and using such ratio crop mode by choice, thank you in advance, I really appreciate your library, it's amazing!)

**Comment by guoyingtao** [comment]
@nikitaBohatyrovExitek 
Just to confirm if what you want is to add a new setting property to enable/disable free crop ratio in Mantis.Config?

**Comment by nikitaBohatyrovExitek** [comment]
it wood be great to enable free crop ratio the same way we select crop ratio through the func CropViewController.didSelectRatio, or make it possible to enable free crop ratio in Mantis.Config on update of CropViewController!)

**Comment by guoyingtao** [comment]
Hi @nikitaBohatyrovExitek 
CropViewController.didSelectRatio is designed for fixed ratios

There are two ways to disable free crop ratio currently by setting presetFixedRatioType in Config

1. set presetFixedRatioType to alwaysUsingOnePresetFixedRatio
2. set presetFixedRatioType to canUseMultiplePresetFixedRatio with a defaultRatio which is greater than 0 (This one has some bugs, I already fixed it in the master branch but hasn't made a new release yet)

if using canUseMultiplePresetFixedRatio(defaultRatio: 0), then free ratio is used.

**Comment by guoyingtao** [comment]
I released Mantis 2.5.0. Please check if it works for your case. 
Thanks!
