### ISSUE TITLE
About Swift package 

### ISSUE THREAD

**Issue by R3l0ad3d** [guoyingtao/Mantis#25]
i am highly requested to this team please add swift package . thanks

**Comment by guoyingtao** [comment]
@R3l0ad3d Thanks for the suggestion. I will add it in the next release.

**Comment by guoyingtao** [comment]
@R3l0ad3d I released Mantis 1.0.0 with swift package support. You can check if it works for you.

**Comment by R3l0ad3d** [comment]
thanks .
