### ISSUE TITLE
Cropped image is not getting on iOS 16.2, always getting original image after crop on done action (Tried on iPhone 13 Pro and iPhone 12 Pro)

### ISSUE THREAD

**Issue by contactme-amol** [guoyingtao/Mantis#250]
Hi Team, 

Thank you for great library, it is working fabulous. only facing issues on iOS 16.2. 

Always getting original image after crop on done action (Tried on iPhone 13 Pro and iPhone 12 Pro), and strange, this issue is not reproducible on iPhone X iOS 16.2. 

`func cropViewControllerDidCrop(_ cropViewController: CropViewController, cropped: UIImage, transformation: Transformation, cropInfo: CropInfo)`

The above delegate method is getting called and getting image in `cropped` image parameter, but original image getting instead of cropped image. 

Please help me on the same OR any properties I need to change.

**Comment by guoyingtao** [comment]
Hi @contactme-amol 

Can you debug transformedImage function in CGImageExtensions.swift to see if it returns to some unhappy paths?

**Comment by guoyingtao** [comment]
Since this issue has been here for more than one month without being responded, I closed it for now.
