### ISSUE TITLE
Unable to call didSelectHorizontallyFlip with 2.5.0

### ISSUE THREAD

**Issue by vanniktech** [guoyingtao/Mantis#254]
2.5.0 requires a CropToolbarDelegate when calling `didSelectHorizontallyFlip()` however I don't have access to one and neither do I want to create fake implementation.

I have a custom button and want to just invoke the functionality. Can we restore a version without needing a Delegate? This is currently blocking me from trying https://github.com/guoyingtao/Mantis/issues/242

**Comment by guoyingtao** [comment]
@vanniktech 
I did not make changes of didSelectHorizontallyFlip in 2.5.0 and I don't quite understand the issue. 

I remember you are using a custom Crop Toolbar and you mentioned `I have a custom button and want to just invoke the functionality`

Just want to confirm if your own Crop Toolbar delegates `didSelectHorizontallyFlip` to the Mantis.CropViewController or you have your own implementation?

**Comment by vanniktech** [comment]
Yes true. I was using 2.2.1 before and didn't update in a while.

I do not use my own Crop Toolbar delegate. I add the buttons via `viewController.navigationItem.rightBarButtonItems`

**Comment by vanniktech** [comment]
I basically just want to call `didSelectHorizontallyFlip()` & `didSelectCounterClockwiseRotate()` whenever I want to. In my case, when the user presses a button. Currently, it requires me to pass a Delegate which I don't have.

**Comment by guoyingtao** [comment]
Hi @vanniktech 
I released Mantis 2.5.1 which should solve the issue.

**Comment by guoyingtao** [comment]
@vanniktech
Just want to make sure if the latest Mantis version solved the issue or not?

**Comment by vanniktech** [comment]
Yes it did, thanks!
