### ISSUE TITLE
Cropped image is sometimes a pixel off

### ISSUE THREAD

**Issue by budidino** [guoyingtao/Mantis#259]
After cropping some images to a 1:1 square, I sometimes get results that are a bit off.
Mantis version: `2.4.0`

### My settings
```
cropVC.config.presetFixedRatioType = .alwaysUsingOnePresetFixedRatio(ratio: 1/1)
cropVC.config.cropViewConfig.cropShapeType = .circle(maskOnly: true)
```

### Example image `514 x 546`

![img](https://user-images.githubusercontent.com/1171894/215414655-5b037c52-2885-474e-8753-532b15d8285d.jpg)

### Size after cropping without zooming or panning: `514 x 513`
![Screenshot 2023-01-30 at 15 33 49](https://user-images.githubusercontent.com/1171894/215414953-34fccd11-ba9b-41ce-acfd-be53cb1ab10a.png)

-----

I've added some extra check and cropping functionality in my code to get around this issue, but it would be ideal if the result for 1:1 images was actually 1:1 😅

**Comment by guoyingtao** [comment]
@budidino 
Can you have a test using Mantis 2.5.2 which I just just released for fixing this issue? 
Thanks!

**Comment by budidino** [comment]
@guoyingtao I can confirm that it works 👍 🚀
