### ISSUE TITLE
How to get crop get after cropping?

### ISSUE THREAD

**Issue by farismhmd1** [guoyingtao/Mantis#26]
In my ios application, I want to get crop rect of the image after cropping for cropping other subviews with same image rect. So please provide me solution for that,

**Comment by guoyingtao** [comment]
I don't understand "cropping other subviews with same image rect" very clearly. Can you add more details for it? Or can you add some demo pictures? That might be helpful!

**Comment by farismhmd1** [comment]
I need image crop rect(image frame details of cropped area) after cropping.

**Comment by guoyingtao** [comment]
Do you mean you want the position and size of the red rect?
<img width="572" alt="image" src="https://user-images.githubusercontent.com/26723384/76489511-f7e45200-63fe-11ea-9c32-4cfb4c8265c0.png">

**Comment by farismhmd1** [comment]
yes, I want the same with the image transformation value.

**Comment by guoyingtao** [comment]
I added CropRectPoints to cropViewControllerDidCrop in the **cropRectInfo** branch 
```
func cropViewControllerDidCrop(_ cropViewController: CropViewController,
                                   cropped: UIImage,
                                   transformation: Transformation,
                                   cropRectPoints: CropRectPoints)
```

CropRectPoints represents the four corner points of the crop rect. The coordinates value of the points are normalized.

```
public struct CropRectPoints {
    var leftTop: CGPoint = .zero
    var rightTop: CGPoint = .zero
    var leftBottom: CGPoint = .zero
    var rightBottom: CGPoint = .zero
}
```

**Comment by farismhmd1** [comment]
ok. I'll try to use this. Thanks for the support.

**Comment by guoyingtao** [comment]
Can you let me know if it works for you? I can add it in a future release if needed.

**Comment by GreydeskChirag** [comment]
Hello Guoyingtao,

 I need CropRect after cropping the image. I read the above answer but have not found the same function in my current pod files. So please guide me for the same.

Thanks in advance.

**Comment by guoyingtao** [comment]
@GreydeskChirag There is a maskFrame in the returned transformation. Can you check if it is what you want?

**Comment by GreydeskChirag** [comment]
@guoyingtao I have check maskFrame but not getting CropRect as I needed.

I have used a 16:9 cropping ratio as the center crop.
-Main ImageSize : (640.0, 426.0)
-Cropped ImageSize : (640.0, 360.0)
-Transformation (offset: (0.0, 41.5), rotation: 0.0, scale: 1.0, manualZoomed: true, intialMaskFrame: (14.0, 302.753125, 806.0, 536.49375), maskFrame: (14.0, 344.3125, 806.0, 453.375), scrollBounds: (0.0, 41.5, 806.0, 453.375))

I need CropRect is CGRect(x: 0, y: 33, width: 640, height: 360). But maskFrame is totally different.

Thanks for your reply.

**Comment by guoyingtao** [comment]
@GreydeskChirag Since you already have `Main ImageSize : (640.0, 426.0)` and `Cropped ImageSize : (640.0, 360.0)`, I think you can get `CropRect is CGRect(x: 0, y: 33, width: 640, height: 360)` from them.
