### ISSUE TITLE
cropShapeType = .circle doesn't display a circle cutout anymore

### ISSUE THREAD

**Issue by budidino** [guoyingtao/Mantis#262]
I use `SPM`, and I recently updated from `2.4.0` to `2.5.0`, but this version doesn't display the circle crop shape when Mantis is presented.

## Screenshots

2.4.0 | 2.5.0
-|-
![IMG_E3A40746C6EC-1](https://user-images.githubusercontent.com/1171894/215493845-d14227d2-6d60-40fd-b2d9-7473db57217d.jpeg) | ![IMG_1777](https://user-images.githubusercontent.com/1171894/215493244-787d683f-4a90-4454-8a63-d8859cf22613.PNG)

## Code
```
extension EditProfileVC: UIImagePickerControllerDelegate, UINavigationControllerDelegate, CropViewControllerDelegate {

    func imagePickerController(_ picker: UIImagePickerController,
                               didFinishPickingMediaWithInfo info: [UIImagePickerController.InfoKey: Any]) {
        picker.dismiss(animated: true)
        guard let image = info[.originalImage] as? UIImage else { return }

        // setup and present the crop screen
        let cropVC = Mantis.cropViewController(image: image)
        cropVC.config.presetFixedRatioType = .alwaysUsingOnePresetFixedRatio(ratio: 1/1)
        cropVC.config.cropViewConfig.cropShapeType = .circle(maskOnly: true)
        cropVC.delegate = self
        navigationController?.present(cropVC, animated: true)
    }

    func cropViewControllerDidCrop(_ cropViewController: Mantis.CropViewController,
                                   cropped: UIImage,
                                   transformation: Mantis.Transformation,
                                   cropInfo: Mantis.CropInfo) {
        avatarManager.update(image: cropped)
        cropViewController.dismiss(animated: true)
    }

    func cropViewControllerDidCancel(_ cropViewController: Mantis.CropViewController, original: UIImage) {
        cropViewController.dismiss(animated: true)
    }
}
```

**Comment by guoyingtao** [comment]
@budidino 
For some reason I could not update to 2.5.2 from my computer, I tried 2.5.1 it did not show this issue. For 2.5.2, I didn't change any logic about crop shape, also my local code did not show this issue.

Can you try 2.5.1 to see if you can still see this issue? Also can you reinstall 2.5.2 if 2.5.1 works fine? Thanks!

**Comment by guoyingtao** [comment]
Hi @budidino 
Can you try the Example project inside Mantis with your config? Thanks!

**Comment by guoyingtao** [comment]
@budidino 
It could be because of some inside code refactor.

The working code runs as the way Mantis recommends.

The config should be prepared already before creating a CropViewController and should not be changed after that.

**Comment by budidino** [comment]
In that case, I'm closing the issue.
Until next time 👋 😆
