### ISSUE TITLE
Extend crop box by dragging on the corners outwards

### ISSUE THREAD

**Issue by vanniktech** [guoyingtao/Mantis#266]
Version 2.6.0, given this image:

<img width="312" alt="Screen Shot 2023-01-31 at 13 58 09" src="https://user-images.githubusercontent.com/5759366/215766176-95a28d2d-d1e1-491c-8e8f-fd0f7958c8c6.png">

I'd like to be able to extend the crop box (making it bigger) by dragging on the corners (drag one and then to the borders of the phone / simulator). I don't know if this ever worked but after adding the 4 other corners similar to iOS Photos it feels more natural to also try to drag on them.

The reverse (making it smaller) works already.

**Comment by guoyingtao** [comment]
@vanniktech 
It is able to extend the crop box towards one border but not two corners at the same time. (The reverse works though)
I checked iOS Photos, it works the same way.

**Comment by vanniktech** [comment]
Does not work for me. Note that I'm having a fixed aspect ratio of 1:1


https://user-images.githubusercontent.com/5759366/215796590-f32cff0d-5c3a-464f-bcec-c1b142cefd9e.mp4

**Comment by guoyingtao** [comment]
@vanniktech 
iOS Photos does not work that way either for a square crop.

**Comment by vanniktech** [comment]
Don't we want to be better than the iOS Photos app?

**Comment by guoyingtao** [comment]
@vanniktech 
Thanks for the suggestion! Of course we all want to do better jobs. I am thinking Apple might has its purpose to design like that. The basic purpose of Mantis is to mimic iOS Photos and add some customized features.
If you think it is a good feature to your project, I will consider to add that support.

**Comment by vanniktech** [comment]
It just feels natural being able to go both ways. Especially now that there are more corners available. Before it didn't bother that much.

**Comment by guoyingtao** [comment]
@vanniktech 
There are multiple limitations which need to be loosen for this feature. I tried changed some code it worked but also caused some bugs which needs some time to fix.
I will go back to this issue when I get more time.

**Comment by vanniktech** [comment]
Much appreciated!

**Comment by guoyingtao** [comment]
@vanniktech 
I fix this issue in Mantis 2.16.0. Let me know if it works for you.
