### ISSUE TITLE
Open CropViewController for inheritance

### ISSUE THREAD

**Issue by vanniktech** [guoyingtao/Mantis#270]
Would you be open to let us consumers subclass `CropViewController` ideally with a constructor using the same parameters as:

```swift
cropViewController(image: UIImage,
                               config: Mantis.Config = Mantis.Config(),
                               cropToolbar: CropToolbarProtocol = CropToolbar(frame: .zero))
```

My use case as you probably by now know is that I want to customize the menu items and currently I hack myself around this by using various extensions, however I'd like to have a dedicated view controller that I can control and where I can also do things in `viewDidLoad` etc. 

If you're open about this, I can submit a PR.

**Comment by guoyingtao** [comment]
@vanniktech 
I am not quite clear about your requirement, but you can definitely raise a PR which can help me to understand better.
Then we can have discussions based on it.

**Comment by guoyingtao** [comment]
Mantis 2.7.0 includes this feature.

**Comment by vanniktech** [comment]
Thanks!
