### ISSUE TITLE
spm version 2.7.0 error

### ISSUE THREAD

**Issue by nghia10216** [guoyingtao/Mantis#278]
![Screen Shot 2023-02-06 at 11 45 08](https://user-images.githubusercontent.com/43274501/216885623-d793af79-75d8-42ac-882c-86321c4bb4ef.png)

**Comment by guoyingtao** [comment]
@nghia10216 
Can you provide more information like your Xcode version?
I just did a test and it worked fine. (Xcode 14.2)

<img width="278" alt="image" src="https://user-images.githubusercontent.com/26723384/216886667-5f58f325-94a9-471c-a77f-8234ee638997.png">

<img width="406" alt="image" src="https://user-images.githubusercontent.com/26723384/216886855-7b711e94-6005-45c1-b6fa-152112b5d1ec.png">

**Comment by nghia10216** [comment]
I'm using
Xcode Version 13.4.1

**Comment by guoyingtao** [comment]
@nghia10216
I am not sure what caused this issue. Maybe it is because I began to release Mantis using Xcode 14 after 2.4.0
Would it be possible for you to update your Xcode to the latest version to have a test?

**Comment by seunghyun-lee** [comment]
I had the same issue on Xcode 13.4 
Unfortunately, I can't update to Xcode 14. my office work environment not allowed using the internet.
so can't update MacOS for using xcode14.
is there any solution for this issue?

**Comment by guoyingtao** [comment]
I closed this issue for now.
You can reopen it anytime if it happens to the latest Xcode.
