### ISSUE TITLE
The UI is based on Device orientation not UI orientation

### ISSUE THREAD

**Issue by yliu342** [guoyingtao/Mantis#279]
The stack view of the CropViewController is built based on the Device orientation rather than the UI orientation. This will cause the UI to break in certain scenarios. E.g. I've got an iPad app which only support portrait. My app is running fine in portrait mode but if I have the iPad rotated to landscape, my app is still running in portrait but when going to CropViewController, the stack view will assume my app is running in landscape due to it is using Device orientation and cause the tool bar to be placed on the side rather than the bottom of the screen.
![IMG_0194](https://user-images.githubusercontent.com/8564158/218340523-4e3268de-92ba-4149-8974-0a70ebcbd267.PNG)

**Comment by guoyingtao** [comment]
@yliu342 
I released Mantis 2.8.0 which should fix this issue. Can you have a try to see if it works for you?

**Comment by yliu342** [comment]
Yep 2.8.0 worked for me
