### ISSUE TITLE
Cropping from modally presented view closes both views

### ISSUE THREAD

**Issue by PerplexedFox** [guoyingtao/Mantis#28]
I have a modally presented PhotoViewController, where the photos and camera button are displayed. When I use camera/gallery, mantis gets called (via segue, as modally I get the error of already presented modal view) for photo editing. However, when I click on "done", not only the CropViewController gets dismissed but also my initial PhotoViewController. 

Is there a way to prevent this dismissal and return to the previous PhotoViewController?

**Comment by guoyingtao** [comment]
I am not quite sure about your issue.
I did some tests by adding some test code in the normalPresent function of the example project and it returned to the previous View Contoller.

```
        let testVC = UIViewController()
        testVC.view.backgroundColor = .blue
        testVC.modalPresentationStyle = .fullScreen
        present(testVC, animated: false)
        testVC.present(cropViewController, animated: true)
```
