### ISSUE TITLE
Crop Title

### ISSUE THREAD

**Issue by umair-khan97** [guoyingtao/Mantis#288]
How to add a title on the top of the Crop view? Thanks

**Comment by guoyingtao** [comment]
@umair-khan97 
Do you mean the tile on the navigation bar? If so, you can check the example project and press "Normal" button.

![image](https://user-images.githubusercontent.com/26723384/223626743-19f20b21-4053-425c-b8db-bb99128c9439.png)

![image](https://user-images.githubusercontent.com/26723384/223626984-7fa538ba-fd3c-4905-b75f-0c150da8ad8b.png)

**Comment by guoyingtao** [comment]
I closed this ticket for now since it has not bee answered since Mar 8
