### ISSUE TITLE
How can I change Grid overlay programmatically?

### ISSUE THREAD

**Issue by liamse** [guoyingtao/Mantis#29]
I use swift 4.2 (with ios 11) and my code is exactly the same as `Example/ViewController.swift/normalPresent(:)` function
```swift
        guard let image = image else {
            return
        }
        
        var config = Mantis.Config()
        
        // Comment out the code below for using preset transformation
        let transform = Mantis.Transformation(offset: CGPoint(x: 171, y: 218.33333333333334), rotation: 0.29709017276763916, scale: 1.8635663196252856, manualZoomed: true)
        config.presetTransformInfoType = .presetInfo(info: transform)
        
        let cropViewController = Mantis.cropViewController(image: image, config: config)
        cropViewController.modalPresentationStyle = .fullScreen
        cropViewController.delegate = self
        present(cropViewController, animated: true)
```

This code correctly transform, rotate, and scale the image, but I need to change the grid overlay as well. And get its information when `cropViewControllerDidCrop` is invoked.

**Comment by guoyingtao** [comment]
@liamse I am not quite sure about the issue. How do you want to change the grid overlay? Can you provide more details or post some demo pictures?

**Comment by liamse** [comment]
When I crop the image, I get the `transformation` like this:

```
 offset : (392.5, 52.5)
    - x : 392.5
    - y : 52.5
  - rotation : -0.3994811177253723
  - scale : 3.327568779701344
  - manualZoomed : true
```

What I saw in cropper is like this:
![Simulator Screen Shot - iPhone 11 - 2020-04-15 at 20 54 42](https://user-images.githubusercontent.com/3607101/79362986-88f99c00-7f5c-11ea-94bf-5b03cb7fb7cf.png)

Now I sent exact the same `transformation` in `config`

```swift
config.presetTransformInfoType = .presetInfo(info: transform)
```

 but I get following image:

![Simulator Screen Shot - iPhone 11 - 2020-04-15 at 20 55 15](https://user-images.githubusercontent.com/3607101/79363034-9a42a880-7f5c-11ea-9abf-4489f8446048.png)

The rotation, scale, and offset on image is correctly set.

The question is how I can set grid overly to be like the first image.

Thanks

**Comment by guoyingtao** [comment]
Thanks for the feedback. It seems like a bug. I will fix it.

**Comment by guoyingtao** [comment]
I solved the issue by adding **maskFrame** to Transformation and released Mantis 1.0.1.
Can you check it to see if it solves your problem?

**Comment by liamse** [comment]
Dear @guoyingtao It works but it has a little problem at rotation dial numbers. It needs to update its place. 

![Simulator Screen Shot - iPhone 11 - 2020-04-16 at 17 07 08](https://user-images.githubusercontent.com/3607101/79457136-f2cd8080-8004-11ea-939e-099990c8aa59.png)


If I change a little grid overlay, it adjusts to its correct place.

![Simulator Screen Shot - iPhone 11 - 2020-04-16 at 17 05 50](https://user-images.githubusercontent.com/3607101/79457170-024cc980-8005-11ea-8799-b59c2fe39c7d.png)

**Comment by guoyingtao** [comment]
@liamse Thanks for the feedback. I just released Mantis 1.0.2. Can you check if it solves the problem?

**Comment by liamse** [comment]
@guoyingtao  Thanks.
I do following steps but nothing changes:
1. git pull: This shows `5 files changed, 26 insertions(+), 22 deletions(-)`
2. go to Example folder and `pod install`: This shows the `Mantis 1.0.2` is installed
3. uncomment lines 41 and 42 of `ViewController.swift`

```swift
        var config = Mantis.Config()
        
        // Comment out the code below for using preset transformation
        let transform = Mantis.Transformation(offset: CGPoint(x: 469.0, y: 942.3333333333334), rotation: 0.2806850373744965, scale: 4.157221958778101, manualZoomed: true, maskFrame: CGRect(x: 99.92007104795738, y: 14.0, width: 214.15985790408524, height: 701.0))

        config.presetTransformationType = .presetInfo(info: transform)
```

and the result is same for `rotation dial numbers`.
![Simulator Screen Shot - iPhone 11 - 2020-04-16 at 19 54 31](https://user-images.githubusercontent.com/3607101/79474870-35e71e00-801c-11ea-9c18-f9e9baf63f44.png)

**Comment by guoyingtao** [comment]
@liamse Can you find  adaptAngleDashboardToCropBox() at the end of CropView.swift? If not, can you try "pod update" instead of "pod install"?

**Comment by liamse** [comment]
@guoyingtao  as you say, I find `adoptAngleDashboardToCropBox() and it works fine. The rotation dial goes its place now. 
But for iPhone 5s (small screen) the image now goes out of screen. 
![image](https://user-images.githubusercontent.com/3607101/79495857-7a81b200-803a-11ea-8323-ec4c90232848.png)
A little move in grid overlay set everything in their place.
![Simulator Screen Shot - iPhone 5s - 2020-04-16 at 23 35 09](https://user-images.githubusercontent.com/3607101/79496741-d1d45200-803b-11ea-8fde-9f7cde3c1615.png)

**Comment by guoyingtao** [comment]
@liamse The test data I got in the Example project is from a bigger screen. If you get the transformation information from your iPhone5s and use it on the same device, it should wok.
