### ISSUE TITLE
Can't implement custom behavior on the rotationDial

### ISSUE THREAD

**Issue by Mehrdadmaskull** [guoyingtao/Mantis#293]
**_RotationDial_**, **_var CropView_**  and **_RotationDialProtocol_** are all inaccessible and need to be **open** so there is access to the protocol's functions to implement custom behavior (like when the user stops the rotation, or get the angle of the rotation etc)

I can work on the changes and create a pull request

**Comment by bobby-kim-km** [comment]
🙄

**Comment by guoyingtao** [comment]
Since it issue has not got any response for more than two months, I close it for now. @Mehrdadmaskull You can reopen it anytime when you want to discuss your pull request.
