### ISSUE TITLE
Cropping handles stop working in dark area.

### ISSUE THREAD

**Issue by sheldorC137** [guoyingtao/Mantis#294]
Hello,
in this video you can see, that the handles are not working in the dark area. I think it would be nice if the handles can be used over the image area, for example:

https://user-images.githubusercontent.com/118553188/229180372-b9669b39-cc36-4939-9337-229e26056d74.mov

**Comment by guoyingtao** [comment]
@sheldorC137 
It is fixed in Mantis 2.15.0.
