### ISSUE TITLE
I cannot pod install 1.02, only have version 0.27, also cannot use your sample project.

### ISSUE THREAD

**Issue by JackyHe2882** [guoyingtao/Mantis#30]
-> Mantis (0.27)
   A swift photo cropping tool which mimics Photo.app
   pod 'Mantis', '~> 0.27'
   - Homepage: https://github.com/guoyingtao/Mantis
   - Source:   https://github.com/guoyingtao/Mantis.git
   - Versions: 0.27, 0.26, 0.25, 0.24, 0.23, 0.22, 0.21, 0.20 [master repo]
(END)

**Comment by guoyingtao** [comment]
@JackyHe2882  You can run `pod repo update` to update your local Cocoapods repo information.
