### ISSUE TITLE
Cropping returns original image

### ISSUE THREAD

**Issue by danielsaidi** [guoyingtao/Mantis#302]
Hi,

Thanks for a great library!

I'm building an OCR feature where the user should be able to select part of an image, and just noticed that some images fail to crop. 

The cropping calls `cropViewControllerDidCrop` but with the original image instead of the cropped one:

<img width="299" alt="image" src="https://github.com/guoyingtao/Mantis/assets/429927/0ee89209-1a4e-48f8-9da9-fdd313e6f188" />

For instance, regardless of which part of this podcast screenshot I select, I get the full image every time:

<img width="300" alt="image" src="https://github.com/guoyingtao/Mantis/assets/429927/1d504c10-aced-46e5-8993-a258647e3e2d" />

I use the following UIKit wrapper in SwiftUI:

```swift
struct ImageCropper: UIViewControllerRepresentable {

    var image: ImageRepresentable
    var completion: (CropResult) -> Void

    typealias CropResult = Result<ImageRepresentable, Error>

    @Environment(\.dismiss)
    var dismiss

    class Coordinator: CropViewControllerDelegate {

        init(_ cropper: ImageCropper) {
            self.cropper = cropper
        }

        var cropper: ImageCropper

        func cropViewControllerDidCrop(
            _ cropViewController: CropViewController,
            cropped: UIImage,
            transformation: Transformation,
            cropInfo: CropInfo
        ) {
            cropper.dismiss()
            cropper.completion(.success(cropped))
        }

        func cropViewControllerDidCancel(
            _ cropViewController: CropViewController,
            original: ImageRepresentable
        ) {
            cropper.dismiss()
        }

        func cropViewControllerDidFailToCrop(
            _ controller: CropViewController,
            original: ImageRepresentable) {}

        func cropViewControllerDidBeginResize(
            _ controller: CropViewController) {}

        func cropViewControllerDidEndResize(
            _ controller: CropViewController,
            original: ImageRepresentable,
            cropInfo: CropInfo) {}
    }

    func makeCoordinator() -> Coordinator {
        Coordinator(self)
    }

    func makeUIViewController(
        context: Context
    ) -> CropViewController {
        let controller = Mantis.cropViewController(image: image)
        controller.delegate = context.coordinator
        return controller
    }

    func updateUIViewController(
        _ uiViewController: CropViewController,
        context: Context
    ) {}
}
```

Here is a screenshot from where I've placed a breakpoint in the `CropView` `crop` function:

<img width="600" alt="image" src="https://github.com/guoyingtao/Mantis/assets/429927/78e37de2-5b0b-4e2b-9f2c-12ea3af1d64d">

Thankful for any help you can provide.

**Comment by guoyingtao** [comment]
@danielsaidi Thanks for the feedback.
Can you post some images which failed to crop here then I can debug with them?

**Comment by danielsaidi** [comment]
Hi @guoyingtao 

Sorry for the late reply.

To me, it happens with this image.

![IMG_5396](https://github.com/guoyingtao/Mantis/assets/429927/ad948623-1cce-46ed-93b6-f59eee88e30c)

**Comment by guoyingtao** [comment]
@danielsaidi 
Which version of Mantis are you using?
I just tested 2.9.1 (the latest version) and it is working

**Comment by danielsaidi** [comment]
Hmmm this is strange. 

I use SPM and added Mantis with the "Up to next major version" rule:

<img width="450" alt="image" src="https://github.com/guoyingtao/Mantis/assets/429927/5035f889-3572-4311-b7c9-b62e02366d23" />

This however adds `1.9.0` and not `2.9.1`:

<img width="968" alt="image" src="https://github.com/guoyingtao/Mantis/assets/429927/b8076dbc-0469-44c4-b730-e0c6ce8b879d" />

I suspect that SPM doesn't work with the Mantis version naming convention, where a `v` is added before the version number. I also noticed that version tags aren't marked as GitHub releases, which may be required (although I'm not sure).

When I first tried adding `v2.9.1` by branch, SPM first failed. This however turned out to be an "Xcode being Xcode" problem, where resetting the SPM cache made it work. 

I can confirm that the cropping works great in 2.9.1 👍

If you want to discuss the version naming conventions, just lmk.

**Comment by guoyingtao** [comment]
@danielsaidi 
I noticed the setting for SPM is `Up to next major version - 1.0.0`, Maybe you can try change it to `Up to next major version - 2.0.0`
<img width="585" alt="image" src="https://github.com/guoyingtao/Mantis/assets/26723384/4ff3bc89-7806-453d-9670-266b237f4d2a">

**Comment by danielsaidi** [comment]
@guoyingtao That was the default behavior when I tried resolving the Mantis dependency, and entering 2.0.0 caused SPM to fail to resolve the dependency altogether.

The strange thing is that when I cleared the SPM cache, things started working...which is very strange since I haven't used Mantis for a while and have cleared my cache many many times since then :)

**Comment by danielsaidi** [comment]
@guoyingtao 

I found out why this behaved so strange. I had accidentally used SSH instead of HTTPS when defining the package URL.

The default resolve is still strange, but at least now I can type 2.0.0 to get the latest 2.9.1.

<img width="450" alt="image" src="https://github.com/guoyingtao/Mantis/assets/429927/f41f3394-da89-4d0d-af6d-ccc697cf108f">
