### ISSUE TITLE
Can you make public 'func crop(by cropInfo: CropInfo) -> UIImage?'?

### ISSUE THREAD

**Issue by bobby-kim-km** [guoyingtao/Mantis#310]
Thanks your Mantis library.

I want crop image using CropInfo, not using crop-view.

Can you make public 'func crop(by cropInfo: CropInfo) -> UIImage?'?

Or

Is there any other way?

**Comment by guoyingtao** [comment]
@bobby-kim-km 
There is a public function
```Swift
public func crop(image: UIImage, by cropInfo: CropInfo) -> UIImage?
```
in Mantis.swift (at line 68)

Does it work for you?

**Comment by bobby-kim-km** [comment]
I see..

Thank u
