### ISSUE TITLE
There is a bug in the case of crop after rotating the image.

### ISSUE THREAD

**Issue by bobby-kim-km** [guoyingtao/Mantis#324]
There is a bug in the case of crop after rotating the image.

If you try to crop an image through the lower right or lower left corner after rotating the image, there is a bug where you need to drag the mouse over a certain area to operate the crop.

Please refer to the video below.

https://youtube.com/shorts/vO-aaBzdsio

**Comment by guoyingtao** [comment]
@bobby-kim-km 
Thanks for the report.
I will fix it when I get a chance.

**Comment by bobby-kim-km** [comment]
@guoyingtao 
Thanks u 😀

**Comment by guoyingtao** [comment]
Hi @bobby-kim-km 
I raised a PR #325  to fix this issue
Can you have a try to see if it solves the issue then I will make a new release. Thank you!

**Comment by bobby-kim-km** [comment]
Hi @guoyingtao 
I checked that the bug has been fixed.
Thank you 👍

**Comment by guoyingtao** [comment]
@bobby-kim-km 
I released 2.14.1 which includes this fix. Thanks for your report again.
