### ISSUE TITLE
Can I animate the reset process when reset button tapped?

### ISSUE THREAD

**Issue by asadullahpranto** [guoyingtao/Mantis#328]
Currently, when I tapping on reset button, it resets instantly, How to do reset smoothly?

**Comment by guoyingtao** [comment]
@asadullahpranto Mantis follows the same behavior with Apple’s Photos app which also has no animation when resetting, so it doesn’t support this feature currently.

**Comment by asadullahpranto** [comment]
I just wanted to take a moment to thank you for sharing your fantastic GitHub repository. It's been incredibly helpful to me, and I'm sure many others as well. 

your are wonderful @guoyingtao.

**Comment by guoyingtao** [comment]
@asadullahpranto Thank you! I am really happy to hear this repository is helpful to you.
