### ISSUE TITLE
Delegate function to listen to background color change

### ISSUE THREAD

**Issue by JonasHiltl** [guoyingtao/Mantis#329]
It would be great if we can listen to the color change of the background of the `CropView`.
I'm imagining a function like this on the `CropViewControllerDelegate`
```swift
func cropViewControllerDidChangeBackground(_ cropViewController: CropViewController, background: UIColor)
```

**Comment by guoyingtao** [comment]
@JonasHiltl Can you add some explanations or a use case for the purpose of this delegate?

**Comment by JonasHiltl** [comment]
@guoyingtao I'm building a UI which has a Crop and Filter screen and I want to sync the background of the crop screen to the filter screen.

I know that I can customise the background of the crop screen but I quite like the default background which is the average color of the image.

Crop Screen             |  Filter Screen
:-------------------------:|:-------------------------:
![](https://github.com/guoyingtao/Mantis/assets/71456708/59dc108a-7d0d-4989-9a91-25bef399fe7a)  |  ![](https://github.com/guoyingtao/Mantis/assets/71456708/3cac18d8-359c-4e33-8616-1888ba82b208)

**Comment by guoyingtao** [comment]
@JonasHiltl The default background is a blur effect which changes color at different spots.

**Comment by JonasHiltl** [comment]
@guoyingtao Ok, I thought it was the average color of the currently selected area, similar to [this](https://www.hackingwithswift.com/example-code/media/how-to-read-the-average-color-of-a-uiimage-using-ciareaaverage). But if it's just a blur than my proposal makes no sense.
