### ISSUE TITLE
Every time I tapped on the reset button, the dimming view gets darken!!

### ISSUE THREAD

**Issue by asadullahpranto** [guoyingtao/Mantis#330]
Regeneration process: 

Just modify the cropView and reset(repeat this process without tapping cancel button)

My observation: 
When you resetting the crop process, the dimming layer is not removing. That's why every time a brand new dimming layer is adding on the previous dimming layer. 

I'm guessing this issue is occurring for the method inside "CropDimmingView" & "CropMaskVisualEffectView": 

```
func setMask(cropRatio: CGFloat) {
        let layer = createOverLayer(opacity: 0.5, cropRatio: cropRatio)
        self.layer.addSublayer(layer)
        innerLayer = layer
}
```

See the following method too inside the "CropMaskViewManager":

```
func setup(in view: UIView, cropRatio: CGFloat = 1.0) {
        maskViews.forEach { maskView in
            maskView.initialize(cropRatio: cropRatio)
            maskView.isUserInteractionEnabled = false
            view.addSubview(maskView)
        }

        showVisualEffectBackground()
}
```

```
func removeMaskViews() {
        maskViews.forEach { $0.removeFromSuperview() }
}
```

**Comment by guoyingtao** [comment]
@asadullahpranto Thanks for reporting this bug! I will fix it in the next release.
