### ISSUE TITLE
Minimum image cropping size in pixels

### ISSUE THREAD

**Issue by kiddden** [guoyingtao/Mantis#333]
I have an image editor with the fixed ratio(1:1), however I also want to limit zoom and cropping in pixels, so a user can't crop an image to size smaller than 1000x1000 px(or if one of the sides of a photo is smaller than 1000px, then we set the minimum size to this side value).

I'm wondering if it is possible in the latest version of Mantis?

**Comment by vanniktech** [comment]
Yes. You need to calculate it yourself though:

```swift
config.cropViewConfig.maximumZoomScale = imageRequirements.maximumZoomScale()
```

Here's my Kotlin code which does the calculation:

```kotlin
  /** This is useful so that you can't zoom in so far that the image will be smaller than our [minSize]. */
  @IosOnly fun maximumZoomScale(size: Size): Float {
    val minSize = minSize()
    val widthRatio = size.width / minSize.width.toFloat()
    val heightRatio = size.height / minSize.height.toFloat()

    return when {
      aspectRatio != null && size.width > size.height -> maxOf(widthRatio, heightRatio)
      else -> minOf(widthRatio, heightRatio)
    }
  }
```

**Comment by kiddden** [comment]
@vanniktech Thanks! This helps a lot, but could you share your minSize() function implementation?

**Comment by vanniktech** [comment]
`minSizePx` is 1000 in your case:

```kotlin
fun minSize() = (aspectRatio ?: AspectRatio.IDENTITY).minSize(minSizePx)

@Parcelize data class AspectRatio(
  val x: Int,
  val y: Int,
) : Parcelable {
  fun minSize(size: Int): Size {
    val min = minOf(x, y)
    return Size(
      width = maxOf(x, size / min * x),
      height = maxOf(y, size / min * y),
    )
  }

  companion object {
    val IDENTITY = AspectRatio(x = 1, y = 1)
  }
}
```

I do support different aspect ratios as well though. If you don't need that you can drop it.

**Comment by kiddden** [comment]
@vanniktech thank you! That resolved my problem
