### ISSUE TITLE
Picture orientation detection not working for iPhone Selfie Camera

### ISSUE THREAD

**Issue by cfmedicus** [guoyingtao/Mantis#335]
If you want to use the automatic ratios for cropping and the source is a iPhone selfie camera picture mantis only suggest rations for landscape pictures, even if source is a portrait one. Also the usage of “original”-ratio use a landscape one.

**Comment by guoyingtao** [comment]
@cfmedicus 
Thanks for pointing it out.
I will fix it in the next release.

**Comment by guoyingtao** [comment]
It is fixed in Mantis 2.15.0.
