### ISSUE TITLE
Trouble with the Swift Example

### ISSUE THREAD

**Issue by EzequielAdrianM** [guoyingtao/Mantis#338]
I am trying to execute the Mantis cropper sample project for SwiftUI but it fails in ImageCropper.swift at the following line:

`cropViewController.delegate = context.coordinator`

Xcode says: Cannot assign value of type ImageCropper.Coordinator to type (any CropViewControllerDelegate)?

When I comment out that line, the app builds but the Crop and Cancel buttons of the cropper do nothing.

Mantis version: 2.14.1

Any clues would be of great help.

**Comment by guoyingtao** [comment]
@EzequielAdrianM 
What is your Xcode version?

**Comment by guoyingtao** [comment]
Can you try a formal Xcode 15.0 (not beta)? Maybe rerun `pod install` too.
I am using 15.0 (15A240d) and haven't seen the issue yet.

**Comment by EzequielAdrianM** [comment]
It was an issue of mine. I was accidentally redeclaring the delegate somewhere else in the code. Thanks for your time!
