### ISSUE TITLE
When re-entering crop, apply crop/transformation data before displaying the image

### ISSUE THREAD

**Issue by xinatanil** [guoyingtao/Mantis#341]
When you re-enter crop, first you see the full image and only then it applies the crop info. While works, it would be nice to apply crop data before displaying the image.

**Comment by guoyingtao** [comment]
@xinatanil 
Thanks for the suggestion.
Please check PR #343 to see it works for you.

**Comment by guoyingtao** [comment]
It is fixed in Mantis 2.15.0.
