### ISSUE TITLE
Make aspect ratio functions public

### ISSUE THREAD

**Issue by xinatanil** [guoyingtao/Mantis#347]
The only limitation that doesn't allow us to build a custom UI wrapper around CropViewController is that aspect ratio functions are not public.
I suggest making `CropViewController.setFixedRatio` and `CropViewController.setFreeRatio` functions `public`.

**Comment by guoyingtao** [comment]
Mantis uses one `ratio selection button` to toggle `fixed ratios` and `free ratio`. Generally users don't need to use setFixedRatio and setFreeRatio.
Can you give me more details about your custom UI wrapper? @xinatanil

**Comment by xinatanil** [comment]
We're just trying to replicate Photos.app UI, which allows user to choose between fixed ratios and freeform

![Simulator Screenshot - iPhone 15 - 2023-11-01 at 21 10 06](https://github.com/guoyingtao/Mantis/assets/11419059/e2458ff0-65e6-4524-8e27-50d973976b10)

**Comment by guoyingtao** [comment]
If you check CustomizedCropToolbarWithoutList in Example project, you can see it uses delegate?.didSelectRatio(self, ratio: 9 / 16) to do the similar thing. `CropToolbarDelegate` also provides didSelectFreeRatio.

Can you check if you can use CropToolbarDelegate as code in CustomizedCropToolbarWithoutList?

**Comment by xinatanil** [comment]
Yeah, the first thing I tried to do is to use CropToolBar methods, but the API was too complicated, and if I remember correctly, it still didn't allow us to add freeform ratio to the list (which was essential to us).
I think that CropViewController doesn't need to provide such complicated APIs.
I think that there should be only two ways to use CropViewController:
1. Use default UI that provides little configuration.
2. Build your own custom UI around embedded CropViewController. It's impossible to support everyone's UI needs, so it'd be easier to provide an API so that anyone could build any UI he wants.

**Comment by guoyingtao** [comment]
@xinatanil 
Thanks for your suggestion. 
CropViewController conforms to CropToolbarDelegate so it has some public functions already like `didSelectFreeRatio` and `didSelectRatio` which actually call private functions like `setFixedRatio` and `setFreeRatio`.
Do you think you can directly use them didSelectFreeRatio` and `didSelectRatio`?

**Comment by xinatanil** [comment]
Yes, actually, I can!
Thank you for the hint, I don't know how I was unable to notice them in the first place!
Thank you for the library!

**Comment by guoyingtao** [comment]
@xinatanil 
I just noticed didSelectRatio does not provide `zoom` parameter as setFixedRatio does. In your sample code, you always set `zoom` to `false` in `setFixedRatio`.
If you still want `zoom` to be `false`, then I need to add `zoom` parameter to `didSelectRatio`.
