### ISSUE TITLE
Regarding the issue of the cropping box following the rotation of the image

### ISSUE THREAD

**Issue by HanX1ao** [guoyingtao/Mantis#356]
No matter how the image is rotated, we need to keep the cropping frame fixed to landscape mode. Is it possible to provide a method to prevent the cropping frame from rotating with the image?
Thanks

**Comment by guoyingtao** [comment]
@HanX1ao 
Please check PR #357 to see if it works for you.
To test the new feature, you need to set CropViewConfig.fixCropBoxWhenRotating90Degree = true

**Comment by HanX1ao** [comment]
@guoyingtao it looks like fine

**Comment by guoyingtao** [comment]
@HanX1ao 
I rename `fixCropBoxWhenRotating90Degree` to **rotateCropBoxFor90DegreeRotation**, now you need to set `CropViewConfig. rotateCropBoxFor90DegreeRotation` to **false** for tests.
I just released Mantis 1.7.0 which includes this feature. Please let me know if it works for you.

**Comment by guoyingtao** [comment]
@HanX1ao 
I closed this ticket since the latest release includes this feature. You can reopen it if it does not work for you.
