### ISSUE TITLE
Mantis crop result has transparency

### ISSUE THREAD

**Issue by EzequielAdrianM** [guoyingtao/Mantis#359]
We are using Mantis for cropping UIImage. Original size is about 870kb but after cropping the Mantis result is about 2mb. After analyzing the images, we detected that Mantis transformed the 3 channel image to a 4 channel (added Alpha). There is no way to disable alpha in Mantis.Config()

We used this extension to check the number of channels of the UIImage:

```
extension UIImage {
    var hasAlpha: Bool {
        guard let alphaInfo = self.cgImage?.alphaInfo else {return false}
        return alphaInfo != CGImageAlphaInfo.none &&
            alphaInfo != CGImageAlphaInfo.noneSkipFirst &&
            alphaInfo != CGImageAlphaInfo.noneSkipLast
    }
}
```

**Comment by guoyingtao** [comment]
@EzequielAdrianM 
Thanks for pointing it out. I will fix it in the next release.

**Comment by guoyingtao** [comment]
@EzequielAdrianM 
Would you mind posting one of your test images with only 3 channels here? Thank you!

**Comment by EzequielAdrianM** [comment]
![IMG_4895](https://github.com/guoyingtao/Mantis/assets/8314884/55894ec1-61b1-4d51-8adf-9b9e0d8273d1)

**Comment by guoyingtao** [comment]
@EzequielAdrianM 
Thanks for providing the test image.
Please check the PR #360 to see if it works for you.

**Comment by EzequielAdrianM** [comment]
Yes, now if the initial image does not have transparency, the cropper result returns an image without transparency.

**Comment by guoyingtao** [comment]
@EzequielAdrianM 
I release Mantis 2.17.1 which includes this fix.
