### ISSUE TITLE
Image Dimension Issue

### ISSUE THREAD

**Issue by mschonvogel** [guoyingtao/Mantis#36]
When the image already has the aspect ratio applied, and you select it again it keeps on zooming in
Expected behavior:
- Either disable the aspect ratio action or don't zoom in again

![image-dimension](https://user-images.githubusercontent.com/370839/80861727-a6bf4480-8c70-11ea-8838-2d856afb0fec.gif)

**Comment by guoyingtao** [comment]
@mschonvogel Mantis 1.2.0 is released which fixed this issue.

**Comment by mschonvogel** [comment]
Thanks for fixing, it works!
