### ISSUE TITLE
[Req] Image Opacity update feature

### ISSUE THREAD

**Issue by bobby-kim-km** [guoyingtao/Mantis#369]
Can you add public function that image opacity update feature in CropViewController?

**Comment by bobby-kim-km** [comment]
I can pull req

**Comment by guoyingtao** [comment]
@bobby-kim-km 
I don't quite understand this requirement yet but you are welcome to raise your PR.

**Comment by bobby-kim-km** [comment]
@guoyingtao 

[PR371](https://github.com/guoyingtao/Mantis/pull/371)
This is my PR
If you need anything else, please tell me.
Thank you.

**Comment by guoyingtao** [comment]
@bobby-kim-km 
Thanks for the PR! It is a good idea to add more features like that, but currently Mantis is an **image cropping** library which focus more on operations like translation, rotation, scale, flip, skew(To do), etc.
I think adjusting image alpha could belong to another image adjusting library like adjusting brightness, contrast, etc.

**Comment by guoyingtao** [comment]
I close this issue for now. If you want to discuss it again, you can reopen it any time. @bobby-kim-km
