### ISSUE TITLE
Stops cropping when moving outside the CropOverlayView

### ISSUE THREAD

**Issue by mschonvogel** [guoyingtao/Mantis#37]
Expected behavior: Don't stop cropping if, during the cropping, the finger moves outside of the CropOverlayView. 
![image-cropping-issue](https://user-images.githubusercontent.com/370839/80862051-90b28380-8c72-11ea-89d6-3d375c1675d4.gif)

Also, sometimes (after doing some cropping) the CropOverlay doesn't let me resize it at all.

**Comment by guoyingtao** [comment]
@mschonvogel Mantis 1.2.0 is released which fixed this issue.

**Comment by mschonvogel** [comment]
Thank you, I've tested it and it works 👍
