### ISSUE TITLE
How to get Coordinates of Cropped image with respect to Original image 

### ISSUE THREAD

**Issue by kumarlav0** [guoyingtao/Mantis#372]
In my use case, I want to get coordinates of cropped image with respect to original image. 

Like, in this method
```
func cropViewControllerDidCrop(_ cropViewController: CropViewController,
                               cropped: UIImage,
                               transformation: Transformation,
                               cropInfo: CropInfo) {
    //        print("crop info::", cropInfo)
    // CropInfo = (translation: CGPoint, rotation: CGFloat, scale: CGFloat, cropSize: CGSize, imageViewSize: CGSize)
}
```

I am getting cropped info and cropped image. But, is there any way to calculate or get cropped image coordinate with respect to original image. 
Coordinates - (X,Y, Height & Width)

**Comment by guoyingtao** [comment]
If no rotation, maybe you can try using `offset` multiplying `scale` in returned `transformation`

**Comment by kumarlav0** [comment]
> If no rotation, maybe you can try using `offset` multiplying `scale` in returned `transformation`
What is offset in this case ?

I tried using  transformation 
X point multiply scale = x  coordinate
Y point multiply scale = y coordinate

But it is not correct calculation.

**Comment by kumarlav0** [comment]
> Hi @kumarlav0 Can you try calculating it by using `translation` and `scale` in returned `cropInfo` if no rotation?

Yes, I am trying using translation, as I mentioned in the above comment, 

I also Used this function to calculate coordinates,

```
func calculateCroppedImageCoordinates(cropInfo: CropInfo) -> CGRect {
        let translationX = cropInfo.translation.x
        let translationY = cropInfo.translation.y
        let scale = cropInfo.scale
        let rotation = cropInfo.rotation
        let cropWidth = cropInfo.cropSize.width
        let cropHeight = cropInfo.cropSize.height
        let imageViewWidth = cropInfo.imageViewSize.width
        let imageViewHeight = cropInfo.imageViewSize.height
        
        // Calculate the offset caused by translation
        let offsetX = translationX / scale
        let offsetY = translationY / scale
        
        // Adjust the crop size based on the scale factor
        let adjustedCropWidth = cropWidth / scale
        let adjustedCropHeight = cropHeight / scale
        
        // Apply rotation to the coordinates
        let rotatedWidth = abs(cos(rotation)) * adjustedCropWidth + abs(sin(rotation)) * adjustedCropHeight
        let rotatedHeight = abs(sin(rotation)) * adjustedCropWidth + abs(cos(rotation)) * adjustedCropHeight
        
        // Calculate the coordinates of the cropped image with respect to the original image
        let croppedX = (offsetX + (imageViewWidth - rotatedWidth) / 2)
        let croppedY = (offsetY + (imageViewHeight - rotatedHeight) / 2)
        
        return CGRect(x: croppedX, y: croppedY, width: rotatedWidth, height: rotatedHeight)
    }

```

But, no solution is working for me exactly, Can you please help me to find exact way or exact coordinates ?

**Comment by guoyingtao** [comment]
Hi @kumarlav0 
Can you check `CropRegion` in returned `CropInfo` which includes the normalized values of four vertices of the crop region.

**Comment by kumarlav0** [comment]
> Hi @kumarlav0 Can you check `CropRegion` in returned `CropInfo` which includes the normalized values of four vertices of the crop region.
> 
> ```swift
> public struct CropRegion: Equatable {
>     public var topLeft: CGPoint
>     public var topRight: CGPoint
>     public var bottomLeft: CGPoint
>     public var bottomRight: CGPoint
> }
> ```

Yes Exactly I want this CropRegion, But how to get this CropRegion from this methods?

cropViewControllerDidCrop

**Comment by guoyingtao** [comment]
It should be included in `CropInfo`

```Swift
public typealias CropInfo = (
    translation: CGPoint,
    rotation: CGFloat,
    scaleX: CGFloat,
    scaleY: CGFloat,
    cropSize: CGSize,
    imageViewSize: CGSize,
    cropRegion: CropRegion
)
```

**Comment by kumarlav0** [comment]
> ```swift
> CropRegion
> ```

Crop Info have only these Values

public typealias CropInfo = (translation: CGPoint, rotation: CGFloat, scale: CGFloat, cropSize: CGSize, imageViewSize: CGSize)

But I am not getting cropRegion: CropRegion in your library.

**Comment by guoyingtao** [comment]
@kumarlav0 
What version of Mantis are you using?

**Comment by guoyingtao** [comment]
`CropRegion` is available since 2.10.0
You can update Mantis to the latest version.

**Comment by guoyingtao** [comment]
The current version is 2.18.0

But please notice that upgrading from 1.9.0 to 2.x.x, you need to solve some issues of breaking changes.

![image](https://github.com/guoyingtao/Mantis/assets/26723384/69ef8c56-717b-4bcc-93d7-f504b2b4153b)

**Comment by kumarlav0** [comment]
Sure, Let me try this

**Comment by guoyingtao** [comment]
Please also check #245 to see if it looks similar with this issue. I might add CropRegion for the similar region.

**Comment by guoyingtao** [comment]
@kumarlav0 
Does CropRegion work for you?

**Comment by kumarlav0** [comment]
> @kumarlav0 Does CropRegion work for you?

Yes, It worked for me. Thank you
