### ISSUE TITLE
Error Cannot inherit from non-open class 'CropViewController' outside of its defining module

### ISSUE THREAD

**Issue by hoangnam714** [guoyingtao/Mantis#385]
i am getting this error when inheriting CropViewController
<img width="889" alt="image" src="https://github.com/guoyingtao/Mantis/assets/51524705/04cb6b70-f8fd-455a-82c6-b2ebab5f8c19">

**Comment by guoyingtao** [comment]
@hoangnam714 
Which version are you using?

**Comment by hoangnam714** [comment]
i am using CropViewController latest version, i using spm to install

**Comment by guoyingtao** [comment]
@hoangnam714 
For some reason, SPM still shows 1.7.5
<img width="460" alt="image" src="https://github.com/guoyingtao/Mantis/assets/26723384/98a7ead7-b1ef-4fd5-be9f-6d92cafe9edb">

Can you use exact version 2.19.0 instead for now
<img width="446" alt="image" src="https://github.com/guoyingtao/Mantis/assets/26723384/7fbd1595-a0bf-4c90-b41e-1923298e5bcd">

**Comment by guoyingtao** [comment]
I tested with SPM exact version and it worked for me. 
Let me know if it solved your issue.

**Comment by guoyingtao** [comment]
@hoangnam714 
I haven't heard feedback from you for a while so I just close this ticket for now. You can reopen it anytime if you still have the issue.

**Comment by smalldevcloud** [comment]
> @hoangnam714 For some reason, SPM still shows 1.7.5 <img alt="image" width="460" src="https://private-user-images.githubusercontent.com/26723384/316414197-98a7ead7-b1ef-4fd5-be9f-6d92cafe9edb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NjQxMTIsIm5iZiI6MTcyMzQ2MzgxMiwicGF0aCI6Ii8yNjcyMzM4NC8zMTY0MTQxOTctOThhN2VhZDctYjFlZi00ZmQ1LWJlOWYtNmQ5MmNhZmU5ZWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDExNTY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2YTliOGU3MTUxYWZmNGI2NWQ0NGUxZTZkYWY2MzdiM2E0YjMyM2VmZWQ5ZWYyOGI0YzhmNTRhOGE1NjEwZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r-yT9-wftSaeK1hNFWG8Ufa8k79xCGc-Y2aouLwXVCk">
> 
> Can you use exact version 2.19.0 instead for now <img alt="image" width="446" src="https://private-user-images.githubusercontent.com/26723384/316414347-7fbd1595-a0bf-4c90-b41e-1923298e5bcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NjQxMTIsIm5iZiI6MTcyMzQ2MzgxMiwicGF0aCI6Ii8yNjcyMzM4NC8zMTY0MTQzNDctN2ZiZDE1OTUtYTBiZi00YzkwLWI0MWUtMTkyMzI5OGU1YmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDExNTY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4YzFjYjlmYWJmYWFhNzRlOGMxZTI3MDFlYWY4YTNjY2U2NDYwMWRiNWYzYWQ4ZTY3ZTVjZGQ4YmM0YWU0YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YcrWGEMkYwqezgLXvABH1KQXho9O6G5fVu6sLYXJYVI">

Thanks, that's the solution
