### ISSUE TITLE
Delegate method returns uncroped image when cropping a screen shot of current PDView page

### ISSUE THREAD

**Issue by SaiBalaji-PSS** [guoyingtao/Mantis#386]
I'm trying to take a screen shot of current pdf page displayed using PDFKit. And crop it further using Mantis, 

Here is my screen shot code and I'm passing the image to mantis. But the mantis delegate method  
`  func cropViewControllerDidCrop(_ cropViewController: Mantis.CropViewController, cropped: UIImage, transformation: Mantis.Transformation, cropInfo: Mantis.CropInfo)`
returns uncropped image as output.
```

  @objc func takeScreenShot(){
        if let pdfPage = pdfView.currentPage, let pdfDocument = pdfView.document {
            let pdfPageRect = pdfPage.bounds(for: .mediaBox)
            let renderer = UIGraphicsImageRenderer(size: pdfPageRect.size)
            let pimage = renderer.image { ctx in
                UIColor.white.set()
                ctx.fill(pdfPageRect)
                ctx.cgContext.translateBy(x: 0.0, y: pdfPageRect.size.height)
                ctx.cgContext.scaleBy(x: 1.0, y: -1.0)
                pdfPage.draw(with: .cropBox, to: ctx.cgContext)
            }
            
           //  Present cropping view
            let cropViewController = Mantis.cropViewController(image: pimage)
            cropViewController.delegate = self
            cropViewController.modalPresentationStyle = .fullScreen // Ensure it's fullscreen
            present(cropViewController, animated: true)

        }
    }
```
Here I have cropped particular part of the screen shot image of pdf page
![Simulator Screenshot - iPhone 15 Pro - 2024-03-25 at 22 49 13](https://github.com/guoyingtao/Mantis/assets/51410810/8ef77e79-6732-4b11-a00a-d23c4830b05e)
But when loading the cropped image on UIImage it gives uncropped image 

```
extension ReaderVC: CropViewControllerDelegate{
    func cropViewControllerDidCrop(_ cropViewController: Mantis.CropViewController, cropped: UIImage, transformation: Mantis.Transformation, cropInfo: Mantis.CropInfo) {
        cropped.saveToPhotoLibrary(nil, nil)
        print(cropInfo)
        self.dismiss(animated: true)
        let vc = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "TestVC") as! TestVC
        vc.croppedImage = cropped
        self.present(vc, animated: true)

    }
    
    func cropViewControllerDidCancel(_ cropViewController: Mantis.CropViewController, original: UIImage) {
        self.dismiss(animated: true)
    }
    func cropViewControllerDidFailToCrop(_ cropViewController: CropViewController, original: UIImage) {
        print("ERROR")
    }
    
    
}
```
![Simulator Screenshot - iPhone 15 Pro - 2024-03-25 at 22 49 19](https://github.com/guoyingtao/Mantis/assets/51410810/9fba0be9-baf6-4a3e-b018-bcfd0090e646)

**Comment by guoyingtao** [comment]
@SaiBalaji-PSS 
Would you mind posting the original screenshot you made from your pdf here so I can have a test？

**Comment by guoyingtao** [comment]
Can you put some break points at line 27/64/111 in `CGImageExtensions.swift` to see if it threw some error or went into default branch in `getBackupBitmapInfo`.

**Comment by SaiBalaji-PSS** [comment]
It went into (64,16) branch
<img width="1152" alt="Screenshot 2024-03-27 at 8 52 20 PM" src="https://github.com/guoyingtao/Mantis/assets/51410810/27d13a0e-be98-4fbf-bdb8-091a560dfca8">

**Comment by guoyingtao** [comment]
@SaiBalaji-PSS 
Can you also check if it throws any errors in the same file. You can search ‘throw’ in the same file to locate the code.
What’s your version of Mantis? Can you upgrade it to the latest version?

**Comment by guoyingtao** [comment]
@SaiBalaji-PSS 
Since I haven't heard from you for a while, I close this ticket for now. You can reopen it any time if needed.
