### ISSUE TITLE
Zooming out should zoom from Center

### ISSUE THREAD

**Issue by rickshane** [guoyingtao/Mantis#389]
Currently, zooming out seems to be anchored to the upper left origin. It should zoom out from center, before bouncing back to fit the cropBoxFrame. Video:

https://github.com/guoyingtao/Mantis/assets/5288729/e00492cf-67fa-4643-b8dd-e333033a48f8

**Comment by guoyingtao** [comment]
@rickshane 
PR #390 fixes this issue. Can you have a test?
Thank you!

**Comment by rickshane** [comment]
Fixed in PR #390. Closing.
