### ISSUE TITLE
BUG: CropRegion origin not true zero

### ISSUE THREAD

**Issue by rickshane** [guoyingtao/Mantis#391]
If I change the crop rect by dragging from lower right to center of image, the upper left origin for cropRegion should still be (0,0) but it is slightly incorrect.

Video provided:

https://github.com/guoyingtao/Mantis/assets/5288729/49e7bfba-2563-4983-ad0d-c5997723a46d

**Comment by rickshane** [comment]
If I use that in a large image, then the origin is off by multiple pixels during a crop operation.

**Comment by guoyingtao** [comment]
If you get a result of multiple pixel offset, can you post the large image size here, I will do more checks then. Thank you.

**Comment by rickshane** [comment]
I think I had a different bug that was causing my origin to be off. Sorry for the concert.

Closing this issue.
