### ISSUE TITLE
Redo of 90 degree rotation after a flip transforms in the opposite direction

### ISSUE THREAD

**Issue by rickshane** [guoyingtao/Mantis#393]
If I flip the image, then rotate it 90 degrees, then undo and redo, the image is displayed in a flipped manner. I think "flipOddTimes" is getting ignored somewhere in applyCropState() method:

https://github.com/guoyingtao/Mantis/assets/5288729/74c4e028-c430-4d2e-8eab-3789da9f2c43

**Comment by guoyingtao** [comment]
@rickshane 
I raised a PR #394 
Can you have a test with it to see if it fixed the issue?

**Comment by rickshane** [comment]
Thanks for fixing this issue.

**Comment by rickshane** [comment]
I just re-tested this with negative degree rotations and it fails. If I apply a flip before a negative degree adjustment and undo/redo, then the negative adjustment becomes positive:

**Comment by guoyingtao** [comment]
@rickshane 
I raised another PR #396 
Can you have a test with it to see if it fixed the issue?

**Comment by guoyingtao** [comment]
@rickshane 
I raised another PR #396 
Please have a test to see if it fixed the issue. Thank you!

**Comment by rickshane** [comment]
This fixes the issue.

Thanks
