### ISSUE TITLE
Scaling the image doesn't work sometimes

### ISSUE THREAD

**Issue by mschonvogel** [guoyingtao/Mantis#40]
It happened in some other cases as well, but I was able to reproduce it when setting the aspect ratio, adjusting the crop frame, and then change the ratio back to the original one. After that it won't let me "zoom-out" anymore.

![image-picker-cant-zoom-out](https://user-images.githubusercontent.com/370839/80918796-013acc80-8d67-11ea-9d7d-f64b1a46cbbc.gif)

**Comment by guoyingtao** [comment]
@mschonvogel Thanks for the reporting. I followed your steps and didn't reproduce the issue. Would you mind uploading the picture you were using for this test. So I can use the same picture to test it again. Thanks!

**Comment by mschonvogel** [comment]
Sure, those are the simulator default photos (Uploaded as a zip because otherwise, GitHub compresses the images):
[Archive.zip](https://github.com/guoyingtao/Mantis/files/4571289/Archive.zip)

**Comment by guoyingtao** [comment]
@mschonvogel I released Mantis 1.2.1. Hope it solved this issue. Also, I remove the default implementations of handleFixedRatioSetted() and handleFixedRatioUnSetted() for CropToolbarProtocol. When you select a fixed ratio, handleFixedRatioSetted() will be triggered, then you can make some UI change to show a user that the current ratio is fixed. When the user tap the button for setting ratio again, handleFixedRatioUnSetted() will be triggered, then the user can adjust the ratio freely.

**Comment by mschonvogel** [comment]
> Also, I remove the default implementations of handleFixedRatioSetted() and handleFixedRatioUnSetted() for CropToolbarProtocol. When you select a fixed ratio, handleFixedRatioSetted() will be triggered, then you can make some UI changes to show a user that the current ratio is fixed. When the user tap the button for setting ratio again, handleFixedRatioUnSetted() will be triggered, then the user can adjust the ratio freely.

That works quite well!

However, now sometimes, I can't zoom in at all anymore: 
![cannot-pinch-zoom](https://user-images.githubusercontent.com/370839/80949457-5a047680-8df4-11ea-95bb-e6770b4a79c7.gif)

Also, the gutter is moving once the image crop view is released:
![gutter-moving](https://user-images.githubusercontent.com/370839/80951202-b7e68d80-8df7-11ea-842a-de034ceb36f2.gif)

**Comment by guoyingtao** [comment]
@mschonvogel Thanks for the feedbacks! I release Mantis 1.2.2 which fixed the issues you mentioned.

**Comment by mschonvogel** [comment]
Thanks, seems to work! @guoyingtao 

But now I can't zoom fully out sometimes:
![cant-zoom-out](https://user-images.githubusercontent.com/370839/81002568-bba30000-8e49-11ea-88b8-8eac9f0df7fe.gif)

**Comment by guoyingtao** [comment]
@mschonvogel Thanks for the feedback! I tried to fix this issue but caused other problems. I need some time to figure out a right way to fix it.

**Comment by mschonvogel** [comment]
@guoyingtao almost 😀 I'm still able to reproduce this issue with v1.2.3:
![cannot-zoom-out](https://user-images.githubusercontent.com/370839/81048033-d9a94880-8ebb-11ea-8bdb-c58d4743db4a.gif)

**Comment by guoyingtao** [comment]
I will keep working on it later. 😂

**Comment by guoyingtao** [comment]
@mschonvogel I released Mantis 1.3.0. Hope it solved the zoom issue.

**Comment by mschonvogel** [comment]
Updated to 1.3.0 but there's still a zoom issue:

![zoom-out-not-possible](https://user-images.githubusercontent.com/370839/81187440-57e91600-8fb4-11ea-955d-ffe507fefbc9.gif)

**Comment by guoyingtao** [comment]
@mschonvogel I did find this issue and fixed it before I released 1.3.0.
Can you help to check if you can find **self.scrollView.updateMinZoomScale()** in counterclockwiseRotate90() in CropView.swift?

**Comment by mschonvogel** [comment]
![image](https://user-images.githubusercontent.com/370839/81191161-0000de00-8fb9-11ea-89a0-43ce3b74b14a.png)

Yes, I also did a hard clean before running the app @guoyingtao

**Comment by guoyingtao** [comment]
I did the similar test and it seems OK
https://www.youtube.com/watch?v=WrOHDB7WymI&feature=youtu.be

Can you check if the Example project work for this issue?

**Comment by mschonvogel** [comment]
![cant-zoom-out](https://user-images.githubusercontent.com/370839/81212305-fdac7d00-8fd4-11ea-9afd-1cd827669393.gif)

I was also able to reproduce it in the latest example project

**Comment by guoyingtao** [comment]
@mschonvogel Can you give me more details about your test device or simulator type information? Thank you!  I couldn't reproduce this issue on my phone and my simulators. 
Can you also try to delete the App and reinstall it?

**Comment by guoyingtao** [comment]
@mschonvogel I released Mantis 1.3.1. Can you try it to see if it solves this issue? Thanks!

**Comment by mschonvogel** [comment]
Yes, fixed it! Thanks again! 🙂
