### ISSUE TITLE
About the color of the cropping border line

### ISSUE THREAD

**Issue by ByLiangCheng** [guoyingtao/Mantis#401]
I configured the color in config.cropViewConfig.cropBorderColor, but it seems to have no effect after setting it. I wonder if it is supported?

Because my config.cropViewConfig.backgroundColor is set to white, in this case, the crop line and the background color will be the same, making it impossible to see whether it exists, but in fact I need it to be displayed prominently.

I would appreciate any help in resolving this issue.

**Comment by ByLiangCheng** [comment]
Sample video :

https://github.com/user-attachments/assets/833097e3-7794-453f-9fd4-633a3f08b70f

**Comment by guoyingtao** [comment]
@ByLiangCheng 
config.cropViewConfig.cropBorderColor is for the border of cropped image like below, it is not for the cropping box whose border is always white currently.

<img width="298" alt="image" src="https://github.com/user-attachments/assets/8829a071-38eb-414c-bb13-2cef77201b4b">

**Comment by ByLiangCheng** [comment]
Will you consider supporting the configuration of a cropping frame that is always white in the future? Because when my background is white, the cropping frame is always white, which makes it invisible.

**Comment by guoyingtao** [comment]
@ByLiangCheng 
Yes, I will consider supporting this configuration in the next release.

**Comment by ByLiangCheng** [comment]
Thanks, looking forward to the update

**Comment by mihapp** [comment]
I'm also looking forward for this update, I have similar issue with white background...

**Comment by guoyingtao** [comment]
@ByLiangCheng @mihapp 
Can you try PR #403 to see if it meets your requirement?

You may need to modify color properties of CropViewConfig.cropAuxiliaryIndicatorConfig

**Comment by ByLiangCheng** [comment]
> @ByLiangCheng @mihapp Can you try PR #403 to see if it meets your requirement?
> 
> You may need to modify color properties of CropViewConfig.cropAuxiliaryIndicatorConfig

Thank you for your support, I successfully solved it with this configuration

**Comment by guoyingtao** [comment]
@ByLiangCheng
I released Mantis 2.22.0 which includes PR #403
