### ISSUE TITLE
CropView have cropProps pass 

### ISSUE THREAD

**Issue by rahul6350** [guoyingtao/Mantis#407]
Hi @YingtaoGuo , [
![Simulator Screenshot - iPhone 15 Pro - 2024-07-23 at 12 33 54](https://github.com/user-attachments/assets/50f0bffc-d20d-4b48-820b-b479336f8293)
](url)
![Simulator Screenshot - iPhone 15 Pro - 2024-07-17 at 23 42 36](https://github.com/user-attachments/assets/194453ba-c73a-45c5-953f-67be31ce6392)

My issue is that suppose in the  print preview page of the two image other than cropview page second page, firstly we need to Edit  and crop the view with certain rotation or without rotation ,and save it the.api call and we send the rotation_degree and cropprops(which is topx., topy, bottomx, bottomy) the backend cropthe image and we preview it the second preview page means backend send the cropped image url. then we select suppose intial is square then we change it to Album then backend always send the cropprops which they changes from square to album or any print size change we need to use this croprops when edit the view to the cropview, we need use this cropprops to see the cropview so we and backend in the same flow. But currently i have on crop saved the transformation then edit then present the transformation as we discussed earlier using cropviewpresent type function can make a struct which contain cropprops and rotation degree every time we update they backend send this but we need to use this struct cropprops(topx, topy , bottomx, bottomy), and rotationdegree when edit to see the view     func cropProps(_ info: CropInfo) -> CropProps {
        return CropProps(topX: Int(info.cropRegion.topLeft.x * info.originalPixels.width),
                         topY: Int(info.cropRegion.topLeft.y * info.originalPixels.height),
                         bottomX: Int(info.cropRegion.bottomRight.x * info.originalPixels.width),
                         bottomY: Int(info.cropRegion.bottomRight.y * info.originalPixels.height))
    } this is for cropprops please provide PR to get this , can you do today this is on urgent basis how can we use that

**Comment by guoyingtao** [comment]
@rahul6350 
It is really hard for me to understand your real purpose. Can you format your post to make it easier to read?
Also what is cropviewpresent type? Mantis doesn't use this type currently.

**Comment by rahul6350** [comment]
In the print preview process, we handle images across multiple pages, specifically focusing on the interaction between the crop view and the preview page. Initially, when a user edits and crops an image, they can apply a certain rotation or no rotation at all. Once the image is edited, we save these details and make an API call, sending the rotation degree along with cropping properties (cropProps), which include coordinates: topX, topY, bottomX, and bottomY. The backend uses these details to crop the image and sends back a URL for the cropped image, which we display on the second preview page.

If the user changes the print format from an initial square to another format, such as an album, the backend recalculates and returns updated cropProps reflecting these changes. We must use these updated cropProps to maintain synchronization between the backend and our front-end view, ensuring the crop view is consistent with the backend's processing.

Currently, when a crop is saved, the transformation is retained for future edits. Using the cropViewPresent function, we maintain a struct that contains both cropProps and the rotation degree. This struct is updated whenever the backend sends new data. By employing this struct, we can effectively utilize the cropProps (topX, topY, bottomX, bottomY) and rotation degree to render the crop view accurately during editing. Below is a function that converts a CropInfo instance to CropProps:

func cropProps(_ info: CropInfo) -> CropProps {
    return CropProps(
        topX: Int(info.cropRegion.topLeft.x * info.originalPixels.width),
        topY: Int(info.cropRegion.topLeft.y * info.originalPixels.height),
        bottomX: Int(info.cropRegion.bottomRight.x * info.originalPixels.width),
        bottomY: Int(info.cropRegion.bottomRight.y * info.originalPixels.height),
        rotationDegree: info.rotationDegree // Assuming rotationDegree is a property of CropInfo
    )
}cropviewpresenttype means in example project there is function presentcropview in which we present on the basis of transformation

**Comment by rahul6350** [comment]
Hi @guoyingtao in simple words When we crop the image we have saved the Transformation on edit we use this saved Transformation then crop region is shown as in presentWithPresetTransformation this function. But the thing is that suppose  func cropProps(_ info: CropInfo) -> CropProps {
        return CropProps(topX: Int(info.cropRegion.topLeft.x * info.originalPixels.width),
                         topY: Int(info.cropRegion.topLeft.y * info.originalPixels.height),
                         bottomX: Int(info.cropRegion.bottomRight.x * info.originalPixels.width),
                         bottomY: Int(info.cropRegion.bottomRight.y * info.originalPixels.height))
    }  when we crop the image and on the basis of cropping we sent the cropProps which is topx topy bottomx bottomy to backend and backend crop the image on the basis of it suppose we use this cropProps to the cropArea instead of transformation  saving can we do that for so on edit exact cropprops set to image and inside the cropbox crop region contain with complete image so basically instead of transformation struct we have topx topy bottomx bottomy cropprops then can we do that as we are doing transformation does please add and reply as soon as possible

**Comment by guoyingtao** [comment]
@rahul6350 
If the image is rotated, are topX, topY based on the original image or the rotated image?

**Comment by rahul6350** [comment]
on the basis of rotation because we send the rotation degree to the backend then backend rotate on the basis and send topx topy bottomx bottom y please do it i need it in urgent basis i did not understand in mantis how can i do that i basically only use transformation saving way  presentWithPresetTransformation in this function which has but now same behaviour want topx topy bottomx bottom y on tha basis

**Comment by rahul6350** [comment]
means rotated image

**Comment by guoyingtao** [comment]
For rotation, it looks like your app only uses angles like 90, 180, 270 etc. Is my understanding correct?

**Comment by guoyingtao** [comment]
@rahul6350 
If no any rotation, you can use PresetTransformationType.presetNormalizedInfo(You may need to build normalized data based on the cropProps (topX, topY, bottomX, bottomY)
If any rotation happened, we have more work to do which may need to add a new type of PresetTransformationType.

**Comment by guoyingtao** [comment]
@rahul6350 
Please try PR #408 to see if it works for you.
You can set Config.cropViewConfig.presetTransformationType = .presetNormalizedInfo when you want to edit the image again after receiving cropProps and rotation data from your backend.
Also you need to build normalized crop info based on the cropProps (topX, topY, bottomX, bottomY) and set ImageRotationType based on your actual rotation.
For example, if the image size is 100 * 200(after rotation) and cropProps is (10, 40, 90, 160), then the normalized crop info should be CGRect(x: 0.1, y: 0.2, width: 0.8, height: 0.6)

**Comment by rahul6350** [comment]
how can we convert suppose topx topy bottomx bottom y to normalize info which is CGRect please if no rotation then how can we do that please tell step by step

**Comment by rahul6350** [comment]
backend send the cropprops how can we convert to CGrect for normalize info

**Comment by rahul6350** [comment]
need to paas CGRECT in presentNormalizeinfo so suppose TOPX topy bottomx bottom y is from backedn then how can convert cgrect and what is cgrect in this so we can paas

**Comment by guoyingtao** [comment]
@rahul6350 
Just did some tests for PR #408 and found some issues. Still need some time to solve them.

**Comment by rahul6350** [comment]
but can you need to paas CGRECT in presentNormalizeinfo so suppose TOPX topy bottomx bottom y is from backedn then how can convert cgrect and what is cgrect in this so we can paas explain

**Comment by rahul6350** [comment]
please explain once resolve the issues

**Comment by guoyingtao** [comment]
@rahul6350 
The normalized data can be built like below
1. create a CGRect based on cropProps (topX, topY, bottomX, bottomY)
2. divide origin.x and width in CGRect by image.width and divide origin.y and height in CGRect by image.height to make sure every value in CGRect is [0, 1]

**Comment by guoyingtao** [comment]
I updated PR #408 and solved issues I found.
You can have a try to see if it works for you.

**Comment by rahul6350** [comment]
func normalizeCropInfo(cropProps: CropProps, imageSize: CGSize) -> CGRect {
    // Calculate the origin and size of the crop rectangle
    let originX = cropProps.topX / imageSize.width
    let originY = cropProps.topY / imageSize.height
    let width = (cropProps.bottomX - cropProps.topX) / imageSize.width
    let height = (cropProps.bottomY - cropProps.topY) / imageSize.height

    // Create and return a normalized CGRect
    return CGRect(x: originX, y: originY, width: width, height: height)
} is this correct

**Comment by rahul6350** [comment]
not working

**Comment by rahul6350** [comment]
no transormation on edit occur of the image

**Comment by rahul6350** [comment]
if let printId = printId,  let transform = cropFrameManager.savedTransFormation[printId], let cropProps = cropConfig.cropProps {
            let createrect = normalizeCropInfo(cropProps: cropProps, imageSize: image.size)
            
            config.cropViewConfig.presetTransformationType = .presetNormalizedInfo(normalizedInfo: createrect ?? .zero)
        }    func normalizeCropInfo(cropProps: CropProps, imageSize: CGSize) -> CGRect {
        // Calculate the origin and size of the crop rectangle
        let originX = CGFloat(cropProps.topX ?? .zero) / imageSize.width
        let originY = CGFloat(cropProps.topY ?? .zero) / imageSize.height
        let width = CGFloat(cropProps.bottomX ?? .zero) - CGFloat(cropProps.topX ?? .zero)  / imageSize.width
        let height = (CGFloat(cropProps.bottomY ?? .zero) - CGFloat(cropProps.topY ?? .zero) ) / imageSize.height

        // Create and return a normalized CGRect
        return CGRect(x: originX, y: originY, width: width, height: height)
    }in this way we create but it is wrong previously when present info paas and use that saved tranformation it works but in this when use cgrect on the basis of cropprops not work can you pleasee explain how can i do that where iam wrong?

**Comment by rahul6350** [comment]
Hey @guoyingtao rotation not working in this flow without rotation working fine but in rotation suppose i rotate one time in clockwise direction so roationType is counterclockwise270 but after transform and paasing this roationtype in edit it will rotate to 180 same when 180 rotation it will roate to .none angle is not correct

**Comment by guoyingtao** [comment]
@rahul6350 
I tested by using Example project and it worked fine. I can't tell the why it doesn't work for your case but looks like it calculated with the saved transformation and presetNormalizedInfo.
Also can you format your posts to make it easier to read?

**Comment by rahul6350** [comment]
Can you provide the code where you tested because cropprops passing is fine but scale zooming i say this the issue because we do not adjust scale in this i think that why

**Comment by guoyingtao** [comment]
Below is the video for counterclockwise270
```Swift
 config.cropViewConfig.presetTransformationType = .presetNormalizedInfo(normalizedInfo: CGRect(x: 0.1, y: 0.2, width: 0.8, height: 0.7), imageRotationType: .counterclockwise270)
```

https://github.com/user-attachments/assets/46a1e336-acfb-45de-9f46-a50346e7edd7

**Comment by guoyingtao** [comment]
@rahul6350 
You can modify function presentWithPresetTransformation in ViewController in Example project and use some code like below (You need to comment out ` config.cropViewConfig.presetTransformationType = .presetInfo(info: transform)`)
```Swift
config.cropViewConfig.presetTransformationType = .presetNormalizedInfo(normalizedInfo: CGRect(x: 0.1, y: 0.2, width: 0.8, height: 0.7), imageRotationType: .counterclockwise270)
```

**Comment by rahul6350** [comment]
Can you zoom to the crop area then edit then on edit zooming not to that level i cant share the video video is too loarge not sharable error that why

**Comment by rahul6350** [comment]
![IMG_0794](https://github.com/user-attachments/assets/5b1d5de9-2be7-4666-a316-494860102920)
![IMG_0795](https://github.com/user-attachments/assets/ea9347f5-d4ca-4648-ac93-02e66e998288)
![IMG_0792](https://github.com/user-attachments/assets/25134fac-ad91-4579-bd3a-2abd43a5d805)
![IMG_0793](https://github.com/user-attachments/assets/cf8e840c-8920-4070-bf7c-766be15ca92b)
can you check these 4 screen shots on preview page have cropped image from backend when crop and rotate and when backend send the cropprops and rotationtype then on edit these are the two image usign presentnormalizeinfo huge diffrenece in without rotation it is not zooming to that instant due to which extra  things space inside the box is  show and roation is 270 but on edit rotation is 180 type i dont know

**Comment by rahul6350** [comment]
please available need to close help me out

**Comment by guoyingtao** [comment]
I don't quite understand the cropping logic of your backend server.
In Mantis, after rotating the image, the image scale will change to adapt the editing view but the cropping region is kept the same.

https://github.com/user-attachments/assets/dc6d86f5-0594-400d-891d-a890170183a6

**Comment by rahul6350** [comment]
No backend serve the cropping logic of google photos but on presentransform it will scale or zoom to that level , because when cropping i save the whole tranofrmation strut in cropout and on edit it use it will correctly zoom to that level but in this it is not i dont know why and roation is also work fine in presentinfo tranformation logic please check zoom or scaling

**Comment by guoyingtao** [comment]
If you only want to restore the image editing status based on the data returned from the backend server or Google photos, you don't need to save the whole transformation which is for rotating any angles. I see in your case, you only rotate degrees like 90, 180, 270 etc, right?

**Comment by rahul6350** [comment]
I think can you do the scaling or zooming are you understand what iam tried to say can you look at two image in preview and edit page withour roattion extra margins or things in edit not scale to that extent

**Comment by guoyingtao** [comment]
You mentioned if no rotation, it works fine. Is the scale also correct if no rotation?

**Comment by rahul6350** [comment]
> If you only want to restore the image editing status based on the data returned from the backend server or Google photos, you don't need to save the whole transformation which is for rotating any angles. I see in your case, you only rotate degrees like 90, 180, 270 etc, right?

yes but when backend not serve the cropprops and rotationdegree when we cropping we saved the whole transformation and use that tranformation in presentInfo and pass the save tranformation it work fine zooming scaling but in this when backend serve cropprops in presentnormalizeinfo when paas cgrect scaling or zooming not working can you skip the rotation part currently zooming and scaling  to that instant. not work in without rotation firstly

**Comment by rahul6350** [comment]
> You mentioned if no rotation, it works fine. Is the scale also correct if no rotation?

the main problem scale is not correct my main point is this in rotation as well in without rotation scale is not correct before in present info when saved transformaiton it is correct in presentnormalizeinfo it is not correct

**Comment by rahul6350** [comment]
cropprops is correct to that tranform but scale is not

**Comment by rahul6350** [comment]
please explain how can we solve this

**Comment by guoyingtao** [comment]
Hi @rahul6350 
Can you use some tool like ChatGPT to format your post, it is a little hard for me to follow you since no punctuations in your post.

**Comment by rahul6350** [comment]
When the backend does not provide cropProps and rotationDegree, we save the entire transformation during cropping and use that transformation in presentInfo. Passing the saved transformation works fine for zooming and scaling.

However, when the backend provides cropProps, we use presentNormalizedInfo, and when passing a CGRect, the scaling or zooming does not work properly.

Can you skip the rotation part, currently focusing on zooming and scaling? Without rotation, the zooming and scaling should work instantly.

**Comment by rahul6350** [comment]
Scale is not correctly work in without rotation are you understand ?

**Comment by rahul6350** [comment]
pls explain

**Comment by guoyingtao** [comment]
Is the cropping region correct if the scale is not correct?

**Comment by rahul6350** [comment]
yes cropping region is correct

**Comment by rahul6350** [comment]
is this solved?

**Comment by guoyingtao** [comment]
Can you post two images (They have the same cropping region) and one is with correct scale (calculated with saved transformation data), the other one with wrong scale(calculated with presentNormalizedInfo)? It can help me understand the issue better. Thanks.

**Comment by rahul6350** [comment]
sure

**Comment by guoyingtao** [comment]
Also if you don't zoom manually and only crop the image, is the scale correct when using presentNormalizedInfo?

**Comment by rahul6350** [comment]
yes when zoom manually then incorrect otherwise correct

**Comment by rahul6350** [comment]
when i think scale issue
?

**Comment by rahul6350** [comment]
![IMG_0796](https://github.com/user-attachments/assets/5893b06b-9a51-48c7-85df-92eac8ced3b1)
![IMG_0797](https://github.com/user-attachments/assets/7be67320-26cc-465c-95b4-e2c4ad951ec2)
1st image is presentInfo tranformation and 2nd is presentinfonormalize

**Comment by rahul6350** [comment]
pls explain

**Comment by rahul6350** [comment]
can we use google meet to solve the issue?

**Comment by guoyingtao** [comment]
> can we use google meet to solve the issue?

Sorry, I still have other work to do. I can not use Google meet

**Comment by rahul6350** [comment]
> > can we use google meet to solve the issue?
> 
> Sorry, I still have other work to do. I can not use Google meet

ok but please solve it its very urgent for me

**Comment by guoyingtao** [comment]
I hope you understand it takes time to figure out the reason of the issue. Especially I don't know the detail of your project. 
Please be patient.

**Comment by guoyingtao** [comment]
I also have other work to do. I can't assure I have enough time to work on it according to your pace.

**Comment by rahul6350** [comment]
Will you get the issue these two images show the difference same crop region 1st give correct 2nd not give correct will you get it ?

**Comment by rahul6350** [comment]
> I also have other work to do. I can't assure I have enough time to work on it according to your pace.

will try please if you take time its ok but i tried not able to figure out

**Comment by rahul6350** [comment]
can we use presentinfo scale  in this presentinfonormalize

**Comment by guoyingtao** [comment]
No matter you manually zoom or not, as long as the normalized info is calculated correctly, the scale is always the same. So no need to use scale for presetNormalizedInfo type because it is automatically calculated based on the  normalized info. 
If the scale is not correct, it could be the normalized info is not correct.

**Comment by rahul6350** [comment]
means according to you CGRect is not correct

**Comment by rahul6350** [comment]
func normalizeCropInfo(cropProps: CropProps, imageSize: CGSize) -> CGRect {
    // Calculate the origin and size of the crop rectangle
    let originX = CGFloat(cropProps.topX ?? .zero) / imageSize.width
    let originY = CGFloat(cropProps.topY ?? .zero) / imageSize.height
    let width = CGFloat(cropProps.bottomX ?? .zero) - CGFloat(cropProps.topX ?? .zero)  / imageSize.width
    let height = (CGFloat(cropProps.bottomY ?? .zero) - CGFloat(cropProps.topY ?? .zero) ) / imageSize.height

    // Create and return a normalized CGRect
    return CGRect(x: originX, y: originY, width: width, height: height)
} is this correct method to calculate cgRECT  on the basis of cropprops and always pass the image.size original image size

**Comment by guoyingtao** [comment]
Looks correct.
If you do a test in presentWithPresetTransformation function with `normalizedInfo: CGRect(x: 0.0, y: 0.0, width: 1.0, height: 1.0)`, you will get the whole image.

**Comment by rahul6350** [comment]
so if normalize info is correct then whats the issue

**Comment by guoyingtao** [comment]
If you do nothing, just crop the whole image, what data will return from the backend?

**Comment by guoyingtao** [comment]
Let us say you are using Square 4*4 inches, just crop the image with the default crop box without changing the crop region, what data will return from the backend? 
Can you post your test image size and the returned data?

**Comment by rahul6350** [comment]
sure

**Comment by rahul6350** [comment]
for square cgrect without cropping have default x = 0.4 y = 0.5 width = 1.1

**Comment by guoyingtao** [comment]
For a vertical image like below, using the square crop box and the default crop region will get x = 0 and width = 1
I am not sure why your backend returned the normalized x = 0.4 and the normalized width is greater than 1

<img width="369" alt="image" src="https://github.com/user-attachments/assets/3ca6ecd3-4fa3-4f7a-928f-f109be2882cd">

**Comment by rahul6350** [comment]
(0.0, 0.0, 1.0, 1.0) create rect is this for square default

**Comment by rahul6350** [comment]
yes x is o width is 1 it is correct for backend

**Comment by rahul6350** [comment]
Hey i check the values of presentInfo and presentNormalizeINfo found one thing is that in offset and scale both are diffrent when cropping i don't know why

**Comment by rahul6350** [comment]
Hey @guoyingtao public func getTransformInfo(byNormalizedInfo normalizedInfo: CGRect, imageRotationType: ImageRotationType) -> Transformation  in this function you have made a switch statement on the basis of imageRotationType and write offset and rotation radius , but when rotate suppose one time clockwise it will show like we rotate 2 time one clockwise rotation imagerotation type is counterclockwise270 but it show 180 type if we remove roation radius then on the .none case offset work fine but other case it is not i dont know the reason pls make us such that it rotate perfectly

**Comment by guoyingtao** [comment]
@rahul6350 
You can use presentWithPresetTransformation function in Example project to have a test. For example, you can use 
```Swift
 config.cropViewConfig.presetTransformationType = .presetNormalizedInfo(normalizedInfo: CGRect(x: 0.1, y: 0.2, width: 0.5, height: 0.5), imageRotationType: .counterclockwise270)
```

I did some tests and the rotation results were correct.

**Comment by guoyingtao** [comment]
The screenshot below shows the result using `config.cropViewConfig.presetTransformationType = .presetNormalizedInfo(normalizedInfo: CGRect(x: 0.1, y: 0.2, width: 0.5, height: 0.5), imageRotationType: .counterclockwise270)`
<img width="381" alt="image" src="https://github.com/user-attachments/assets/7aefee40-86e2-43d8-956f-4e7ac4e49e52">

**Comment by rahul6350** [comment]
suppose when we rotate and save have we send the rotated image or saved image if we send the rotated image it is incorrect and when we send the original image it is correct rotation but offset slightllt wrong not correctly as we seen but when crop again it break

**Comment by guoyingtao** [comment]
presetTransformationType is always for the original image

**Comment by rahul6350** [comment]
But i have use when rotated in presentInfo rotated imag and crop the rotated image works fine , but in the cropprops case when we send the original image instead of rotated Image and function show the rotation in transform it is correct but when crop the rotated image in this case it is wrong because backend give in response is Wrong dimensions

**Comment by guoyingtao** [comment]
> But i have use when rotated in presentInfo rotated imag and crop the rotated image works fine , but in the cropprops case when we send the original image instead of rotated Image and function show the rotation in transform it is correct but when crop the rotated image in this case it is wrong because backend give in response is Wrong dimensions

I don't quite understand it. What do you mean wrong dimensions? Again, Is the response data from backend based on the original image or the rotated one?

**Comment by guoyingtao** [comment]
There has been no reply to this ticket for a while, so I am closing it for now. You can reopen it anytime if needed.

**Comment by guoyingtao** [comment]
There has been no reply to this ticket for a while, so I am closing it for now. You can reopen it anytime if needed.
