### ISSUE TITLE
Cropped image return on the basis of cropProps

### ISSUE THREAD

**Issue by rahul6350** [guoyingtao/Mantis#409]
We have a original image and have cropprops which have topx topY bottomY bottomX how can we crop the image and get cropImage on the basis of topx topy bottomx bottomy 
   func cropProps(_ info: CropInfo) -> CropProps {
        return CropProps(topX: Int(info.cropRegion.topLeft.x * info.originalPixels.width),
                         topY: Int(info.cropRegion.topLeft.y * info.originalPixels.height),
                         bottomX: Int(info.cropRegion.bottomRight.x * info.originalPixels.width),
                         bottomY: Int(info.cropRegion.bottomRight.y * info.originalPixels.height))
    } can you provide in this library crop function cropped the image on the basis of cropInfo but can you get a function which takes cropProps as input and return cropImage on the basis of cropprops which is how can we do that please  @guoyingtao

**Comment by guoyingtao** [comment]
@rahul6350 
Mantis is an iOS Image cropping library, which mimics the Photo App. Users can crop images by the interactions with CropViewController. Perhaps you can find a dedicated image processing library that includes the cropping features you need.

**Comment by guoyingtao** [comment]
There has been no reply to this ticket for a while, so I am closing it for now. You can reopen it anytime if needed.
