### ISSUE TITLE
Transformation properties are internal and not accessible

### ISSUE THREAD

**Issue by nickjbedford** [guoyingtao/Mantis#410]
I need to store the Transformation object in my own app to then restore the state of the crop view transformation when editing a crop. I no longer can access the properties in Transformation despite the constructor and class being public.

```swift
public struct Transformation: Equatable {
    var offset: CGPoint
    var rotation: CGFloat
    var scale: CGFloat
    var isManuallyZoomed: Bool
    var initialMaskFrame: CGRect
    var maskFrame: CGRect
    var cropWorkbenchViewBounds: CGRect
    var horizontallyFlipped: Bool
    var verticallyFlipped: Bool
}
```

**Comment by guoyingtao** [comment]
@nickjbedford 
Are you using CocoaPods or Swift Package Manager? The Example project uses CocoaPods, and it's no problem to access Transformation. If you're using Swift Package Manager, can you check which version of Mantis you're using?

**Comment by guoyingtao** [comment]
@nickjbedford 
Since there hasn't been any activity on this issue for a while, I'll close it for now. Feel free to reopen it if needed.
