### ISSUE TITLE
Enhancement Request: Zooming an Image in Mac Catalyst

### ISSUE THREAD

**Issue by zewkini** [guoyingtao/Mantis#415]
Don't see a way to zoom an image in Mac Catalyst similar to how it can be done in iOS (like the pinch gesture).

I'm referrring to just using something like keyboard presses (like cmd-+).

**Comment by guoyingtao** [comment]
@zewkini 
Please check if PR #416 works for you?

**Comment by guoyingtao** [comment]
@zewkini 
I just released Mantis 2.2.30 which supports this feature.

**Comment by zewkini** [comment]
Excellent work. I really appreciate your quick response and dedication to adding this request!
