### ISSUE TITLE
Cropper not working in iPhone X

### ISSUE THREAD

**Issue by ganpat05** [guoyingtao/Mantis#419]
I have integrated Mantis in my app and it is working fine in simulator.
But when I choose a photo from library which is the screenshot the cropper not working.
Device - iPhone X
OS Version - 16.7.8

**Comment by guoyingtao** [comment]
@ganpat05 
Can you post the screenshot you mentioned here so I can take a look later? Thank you!

**Comment by guoyingtao** [comment]
@ganpat05 
What version of Mantis are you using?
Can you update to the latest version and test it again? Thanks!

**Comment by guoyingtao** [comment]
@ganpat05 
Can you check if the PR #423 solves the issue?

**Comment by guoyingtao** [comment]
@ganpat05 
Mantis 2.23.1 has been released. Please verify if it resolves the crash issue.

**Comment by guoyingtao** [comment]
@ganpat05 
Since I haven't heard from you for a while, I have closed this issue for now. You can reopen it anytime.
