### ISSUE TITLE
App crashes because of a CGContext issue.

### ISSUE THREAD

**Issue by JayAt2024** [guoyingtao/Mantis#421]
I was using v2.23.0 and it occurred that the project crashed sometimes.  By looking into the code of Mantis, I found  the crashes happened because of this piece of code in the file of CGImageExtensions.swift, line 47~55:
```swift
let context = CGContext(data: nil,
                                width: Int(round(outputSize.width)),
                                height: Int(round(outputSize.height)),
                                bitsPerComponent: bitsPerComponent,
                                bytesPerRow: bitmapBytesPerRow,
                                space: colorSpaceRef,
                                bitmapInfo: bitmapInfoData)
        ??
        createBackupCGContext(size: outputSize, bitmapBytesPerRow: bitsPerComponent, colorSpaceRef: colorSpaceRef)
```
        
The context was nil when the app crashed. I suppose the bitmapBytesPerRow param of the createBackupCGContext function is not expecting `bitsPerComponent` but something like `bitsPerComponent * Int(size.width) * 4 / 8`? 
By the way, the images I used is just common snapshots, with bitsPerComponent = 16 and bitsPerPixel = 48.

**Comment by guoyingtao** [comment]
@JayAt2024 
Would you mind posting on snapshot which caused crash here? Thank you!

**Comment by guoyingtao** [comment]
@JayAt2024 
Mantis 2.23.1 has been released. Please verify if it resolves the crash issue.

**Comment by guoyingtao** [comment]
@JayAt2024 
Since I haven't heard from you for a while, I have closed this issue for now. You can reopen it anytime.
