### ISSUE TITLE
Screenshot cropping crashes the app

### ISSUE THREAD

**Issue by rootko** [guoyingtao/Mantis#422]
Hi, I'm using Mantis 2.23.0, iPhone 13 mini on iOS 17.2.1 and I have a special screenshot that somehow crashes the app when I press Done (no matter if I crop or not). I've debug the code and the culprit is in CropView:1165 in the function 
`func crop(_ image: UIImage) -> CropOutput`
Namely calling this function `image.crop(by: cropInfo)` returns nil, with the following error message:
```
CGBitmapContextCreate: unsupported parameter combination:
	RGB | 16 bits/component, integer | 6752 bytes/row.
	kCGImageAlphaNone | kCGImageByteOrder16Little | kCGImagePixelFormatPacked
Set CGBITMAP_CONTEXT_LOG_ERRORS environmental variable to see more details.
CGBitmapContextCreate: invalid data bytes/row: should be at least 9000 for 16 integer bits/component, 3 components, kCGImageAlphaNoneSkipLast.
*** Failed to get transfromed image ***
Failed reason: failedToBuildContext(colorSpaceModel: __C.CGColorSpaceModel, bitsPerPixel: 48, bitsPerComponent: 16)
```

I'm attaching the screenshot that is not working for me. Other screenshots don't show this behaviour, so it's probably not a top priority. Probably just some extreme case of unexpected screenshot parameters...

Thanks for having a look, your library is a life saver ;)

![IMG_7628](https://github.com/user-attachments/assets/68e8321d-c4d0-4ee0-a5c9-a115dab38278)

**Comment by guoyingtao** [comment]
@rootko 
Thanks for providing the screenshot. Please check if the PR #423 solves the issue?

**Comment by rootko** [comment]
Hi, yes, this fixes the crash and I'm able to crop this screenshot as well as others from my iPhone 13 mini that were crashing before. Thanks for the quick reply and fix.
