### ISSUE TITLE
there are three different styles of image cropindicator view when tap on album it frame adjust to that s

### ISSUE THREAD

**Issue by rahul6350** [guoyingtao/Mantis#426]
there are three different styles of image cropindicator view when tap on album it frame adjust to that size suppose fram is on album it has croppoints topx topy bottomx bottomy or we get the cropregion when move to large then we get the cropregion can we get the cropregion of all sizes large square when on album region because frame we know how can i do that it is breaking on that image which has width hight as compared to height

**Comment by guoyingtao** [comment]
Thank you for your input! I’m having a bit of trouble fully understanding the description. Could you please clarify by reorganizing the explanation or adding some visual examples, like screenshots or diagrams? This would help me better understand the issue and assist you more effectively.

**Comment by guoyingtao** [comment]
Since there is no response for this ticket for a while, I just closed it for now. You can reopen it anytime if needed.

**Comment by guoyingtao** [comment]
Since there is no response for this ticket for a while, I just closed it for now. You can reopen it anytime if needed.
