### ISSUE TITLE
Add support for custom CropShapeType

### ISSUE THREAD

**Issue by lucagiorgettispotsoftware** [guoyingtao/Mantis#45]
Can you add support for custom CropShapeType using UIBezierPath (cgPath: CGPath)?
Or can you help me to achieve this result?
I'm trying to achieve this result in a fork, but the custom shape doesn't render properly

I have added this case
`case custom(path: CGPath)` in CropShapeType
and in the `func createOverLayer(opacity: Float) -> CAShapeLayer` in `CropMaskProtocol` I have added the case to manage innerPath
`innerPath = UIBezierPath(cgPath: customPath)`
Where am I wrong?

**Comment by guoyingtao** [comment]
@lucagiorgettispotsoftware CropMaskProtocol is for the overlay mask. You may also need to add some code to `func crop(_ image: UIImage) -> (croppedImage: UIImage?, transformation: Transformation)` in CropView.swift and extension section of UIImageExtensions.swift

**Comment by lucagiorgettispotsoftware** [comment]
Thanks for the reply. For now I'm focusing on the mask. My problem now is to correctly calculate the dimensions of the various layers (mask, dimming etc).
Will there be support for custom CropShapeTypes in the next releases?

**Comment by guoyingtao** [comment]
@lucagiorgettispotsoftware I don't have a plan for custom CropShapeTypes yet. But if you can help to implement that feature, would you mind submitting a PR for that? Thanks!

**Comment by guoyingtao** [comment]
@lucagiorgettispotsoftware Mantis 1.7.1 added support for custom CropShapeType.
