### ISSUE TITLE
SwiftUi compatibility?

### ISSUE THREAD

**Issue by Brakkar** [guoyingtao/Mantis#46]
Hello,
pardon my ignorance, but can this library work on a SwiftUi project?
Does it require any kind of adaptation for SwiftUi?

**Comment by guoyingtao** [comment]
@Brakkar I think this [link](https://developer.apple.com/tutorials/swiftui/interfacing-with-uikit) may be helpful. 

> To represent UIKit views and view controllers in SwiftUI, you create types that conform to the UIViewRepresentable and UIViewControllerRepresentable protocols. Your custom types create and configure the UIKit types that they represent, while SwiftUI manages their life cycle and updates them when needed.

I haven't tried it yet. If it works please let me know. Thank you!
