### ISSUE TITLE
Mirror Mode

### ISSUE THREAD

**Issue by MichaelDiMeo** [guoyingtao/Mantis#47]
Mirror Mode misses!

**Comment by guoyingtao** [comment]
@MichaelDiMeo Do you mean Flip Horizontally / Vertically when you say Mirror Mode?

**Comment by MichaelDiMeo** [comment]
@guoyingtao Yes! I've tried to implement by myself but I had a lot of problems with your code. For example I can't add outlet to the view.

**Comment by MichaelDiMeo** [comment]
@guoyingtao Anyway, congrats for this amazing tool!
