### ISSUE TITLE
Is it possible to rotate clockwise?

### ISSUE THREAD

**Issue by kjlee38** [guoyingtao/Mantis#49]
Is it possible to rotate clockwise?

**Comment by guoyingtao** [comment]
@kjlee38 Currently it only rotate anti-clockwise. I can make it configurable for rotating clockwise in the next release.

**Comment by kjlee38** [comment]
@guoyingtao Thank you for your answer. When will the next release be planned?

**Comment by guoyingtao** [comment]
@kjlee38 I plan to do it on this weekend.

**Comment by kjlee38** [comment]
@guoyingtao Oh great! Thank you so much~

**Comment by guoyingtao** [comment]
@kjlee38 I released Mantis 3.1.2 with a clockwise rotation demo.
Now you can choose to use clockwise rotation or counterclockwise rotation, or both.

![image](https://user-images.githubusercontent.com/26723384/83361784-f2d9d380-a359-11ea-8f34-326747c14291.png)

**Comment by kjlee38** [comment]
@guoyingtao Greate!! Thank you very much!
