### ISSUE TITLE
Misspelled "Protocal"

### ISSUE THREAD

**Issue by hyouuu** [guoyingtao/Mantis#5]
It should be Protocol see here :p https://www.dictionary.com/browse/protocal

**Comment by guoyingtao** [comment]
Thank you for the correction! I will fix it in the next version

**Comment by guoyingtao** [comment]
It is fixed in version 0.29.

**Comment by hyouuu** [comment]
Wow that's fast! Thanks!

**Comment by hyouuu** [comment]
Wow that's fast! Thanks!
