### ISSUE TITLE
SwiftUI implementation example

### ISSUE THREAD

**Issue by ClaesClaes** [guoyingtao/Mantis#50]
Hi, do you have (or know of) a SwiftUI example of using Mantis?

**Comment by guoyingtao** [comment]
I don't have a SwiftUI example of using Mantis currently, but I can work on it later.

**Comment by ejuden** [comment]
Here is some code I have for using it with SwiftUI, hope it helps.

`import Foundation
import SwiftUI
import Mantis


class MantisCoordinator: NSObject, CropViewControllerDelegate {
    
    var image: UIImage
    @Binding var showView: Bool
     var imageWasEdited: (UIImage?) -> Void
    
    init(image: UIImage, showView: Binding<Bool>, imageWasEdited: @escaping (UIImage?) -> Void) {
        
        self.image = image
        _showView = showView
         self.imageWasEdited = imageWasEdited
    }
    
    func cropViewControllerDidCrop(_ cropViewController: CropViewController, cropped: UIImage, transformation: Transformation) {
        //self.$image.wrappedValue = cropped
        imageWasEdited(cropped)
        self.$showView.wrappedValue = false
    }
    
    func cropViewControllerDidCancel(_ cropViewController: CropViewController, original: UIImage) {
        //self.$image.wrappedValue = original
        self.$showView.wrappedValue = false
    }
    
    func cropViewControllerDidFailToCrop(_ cropViewController: CropViewController, original: UIImage) {
        //self.$image.wrappedValue = original
        self.$showView.wrappedValue = false
    }
    
    func cropViewControllerWillDismiss(_ cropViewController: CropViewController) {
        self.$showView.wrappedValue = false
    }
    
    
}

struct MantisController: UIViewControllerRepresentable {
    func updateUIViewController(_ uiViewController: CropViewController, context: UIViewControllerRepresentableContext<MantisController>) {
    }
    
    
    var image: UIImage
    @Binding var showView: Bool
    
    var imageWasEdited: (UIImage?) -> Void
    
    var cropShape: CropShapeType = .ellipse(maskOnly: true)
    
    func makeCoordinator() -> MantisCoordinator {
        return(MantisCoordinator(image: self.image, showView: self.$showView, imageWasEdited: imageWasEdited))
    }
    
    func makeUIViewController(context: UIViewControllerRepresentableContext<MantisController>) -> CropViewController {
        
        var config = Mantis.Config()
        config.ratioOptions = [.custom]
        //config.presetFixedRatioType = .alwaysUsingOnePresetFixedRatio(ratio: 1.0)
        config.addCustomRatio(byVerticalWidth: 1, andVerticalHeight: 1)
//        config.addCustomRatio(byVerticalWidth: 2, andVerticalHeight: 2)
//        config.addCustomRatio(byVerticalWidth: 3, andVerticalHeight: 3)
//        config.addCustomRatio(byVerticalWidth: 4, andVerticalHeight: 4)
        //config.cropShapeType = .ellipse(maskOnly: true)
        config.cropShapeType = cropShape
        
        //config.cropShapeType = .rect
        //config.cropShapeType = .roundedRect(radiusToShortSide: 20, maskOnly: false)
        config.presetFixedRatioType = .alwaysUsingOnePresetFixedRatio(ratio: 1.0 / 1.0)
        config.showRotationDial = false
        

        let cropViewController = Mantis.cropViewController(image: image, config: config)
        
        cropViewController.modalPresentationStyle = .fullScreen
        cropViewController.mode =  .normal
        

        cropViewController.delegate = context.coordinator
        
        return(cropViewController)
        
    }
    
}
`

**Comment by ejuden** [comment]
Here is some code I have, hope it helps!

`import Foundation
import SwiftUI
import Mantis


class MantisCoordinator: NSObject, CropViewControllerDelegate {
    
    var image: UIImage
    @Binding var showView: Bool
     var imageWasEdited: (UIImage?) -> Void
    
    init(image: UIImage, showView: Binding<Bool>, imageWasEdited: @escaping (UIImage?) -> Void) {
        
        self.image = image
        _showView = showView
         self.imageWasEdited = imageWasEdited
    }
    
    func cropViewControllerDidCrop(_ cropViewController: CropViewController, cropped: UIImage, transformation: Transformation) {
        //self.$image.wrappedValue = cropped
        imageWasEdited(cropped)
        self.$showView.wrappedValue = false
    }
    
    func cropViewControllerDidCancel(_ cropViewController: CropViewController, original: UIImage) {
        //self.$image.wrappedValue = original
        self.$showView.wrappedValue = false
    }
    
    func cropViewControllerDidFailToCrop(_ cropViewController: CropViewController, original: UIImage) {
        //self.$image.wrappedValue = original
        self.$showView.wrappedValue = false
    }
    
    func cropViewControllerWillDismiss(_ cropViewController: CropViewController) {
        self.$showView.wrappedValue = false
    }
    
    
}

struct MantisController: UIViewControllerRepresentable {
    func updateUIViewController(_ uiViewController: CropViewController, context: UIViewControllerRepresentableContext<MantisController>) {
    }
    
    
    var image: UIImage
    @Binding var showView: Bool
    
    var imageWasEdited: (UIImage?) -> Void
    
    var cropShape: CropShapeType = .ellipse(maskOnly: true)
    
    func makeCoordinator() -> MantisCoordinator {
        return(MantisCoordinator(image: self.image, showView: self.$showView, imageWasEdited: imageWasEdited))
    }
    
    func makeUIViewController(context: UIViewControllerRepresentableContext<MantisController>) -> CropViewController {
        
        var config = Mantis.Config()
        config.ratioOptions = [.custom]
        //config.presetFixedRatioType = .alwaysUsingOnePresetFixedRatio(ratio: 1.0)
        config.addCustomRatio(byVerticalWidth: 1, andVerticalHeight: 1)
//        config.addCustomRatio(byVerticalWidth: 2, andVerticalHeight: 2)
//        config.addCustomRatio(byVerticalWidth: 3, andVerticalHeight: 3)
//        config.addCustomRatio(byVerticalWidth: 4, andVerticalHeight: 4)
        //config.cropShapeType = .ellipse(maskOnly: true)
        config.cropShapeType = cropShape
        
        //config.cropShapeType = .rect
        //config.cropShapeType = .roundedRect(radiusToShortSide: 20, maskOnly: false)
        config.presetFixedRatioType = .alwaysUsingOnePresetFixedRatio(ratio: 1.0 / 1.0)
        config.showRotationDial = false
        

        let cropViewController = Mantis.cropViewController(image: image, config: config)
        
        cropViewController.modalPresentationStyle = .fullScreen
        cropViewController.mode =  .normal
        

        cropViewController.delegate = context.coordinator
        
        return(cropViewController)
        
    }
    
}
`

**Comment by ClaesClaes** [comment]
Thanks Edward, much appreciated! Worked like a charm (almost). Xcode complained about the first 'func' in the 'struct'.

```
func updateUIViewController(_ uiViewController: CropViewController, context: UIViewControllerRepresentableContext) {
} 
```
The ommission of the `<MantisController>` after 'UIViewControllerRepresentableContext' seems related to how text is formated in this text field if it's not marked as 'code'. So just for clarity for others here's how it should read:
  
```
func updateUIViewController(_ uiViewController: CropViewController, context: UIViewControllerRepresentableContext<MantisController>) {
    }
```
