### ISSUE TITLE
Combine Impression into this?

### ISSUE THREAD

**Issue by hyouuu** [guoyingtao/Mantis#6]
Looks like the goal for Mantis is to "mimics most interactions in the Photos.app", which contains filter functionality - could we merge Impression into this? The Photos.app UI could be referred to. Thanks for sharing this!

**Comment by guoyingtao** [comment]
Thanks for your suggestion! I am thinking to use my other project Dahlia to combine them together. Still working on it.

**Comment by hyouuu** [comment]
Looking forward to it! Let me know if there's something I can help
