### ISSUE TITLE
CFBundleVersion is missing

### ISSUE THREAD

**Issue by codebeauty** [guoyingtao/Mantis#61]
Build for Release failed because of Mantis:

> ERROR ITMS-90056: "This bundle Payload/.../Frameworks/Mantis.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion"
Return status of iTunes Transporter was 1: ERROR ITMS-90056: "This bundle Payload/.../Frameworks/Mantis.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion"
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.

I can't find the reason why CFBundleVersion is missing but by adding it manually inside **/iOS/Carthage/Build/iOS/Mantis.framework** fixed the problem temporary.

**Comment by guoyingtao** [comment]
@codebeauty What is your Xcode version? I tried with XCode 12.0.1 and found a different error.
```
Build Failed
	Task failed with exit code 1:
...
This usually indicates that project itself failed to compile.
...
```

This [link](https://github.com/Carthage/Carthage/issues/3019) mentioned **Carthage builds fail at xcrun lipo on Xcode 12 beta (3,4,5...)**

**Comment by guoyingtao** [comment]
I tried one solution of the link above and it worked.
https://github.com/Carthage/Carthage/issues/3019#issuecomment-665136323

**Comment by guoyingtao** [comment]
@codebeauty Based on this linke https://github.com/Flight-School/AnyCodable/issues/20#issuecomment-493263003
It seems I need to hard code hard-coding CURRENT_PROJECT_VERSION to 1 to solve this problem.
I will fix it in the next release.

**Comment by codebeauty** [comment]
> @codebeauty What is your Carthage and Xcode version? I tried with XCode 12.0.1 and found a different error.
> 
> ```
> Build Failed
> 	Task failed with exit code 1:
> ...
> This usually indicates that project itself failed to compile.
> ...
> ```
> 
> This [link](https://github.com/Carthage/Carthage/issues/3019) mentioned **Carthage builds fail at xcrun lipo on Xcode 12 beta (3,4,5...)**

Yes, that lipo bug is temporary fixed for me by using the workaround with a tmp.xcconfig file mentioned in this thread. I'm using **Xcode 12.0.1** and **Carthage 0.36.0**
