### ISSUE TITLE
Fixed ratio breaks when zooming crop view out further than the width of the image

### ISSUE THREAD

**Issue by trung-belle** [guoyingtao/Mantis#63]
Steps to reproduce:
1. Set fixed ratio to 1/1.
2. Hold one corner of the crop view then drag it outwards to zoom out.
3. When the crop view reaches the full width of the image, continue zooming it out will break the 1/1 ratio.
If when I zoom out I do not release my finger and zoom back in immediately, the 1/1 ratio will be restored. But if I release my finger, the new ratio become fixed.
Below are the screenshots matching the steps.
![IMG_0969](https://user-images.githubusercontent.com/67924873/96831891-ad926d00-13f2-11eb-85d6-be61bed3cd91.PNG)
![IMG_0970](https://user-images.githubusercontent.com/67924873/96831893-af5c3080-13f2-11eb-9bf6-ebc93ad95487.PNG)
![IMG_0971](https://user-images.githubusercontent.com/67924873/96831894-aff4c700-13f2-11eb-90e6-f4aa292072fc.PNG)

**Comment by guoyingtao** [comment]
@trung-belle Thanks for the report! I fix it in the branch 63_fixed_ratio_break_bug. Can you help to check if the issue still exist?

**Comment by trung-belle** [comment]
Hi, sorry I have not been on GitHub for a while. I can confirm that the issue has been solved as of version 1.4.7. Thanks!
