### ISSUE TITLE
Add delegate hooks for responding to changes in crop prior to applying it

### ISSUE THREAD

**Issue by luke-oneill** [guoyingtao/Mantis#65]
I have the following use case:
* A parent view controller displays crop view controller and other UI elements.
   * The embedded crop view controller, which allows user to crop an image
   * A label that displays the current resolution of the cropped image
* The label should update in real time as the user uses touch gestures to adjust the crop

I don't think this is possible with the current hooks, as I have no way of being notified that the user touching/dragging/the crop has changed.

If this is possible, please could you point me in the right direction. Otherwise, I'd be happy to raise a PR to add support for this, but would be good to get some pointers to get my started!

**Comment by guoyingtao** [comment]
Mantis does not support the use cases you mentioned, so feel free to submit your PR for this feature.
Maybe you can start with CropView+Touches.swift and CropViewControllerDelegate in CropViewController.swift.
