### ISSUE TITLE
Effects CropVisualEffect Enhancement Request

### ISSUE THREAD

**Issue by ejuden** [guoyingtao/Mantis#68]
Thought others might benefit from this:

I have added a new enum to "CropVisualEffectType" (custom) in my code.
`public enum CropVisualEffectType {
    case blurDark
    case dark
    case light
    case none
    case custom(color: UIColor)
}`
modified "getEffect" to use it:
` static func getEffect(byType type: CropVisualEffectType) -> (UIVisualEffect?, UIColor) {
        switch type {
            case .blurDark: return (UIBlurEffect(style: .dark), .clear)
            case .dark: return (nil, UIColor.black.withAlphaComponent(0.75))
            case .light: return (nil, UIColor.black.withAlphaComponent(0.35))
            case .none: return (nil, .black)
            case .custom(color: let color): return(nil, color)
        }
    }`

I also changed the "cropToolbar" modifier to public in "CropViewController"

This allows me to change the background, toolbar colors to match:

`config.cropVisualEffectType = .custom(color: UIColor(named: "ThemeColor")!)
 cropViewController.view.backgroundColor = UIColor(named: "ThemeColor")
 cropViewController.cropToolbar.backgroundColor = UIColor(named: "ThemeColor")
`

**Comment by guoyingtao** [comment]
@ejuden Would you mind submitting a PR for that so I can review the code?
Also, maybe you can add a ThemeColor property to Mantis.Config instead of making `CropToolbar` public.

**Comment by ejuden** [comment]
I am not sure I created the PR correctly, looks like I have 4 separate patches for the same fix.


Edward

**Comment by apptekstudios** [comment]
@ejuden Do you have a branch with the entire fix committed to it? If you push that branch to your github fork it is easy to make a single PR from that 👍

**Comment by ejuden** [comment]
Ok, got a crash course on using PR in GitHub, never done that.  Thanks!

All done.


Edward

**Comment by guoyingtao** [comment]
@ejuden Since you submitted the PR(https://github.com/guoyingtao/Mantis/pull/73) for this ticket. I just close this ticket and we can do more discussions in the PR.
