### ISSUE TITLE
Clockwise rotation + rotation dial causes images to flip

### ISSUE THREAD

**Issue by luke-oneill** [guoyingtao/Mantis#75]
Hey, I discovered a bug when using clockwise rotation and rotation dial at the same time. I will try and look into this later but please let me know if you have any pointers on how to fix.

1. Select "Clockwise rotation" option in example project
2. Press rotate button to turn image clockwise 90°
3. Use the rotation dial to fine tune rotation.

Expected: Image rotates based on your drag
Actual: Image flips 180° as soon as you move the rotation dial

![Nov-20-2020 10-05-19](https://user-images.githubusercontent.com/5530491/99787801-1a934280-2b18-11eb-83b8-79445b08ea95.gif)

**Comment by guoyingtao** [comment]
@luke-oneill Thanks for the report. It is a bug. I fixed it in PR #76

**Comment by guoyingtao** [comment]
I released Mantis 1.4.7 which fixes this issue.
