### ISSUE TITLE
Apply transformations to a different ratio

### ISSUE THREAD

**Issue by alessiolapenna** [guoyingtao/Mantis#77]
Assuming I have an Image and some transformations that Mantis gave me when applying a certain fixed aspect ratio, is there any way at the moment to keep those transformations (or well migrating them) to a different aspect ratio?

For example, I have zoomed in an image in a vertical aspect ratio 4:3, now I'd like to change the aspect ratio to horizontal or square but I'd still like to see the zoomed image without resetting all transformations. 

Thanks for your work.
Regards,
Alessio

**Comment by guoyingtao** [comment]
@alessiolapenna I may not understand your question very well. Since when you change the aspect ratio, it won't reset all transformations. Can you give more descriptions about it? Do you mean you want to get a new aspect ratio image based on a zoomed image and previous ratio like 4:3 programmatically not do it via Mantis UI?

**Comment by alessiolapenna** [comment]
@guoyingtao 

Thanks for your prompt reply.
Here is the flow:

1. User edit a photo using Mantis UI, applying a ratio (example 1:1.3)
2. The app gets a transformation object from interaction at point 1
3. User select a different aspect ratio in our UI
4. The app open edit mode again with Mantis UI with a new fixed aspect ratio (example 2:1)

What I'm trying to achieve is to apply the transformations that I got at point 2, to the new aspect ratio in point 4.

**Comment by guoyingtao** [comment]
@alessiolapenna The current logic of Mantis does not support it. I need to add some code for it.

**Comment by alessiolapenna** [comment]
@guoyingtao Thank you. That would be great. If you don't have time to do that, can you give me some directions on how to migrate transformation data between aspect ratios?

**Comment by guoyingtao** [comment]
@alessiolapenna Can you try using 
```Ruby
pod 'Mantis', :git => 'https://github.com/guoyingtao/Mantis', :commit => 'f8ec3d25fd1e598495f4f4dd2be83f2203542f94'
```
 to see if it works for you? If it does, I will release a new version later.

**Comment by alessiolapenna** [comment]
@guoyingtao sure, how should I proceed? Just pass the presettransformation i got in a different ratio and see if it works, right?

**Comment by guoyingtao** [comment]
I think you can use some code like below
```Swift
var config = Mantis.Config()
config.presetTransformationType = .presetInfo(info: transform)
config.presetFixedRatioType = .alwaysUsingOnePresetFixedRatio(ratio: <Your new fixed aspect ratio>)
```

**Comment by guoyingtao** [comment]
I think the issues in this ticket is solved in the latest version of Mantis so I close this ticket for now.
You can reopen it if you found more issues about it.
