### ISSUE TITLE
Choose default ratio but allow fixed-ratio button to be shown

### ISSUE THREAD

**Issue by roddymunro** [guoyingtao/Mantis#79]
I have a custom ratio that I would like to be set when opening an image (2:1). However, I would also like users to have the option of changing the ratio themselves.

I have tried `config.presetFixedRatioType = .alwaysUsingOnePresetFixedRatio(ratio: 2.0)`, but this doesn't allow the ratio to be changed.

I have also used `config.addCustomRatio(byHorizontalWidth: 2, andHorizontalHeight: 1)`, but I see no way to set the default crop ratio.

Is there something I'm missing, or should this be a feature request? Thank you.

**Comment by guoyingtao** [comment]
@roddymunro I think this is a feature request. I can support this feature in the next release.

**Comment by guoyingtao** [comment]
I released Mantis 1.4.8. Can you check if it can solve this issue?
You can use MantisConfig.presetFixedRatioType = canUseMultiplePresetFixedRatio(defaultRatio: <Your ratio>)

**Comment by roddymunro** [comment]
@guoyingtao Thank you, that seems to work nicely. I appreciate you doing this so quickly!
