### ISSUE TITLE
Can we use this library with Objective-C project?

### ISSUE THREAD

**Issue by georgek1991** [guoyingtao/Mantis#8]
I am working on an Obj-C project and I would like to use this library in my project. Does this library supports Obj-C project. Can you please specify steps to use it.

**Comment by guoyingtao** [comment]
There is some way to import a swift framework to your Obj-c project. Like this one
https://medium.com/@anum.amin/swift-pod-library-in-objective-c-project-c6d1c5af997d
I haven't tried it but maybe you can try it.
