### ISSUE TITLE
Set image container inside the cropper

### ISSUE THREAD

**Issue by zeeshanTeks** [guoyingtao/Mantis#83]
Hi,

Is it possible fit the image container view inside the cropper initially(image attached)? Then after user can zoom in/out.
Attached image shows how it should look. The image will be centred. I tried to zoom in as much as i can, but the image should be fully inside the cropper and centred, with white background(if possible)

We have a fixed ratio for cropper. i.e., 4x6 and 5x7

First image is how it looks now.
Second image is a close representation of how it should look.

Any help is appreciated. Thanks.

**Original:**
![Simulator Screen Shot - iPhone 8 Plus - 2021-02-04 at 19 03 05](https://user-images.githubusercontent.com/42762977/106899672-a67e3900-671b-11eb-86e6-703240a32e0c.png)

**Requirement:**
![Simulator Screen Shot - iPhone 8 Plus - 2021-02-04 at 18 47 05](https://user-images.githubusercontent.com/42762977/106897793-6b7b0600-6719-11eb-9ad8-8c4050fed389.png)

**Comment by guoyingtao** [comment]
This feature seems only for specific usage and I don't think I have enough time to do it. So I just close it for now as it has been two years.
