### ISSUE TITLE
Error message when image is a a screenshot

### ISSUE THREAD

**Issue by Brakkar** [guoyingtao/Mantis#89]
Hello,
I notice this behavior ONLY when image loaded in the cropper is a screenshot image ( taken with simultaneously pressing iPhone ON and Volume + buttons) thus loaded from library:

1) As soon as the image appears in the target UIImageview, it very quickly zoom on the image just slightly.
2) In the log window on xcode I can read the message below. It doesn't prevent the system from working. It works fine.

CGBitmapContextCreate: unsupported parameter combination:
 	16 bits/component; integer;
 	64 bits/pixel;
	RGB color space model; kCGImageAlphaLast;
	kCGImageByteOrder16Little byte order;
	8128 bytes/row.
Valid parameters for RGB color space model are:
	16  bits per pixel,		 5  bits per component,		 kCGImageAlphaNoneSkipFirst
	32  bits per pixel,		 8  bits per component,		 kCGImageAlphaNoneSkipFirst
	32  bits per pixel,		 8  bits per component,		 kCGImageAlphaNoneSkipLast
	32  bits per pixel,		 8  bits per component,		 kCGImageAlphaPremultipliedFirst
	32  bits per pixel,		 8  bits per component,		 kCGImageAlphaPremultipliedLast
	32  bits per pixel,		 10 bits per component,		 kCGImageAlphaNone|kCGImagePixelFormatRGBCIF10
	64  bits per pixel,		 16 bits per component,		 kCGImageAlphaPremultipliedLast
	64  bits per pixel,		 16 bits per component,		 kCGImageAlphaNoneSkipLast
	64  bits per pixel,		 16 bits per component,		 kCGImageAlphaPremultipliedLast|kCGBitmapFloatComponents|kCGImageByteOrder16Little
	64  bits per pixel,		 16 bits per component,		 kCGImageAlphaNoneSkipLast|kCGBitmapFloatComponents|kCGImageByteOrder16Little
	128 bits per pixel,		 32 bits per component,		 kCGImageAlphaPremultipliedLast|kCGBitmapFloatComponents
	128 bits per pixel,		 32 bits per component,		 kCGImageAlphaNoneSkipLast|kCGBitmapFloatComponents
 See Quartz 2D Programming Guide (available online) for more information.

**Comment by guoyingtao** [comment]
Hi @Brakkar, thanks for the feedback!
I could not reproduce the issue you mentioned on my iPhone 11. Could you add more information about the device you were using? Thanks!

**Comment by Brakkar** [comment]
Hi @guoyingtao,

i have an iphone XS on iOS 14.2.

I can reproduce the error message on iPhone 11 simulator and the image from this link.
I add it as a link because i'm not sure if github upload would alter the image in a way that may not cause the problem.
https://fromsmash.com/screenshotimage

**Comment by guoyingtao** [comment]
@Brakkar Thanks for image. I reproduced the issue this time.
It is because the code below.

Usually code 1 works. When code 1 does not work, it will give the warning you mentioned before. Then code 2 or code 3 will handle it.

For your image, code 2 handled it.

It is not a graceful solution and there are cases I haven't handled yet.
I will improve the code later to make it more general.

```Swift
// 1
var context = CGContext(data: nil,
                                width: Int(outputSize.width),
                                height: Int(outputSize.height),
                                bitsPerComponent: self.bitsPerComponent,
                                bytesPerRow: bitmapBytesPerRow,
                                space: colorSpaceRef,
                                bitmapInfo: self.bitmapInfo.rawValue)

       // 2
        if context == nil {
            context = CGContext(data: nil,
            width: Int(outputSize.width),
            height: Int(outputSize.height),
            bitsPerComponent: self.bitsPerComponent,
            bytesPerRow: bitmapBytesPerRow,
            space: colorSpaceRef,
            bitmapInfo:CGImageAlphaInfo.premultipliedLast.rawValue)
        }
        
       // 3
        if context == nil {
            context = CGContext(data: nil,
            width: Int(outputSize.width),
            height: Int(outputSize.height),
            bitsPerComponent: self.bitsPerComponent,
            bytesPerRow: bitmapBytesPerRow,
            space: colorSpaceRef,
            bitmapInfo:CGImageAlphaInfo.premultipliedFirst.rawValue)
        }
```

**Comment by guoyingtao** [comment]
@Brakkar I released Mantis 1.5.0 which removed the warning.
I did not notice "**As soon as the image appears in the target UIImageview, it very quickly zoom on the image just slightly.**"
Can you check if it still happens in this version? Thank you!

**Comment by Brakkar** [comment]
@guoyingtao  thank you for the fix. I can confirm I don't get the error message anymore.
As for the behavior, please look at that video: https://fromsmash.com/microzoom

You can notice that as soon as the image gets in the mantis square selection area, it zoom slightly.
It doesn't do this with image taken from camera, again, it seems to affect only images from screenshot.
I can reproduce this in simulator of iPhone 11 and probably others.

**Comment by guoyingtao** [comment]
@Brakkar I release Mantis 1.5.1 which fixed this issue. Can you check it again to see if the issue is solved or not on your side? Thank you!

**Comment by Brakkar** [comment]
@guoyingtao I confirm it is resolved. It feels much cleaner. Thanks.
