### ISSUE TITLE
Auto scale when set ratio 9:16

### ISSUE THREAD

**Issue by nthnhung23** [guoyingtao/Mantis#93]
When i set config like this:
`config.presetFixedRatioType = .alwaysUsingOnePresetFixedRatio(ratio: 9.0 / 16.0)`
image auto scale. How to not scale this?

https://user-images.githubusercontent.com/75512024/112818216-7c0e8380-90ad-11eb-8f8b-e9091d80722a.MP4

**Comment by guoyingtao** [comment]
@nthnhung23 Which version are you using? I think it was solved in the latest version 1.5.1

**Comment by nthnhung23** [comment]
> @nthnhung23 Which version are you using? I think it was solved in the latest version 1.5.1

yes, thank you. But i have new issue.
I try crop like video, ratio frame will change error.

And How do I keep ratio frame and only change image?

https://user-images.githubusercontent.com/75512024/112930915-5df46200-9145-11eb-89b1-c179f0f74d04.MOV

**Comment by guoyingtao** [comment]
@nthnhung23 Mantis does not support video crop. Do you mean animation GIFs?

**Comment by guoyingtao** [comment]
@nthnhung23 Mantis does not support video crop. Do you mean animation GIFs?

**Comment by nthnhung23** [comment]
> @nthnhung23 Mantis does not support video crop. Do you mean animation GIFs?

No, video is demo bug. I crop only image

**Comment by guoyingtao** [comment]
@nthnhung23 Can you provie more information about your iOS device? Does it happen to any photos you are using? Thank you!

**Comment by nthnhung23** [comment]
> @nthnhung23 Can you provie more information about your iOS device? Does it happen to any photos you are using? Thank you!

this problem any device and photos i used.

**Comment by guoyingtao** [comment]
@nthnhung23 Does it also happen when you use the Example App?

**Comment by guoyingtao** [comment]
@nthnhung23 I reproduced this issue. I will check it later when I have enough time.
