### ISSUE TITLE
It keeps zooming in when switching between Original and Square ratio

### ISSUE THREAD

**Issue by kien-huubap** [guoyingtao/Mantis#99]
When the device is in landscape orientation, switching between Original and Square ratio will keeping zooming in on the image, as shown below.

![landscape_zoomed](https://user-images.githubusercontent.com/56101510/115488962-f639be80-a28d-11eb-8dc8-2a9e0cf08ecf.gif)

Steps to reproduce:
1. Open the crop view in landscape.
2. Tap on "Square" ratio, the image is zoomed in.
3. Tap on "Original" ratio, the crop frame is changed.
4. Tap on "Square" ratio again, the image is zoomed in further.

If we keep repeating step 3 and 4, it will just keep zooming in.

It works just fine when the device is in portrait orientation.

![portrait_works_fine](https://user-images.githubusercontent.com/56101510/115489344-a4ddff00-a28e-11eb-8d36-3ffd5ea1e369.gif)

**Comment by guoyingtao** [comment]
@kien-huubap Thanks for the report! I fixed it in a branch
Do you mind helping to test it by using the commit below to see if it solve the issue? Thanks 
```Ruby
pod 'Mantis', :git => 'https://github.com/guoyingtao/Mantis.git', :commit => '71f6d9463d6c8698039bd62017afc7401d219136'
```

**Comment by kien-huubap** [comment]
@guoyingtao Nice! I tested it and it works fine now! 👍 

![mantis_fixed](https://user-images.githubusercontent.com/56101510/115647707-e3d78780-a356-11eb-8fd8-1aeed3bb82ad.gif)

Again, thanks for the great work! 👍

**Comment by guoyingtao** [comment]
@kien-huubap Thanks for the tests. I will include this fix in the next release of Mantis.
